### ISSUE TITLE
Fillable box not available

### ISSUE THREAD

**Issue by StephanBruh** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#1]
Printing an error with; Fillable box not available

I set show browser to true, to see what it is doing. It is opening the bet menu correctly and does click the custom amount button and you can fill in a custom amount. But it does throw the error.

**Comment by Tkd-Alex** [comment]
Have you a list of streamer that usually do predictions? This can help me to debug

**Comment by Tkd-Alex** [comment]
![image](https://user-images.githubusercontent.com/14061593/104660274-7ae0d380-56c6-11eb-9a5e-5c5a092f4a66.png)

Also in your case the text-button for make the input fillable is not 100% show?

**Comment by jhagin002** [comment]
It shouldn't matter if it's 100% shown, selenium should still be able to click it as doesn't need to physically be able to see the element to interact with it. And also like he said, it is being clicked. There is an issue with getting the text box where you input the custom amount. I don't know what the website html looks like when there's a prediction going on when you have the channel points tab open, with the predictions thing clicked, then the bet custom amount part. You could probably just find the text box element and then just do `element.send_keys(custom_amount)`.

I haven't really looked much at your code so idk if you are doing that already.

**Comment by StephanBruh** [comment]
> Have you a list of streamer that usually do predictions? This can help me to debug

Well forsen and nymn mainly, but cant you start predictions on your own channel and set the bot to a alt? If not just dm me on discord stephan#0001 and I can run predictions for you in my/other channels for you to debug and help the development.

**Comment by jhagin002** [comment]
You have to be an affiliate to start predictions.

**Comment by StephanBruh** [comment]
> You have to be an affiliate to start predictions.

Ah okay didn't know that but I'm a affiliate so should be good :)

**Comment by jhagin002** [comment]
Yep, should work out then.

**Comment by StephanBruh** [comment]
Yep fixed in latest commit! Thanks
