### ISSUE TITLE
Less text in terminal

### ISSUE THREAD

**Issue by Olamio** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#10]
There should be an option in run.py that would simplify the displayed text in the terminal. I think I already saw something commented in some file that just said "xx channel points for yy". Why not have that for everything that can happen? So for example:

**_21/01/21 23:33:19 - INFO - [on_message]: +10 → Streamer(username=streamer_username, channel_id=x, channel_points=y) - Reason: WATCH._**
would just be
**_21/01/21 23:33:19 - +10 cp for streamer_username_**

or

**_21/01/21 23:45:44 - INFO - [on_message]: +50 → Streamer(username=streamer_username, channel_id=x, channel_points=y) - Reason: CLAIM._**
would just be
**_21/01/21 23:33:19 - +50 cp for streamer_username_**.

Especially bets fill up the screen really quick. So they could just be "streamer_username has started a bet called name_of_bet" and "Placing a bet for streamer_username for name_of_bet_" and at the end just "Won/Lost bet for x cp on name_of_bet of streamer_username" or whatever.

I like having it on the second monitor but I don't like that its filling up the screen if a lot of nonsense to me.

**Comment by Tkd-Alex** [comment]
Ok maybe I exaggerated with the logs, I have a 21: 9
I will do tomorrow ...

**Comment by testdev123456** [comment]
i would remove the 'seconds' as well..  since it's not a busy log.

**Comment by Tkd-Alex** [comment]
> i would remove the 'seconds' as well.. since it's not a busy log.

I'm not agree to remove 'seconds' , I will remove the year in the 'less version'

**Comment by Tkd-Alex** [comment]
Better?

![image](https://user-images.githubusercontent.com/14061593/105486672-284b7c80-5caf-11eb-90ad-931b96ce84fc.png)

**Comment by StephanBruh** [comment]
Yes much better!

**Comment by rindes** [comment]
Hello @Tkd-Alex, for me the less=True, dosen't work correct.

![error_censored](https://user-images.githubusercontent.com/36708183/115946960-e526c280-a4c4-11eb-9e9d-a04367d2c8fb.jpg)

Can you possible help me here?
