### ISSUE TITLE
 RuntimeError(f"Error while trying to listen for a topic: {response}")      

### ISSUE THREAD

**Issue by sludgefudge01** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#101]
`28/02/21 21:33:23 - ERROR - [error]: error from callback <function WebSocketsPool.on_message at 0x000002785EA09280>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'KLcOnmGJWk73CFWHo9PWy9yXNwLxI5'}                                                                                                                    File "C:\Python38\lib\site-packages\websocket\_app.py", line 346, in _callback                                            callback(self, *args)                                                                                                 File "C:\Users\Admin\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 367, in on_message                                                                                                   raise RuntimeError(f"Error while trying to listen for a topic: {response}")      `

**Comment by dmunozv04** [comment]
Could you try to erase the cookie file? found on:
 ```cookies/{your-user}.pkl```

**Comment by Tkd-Alex** [comment]
Please try to delete the cookie file and re-login again

**Comment by sludgefudge01** [comment]
Worked after erasing cookies, thank you guys!
