### ISSUE TITLE
Points spent events are never processed

### ISSUE THREAD

**Issue by RakSrinaNa** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#103]
While testing #96 I wondered why the points spent never showed up.

Seems to be that the payload sent by twitch doesn't work the same as when points are earned (everything hidden in red is my channel id):
![image](https://user-images.githubusercontent.com/1688389/109965407-37cad600-7cef-11eb-9a9a-ef3543f24eae.png)

The `channel_id` of the message isn't the id of the watched channel, but the id of our channel
Basically it seems like the `channel_id` is the one of the channel that sent points:
* when winning points it's the streamer, as it gives points to us
* when spending it's us as we give points to the streamer

So when we try to get the streamer, it always returns -1 (`message.channel_id != ws.streamers[i].channel_id` when points are spent).
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/7de7ea62e039f7183785d4289a1a6b551bd0af56/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L176-L177

**Comment by Tkd-Alex** [comment]
Then? I don't understand this issue.
We aren't unable to know where we have spent the points, but as you already say the Twitch payload don't share the channel_id of the streamer but our id.

**Comment by Tkd-Alex** [comment]
OK. I've read your comment https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/96.
So you think we should find a way to know where we have spent the points, so we can adjust the chart?

**Comment by RakSrinaNa** [comment]
Well, in the analytics branch you clearly use that event, which to me makes sense (to update the chart when we spend points)

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/5d7478e027ba675b2c3016544be9deaba638efb6/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L180

Though the way the event is handled, it'll never go past that check:
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/5d7478e027ba675b2c3016544be9deaba638efb6/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L176-L177

**Comment by Tkd-Alex** [comment]
I'm feel so stupid :cry: 
You are right!
