### ISSUE TITLE
Select a Game where the Bot is watching the Streams from

### ISSUE THREAD

**Issue by mrcsdl** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#105]
It would be cool if you could add a ability to turn on a setting that for example i have 

10 Streamers in my Config -> if one of them is playing a specific game than only this one getting farmed if there are 2 Than 2 
with the priority as it is normal from top to bottom.

Hope you understand what i mean

**Comment by Yishaqel** [comment]
All the streams I watch are from the same game, yes I agree to have an option to be able to choose in which channel to collect points but if I have not asked for this suggestion before it is because I think it is not possible.

**Comment by Tkd-Alex** [comment]
I don't have answered to this Issue because currently I don't have too much free time and at first read I don't have understood what do you want.

Why this PR was closed?

**Comment by Yishaqel** [comment]
I also don't know why it has been closed...
I would like to know if it is possible to choose in which channels you want to collect points with preference and if it is compatible with the current configuration of the bets.

**Comment by Yishaqel** [comment]
Currently everyone I watch plays the same game, so I guess it would be nice to add a priority of people to watch, to earn points on that channel and not on the others. Is this possible without affecting multi betting?

**Comment by Tkd-Alex** [comment]
Just change the orders of the streamers, no?

**Comment by Yishaqel** [comment]
Yes, I guess that would be fine since I am currently loading over 70 streamers and it randomly picks up points from channels where I don't really need it since I win with the program's bets.

**Comment by Tkd-Alex** [comment]
Sorry, but I Have difficult to understand what do you want or need.
The streamers will watch with the priority and not randomly. The script has a priority system

**Comment by Yishaqel** [comment]
> Sorry, but I Have difficult to understand what do you want or need.
> The streamers will watch with the priority and not randomly. The script has a priority system

I thought I was currently collecting points at random :/

**Comment by mrcsdl** [comment]
> So for example if you have:
> 
> * Streamer1 online
> * Streamer2 online
> * Streamer3 online
> * Streamer4 online
> 
> The script with default config will watch 1 and 2, but If Streamer4 will start playing **Game1** (for example) you would to watch Streamer4
> 
> * Streamer4
> * Streamer1
> * Streamer2
> * Streamer3
> 
> It's correct?

This is correct, so we can use the bot as well as a Drop farmer for like rust. It’s hard to get drops from NA streamers when you are from EU. And letting the pc running dose costs to much. So it would be nice to do this with your bot as well, Iam running your bot on a raspberrypi and the costs of running a pi 24/7 is affordable :D

**Comment by Tkd-Alex** [comment]
Have you tried the drops priority?

**Comment by mrcsdl** [comment]
No I haven’t tried that, but I think the problem is, that the bot can not detect if the 2h are over or how long it takes to get the drop into my inventory. So it keeps idling I guess. Or am I wrong with that?

**Comment by Tkd-Alex** [comment]
> No I haven’t tried that, but I think the problem is, that the bot can not detect if the 2h are over or how long it takes to get the drop into my inventory. So it keeps idling I guess. Or am I wrong with that?

I think you are wrong. We are working a lot on drops and inventory.
Read here: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/68
