### ISSUE TITLE
No Website under :5000

### ISSUE THREAD

**Issue by mrcsdl** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#109]
**Describe the bug**
Trying to open up the web panel on 192.168.178.52:5000 or localhost:5000

**To Reproduce**
1. Starting the bot in screen
2. Trying with my pc to connect to the website 
3.  There is no website

**Desktop (please complete the following information):**
 - OS: Rasbian OS Lite newest version
 - Python version 3.7

**Comment by Tkd-Alex** [comment]
Are you on the right branch? Currently analytics web page It's under development. 

Master branch It's without analytics web page

**Comment by mrcsdl** [comment]
Okay thanks for the info
