### ISSUE TITLE
Unable to claim Bonus Points after Reconnect

### ISSUE THREAD

**Issue by PureFallen** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#114]
**Describe the bug**
When trying to claim Bonus "Chests" on a Stream while the connection is interrupted by a DHCP Handshake (daily forced disconnect by ISPs in some countries to change the IP Address, update Time Server, DNS Server etc...), the program afterwards sometimes fails to claim said Bonus "Chests" until restarted or Streamers changed.

**To Reproduce**
1. Run the Script
2. Wait for a DHCP Handshake
3. After reconnect, it may be no longer Bonus Chests collected for some Streamer

![cSDl8tT](https://user-images.githubusercontent.com/68307987/111025870-ef8e7080-83de-11eb-875f-9712c8347871.png)

**Expected behavior**
After reconnect, the script should be able to check for Bonus Chests and claim those again, just like with sending watch_time.

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Python version: 3.7.3

**Additional context**
The error happens consistent enough to cost points, but not consistant enough to make it easy to reproduce.
Looking forward to digging through the Debug-Log the next time it happens (previously had logging disabled to reduce wear on the SD Card).
Also going to try out if this is really connected to DHCP Handshakes nature of changing the external IP Address the script has, or if basically any disconnect could cause this issue.

**Comment by PureFallen** [comment]
Something got inbetween, got into testing around a bit more and tried to look into the Debug log.
Apparently the script never received another "claim-available" response from Twitch, when Twitch did send that information before while disconnected.
Looking at that, the script seems to check at start if a bonus claim is available.... is that implemented for a reconnect as well?

**Comment by Tkd-Alex** [comment]
@PureFallen should be fixed with the latest commit

**Comment by PureFallen** [comment]
> 
> 
> @PureFallen should be fixed with the latest commit

Alright, i will try out tonight and see how it goes :)

**Comment by PureFallen** [comment]
Reporting in, works as expected. Thank you for the quick fix.
