### ISSUE TITLE
What does this part of code entail? (Explain it like I'm five, please).

### ISSUE THREAD

**Issue by noord101** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#118]
Just wondering what these lines of codes mean. I have managed to set up the bot correctly, but for some reason the bet on a channel didn't go through since the value was 800. What does the value mean and the other stuff?

by=OutcomeKeys.TOTAL_USERS,    # Where apply the filter. Allowed [PERCENTAGE_USERS, ODDS_PERCENTAGE, ODDS, TOP_POINTS, TOTAL_USERS, TOTAL_POINTS]
                where=Condition.LTE,           # 'by' must be [GT, LT, GTE, LTE] than value
                value=800

**Comment by KableK42** [comment]
That will filter out all bets that have less than or equal to 800 participants.

GT = Greater than
LT = Less than
GTE = Greater than or equal
LTE = Less than or equal

Total users = total participants in the bet

The rest of the types of filters are explained here:
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#filtercondition
