### ISSUE TITLE
Add Millify to requirements.txt

### ISSUE THREAD

**Issue by RakSrinaNa** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#12]
**Describe the bug**
Millify dependency was added in 878012026e95bf7e19a13944eb0a6dd09db3dda4 & a9cf39f28607507309c81f2c8cb797a79d9cf00c.

This dependency should also be added in the requirements.txt file.

**Comment by Tkd-Alex** [comment]
It's already present 🧐
