### ISSUE TITLE
Bugged Analytics Annotations

### ISSUE THREAD

**Issue by KillaBoi** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#122]
**Describe the bug**
Analytic Annotations are bugged when switching to another streamer and remain on the page

**To Reproduce**
1. Add multiple streamers to the miner
2. Mine some streamers especially those where predictions have to be made
3. Notice that the annotations remain for the streamer you were originally looking at even if you switch to another streamers tab.

**Expected behavior**
Annotations should be removed for the previous streamer and show the new tabs annotations

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1038-gcp x86_64)
 - Python version Python 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0] on linux

**Additional context**
GIF of issue: https://i.imgur.com/9EkRoW4.gif

**Comment by Tkd-Alex** [comment]
I don't know why but the gif still loading :disappointed:

**Comment by KillaBoi** [comment]
> I don't know why but the gif still loading 😞

Probably because it's kinda big, here's a streamable link of the same gif https://streamable.com/7ygtrc

**Comment by Tkd-Alex** [comment]
Thanks :smile_cat: 
What's the browser?

**Comment by KillaBoi** [comment]
Tried with Microsoft Edge 89.0.774.57 and Firefox 87.0, both are doing the same thing.

**Comment by kelukelol** [comment]
Same issue here, have tried it with Opera GX (73.0.3856.421) and Google Chrome (89.0.4389.90).
Windows 10, Python version 3.9.2

**Comment by Tkd-Alex** [comment]
I'm not able to reproduce :crying_cat_face:

**Comment by KillaBoi** [comment]
Idk if its a browser issue or an install issue or something but would you like to test with the version currently running on my server? If so, I can link to you privately via email or something?

**Comment by Tkd-Alex** [comment]
You are not the only one with this error. 
Maybe I'm the problem :rofl: 

If you have your server accessible from the outside yes to reach me privately, you can write everywhere you want

**Comment by KillaBoi** [comment]
> You are not the only one with this error.
> Maybe I'm the problem 🤣
> 
> If you have your server accessible from the outside yes to reach me privately, you can write everywhere you want

will send the ip to you on twitter

**Comment by Tkd-Alex** [comment]
Should be fixed in the related commit, please try :smile_cat:

**Comment by KillaBoi** [comment]
can confirm fixed, tyvm!
