### ISSUE TITLE
Join IRC chat to multiple streamers

### ISSUE THREAD

**Issue by misterkoko** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#124]
**Describe the bug**
If you join IRC chat to increase watch time and you have multiple streamers in the array, you only show as online on the streamers chat that's first in the array.

**To Reproduce**
Input multiple streamers to the array and set join_chat to true

**Expected behavior**
I expected I'll see my username online on all the channels.

**Desktop (please complete the following information):**
 - OS: Linux
 - Python version 3.8.5

**Additional context**
It claims the bonuses fine and it joins the IRC chat of the first username in the array. On that first channel it's increasing the watchtime great. Is it possible that you're actually joined on other channels usernames and you just can't see yourself in chat? I also don't know if the watchtime increases on other channels.

**Comment by testdev123456** [comment]
it's working fine on my end.
the list of IRC users in twitch chat has a delay of up to 5 minutes... so make sure you wait that time before checking if you're on the list or not.

**Comment by misterkoko** [comment]
Don't remember the specific time I checked. Is there any odd possibility that even if you don't appear in the chat list it counts towards the watchtime? I'll be closing the issue anyway, thank you for the fast response.

**Comment by testdev123456** [comment]
all bots I know ( like streamelements ) collect watchtime by checking your time spent in the IRC user list while streamer is live.
