### ISSUE TITLE
dropCampaign exception

### ISSUE THREAD

**Issue by Dennis-Mulder** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#128]
**Describe the bug**
An exception occurred while the script was running. After restarting the script I immediately get the same exception after it loaded the streamers.
```
Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\opt\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 561, in sync_campaigns
    campaigns_details = self.__get_campaigns_details(
  File "C:\opt\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 501, in __get_campaigns_details
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
  File "C:\opt\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 501, in <lambda>
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
TypeError: string indices must be integers
```

**To Reproduce**
Unclear, it seems that there is a drop that causes an issue.

**Expected behavior**
No exception in the console :)

**Desktop (please complete the following information):**
- Windows 10
- Python 3.9.2

**Additional context**
I'm on the latest version of the script (2f373bf)

**Comment by Tkd-Alex** [comment]
Did you know the drop? Or maybe we can find it based on your inventory?

**Comment by Dennis-Mulder** [comment]
It looks like this is the one, this is the only drop in my inventory
![image](https://user-images.githubusercontent.com/22026742/113360281-bbf19700-9349-11eb-9500-aa533df5aaff.png)
https://www.twitch.tv/drops/campaigns?dropID=a7feb360-305b-4f9b-9d5b-b8df8d14e3a1

**Comment by kelukelol** [comment]
I don't use the drops function in the script since I don't play a lot of video games, but I get the same issue.
Windows 10
Python v. 3.9.2

**Comment by Tkd-Alex** [comment]
Should be fixed in the related commit, please try :smile_cat:

**Comment by Dennis-Mulder** [comment]
I get an new error now when I start the script:
```
Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\opt\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 569, in sync_campaigns
    campaigns_details = self.__get_campaigns_details(
  File "C:\opt\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 497, in __get_campaigns_details
    chunks = create_chunks(campaigns)
TypeError: create_chunks() missing 1 required positional argument: 'n'
```

**Comment by Yishaqel** [comment]
> I get an new error now when I start the script:
> 
> ```
> Exception in thread Sync campaigns/inventory:
> Traceback (most recent call last):
>   File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
>     self.run()
>   File "C:\Program Files\Python39\lib\threading.py", line 892, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\opt\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 569, in sync_campaigns
>     campaigns_details = self.__get_campaigns_details(
>   File "C:\opt\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 497, in __get_campaigns_details
>     chunks = create_chunks(campaigns)
> TypeError: create_chunks() missing 1 required positional argument: 'n'
> ```

I guess we all received the same error after upgrading

**Comment by Tkd-Alex** [comment]
LoL, sorry it's bed time 💤
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/f7856203fff4e59bca4fe63118fa8dee13984d54

**Comment by Dennis-Mulder** [comment]
Looks like it's fixed. I no longer get an exception while starting the script.

**Comment by Tkd-Alex** [comment]
Nice, after a few days please close the issue :)

**Comment by zTigerrrr** [comment]
I get the same error.

**Comment by Tkd-Alex** [comment]
> I get the same error.

With the latest commit? :thinking:

**Comment by zTigerrrr** [comment]
> > I get the same error.
> 
> With the latest commit? 🤔

I have no clue. Sorry, but I don't really get how all of this works, the commits and all. I don't know how to upgrade the script either. I'm a total noob at all of this.

**Comment by Tkd-Alex** [comment]
@zTigerrrr You can try with `git pull` inside the directory or download again ^^

**Comment by zTigerrrr** [comment]
> @zTigerrrr You can try with `git pull` inside the directory or download again ^^

I'm kind of ashamed of asking this, because it's probably dumb and you have tons of other things to do. But I have cloned the repository to GitHub Desktop and used fetch origin. I think this works? But I am just asking to be sure. :)

**Comment by Tkd-Alex** [comment]
> > @zTigerrrr You can try with `git pull` inside the directory or download again ^^
> 
> I'm kind of ashamed of asking this, because it's probably dumb and you have tons of other things to do. But I have cloned the repository to GitHub Desktop and used fetch origin. I think this works? But I am just asking to be sure. :)

Yup, should be OK
The error still persist?
