### ISSUE TITLE
terminal log - minor fixes & improvements

### ISSUE THREAD

**Issue by testdev123456** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#13]
- if emoji=False there's still a \u2192 ( → ) print on most lines. that should be gone.
- the entire line print of "claiming the bonus for..." is redundant and unnecessary. we already see the +50 claim line.   
- the " Streamer: " is also redundant as well, as they're all streamers.
- prediction lines should mention streamer's name, or at least on the first line "Start betting for.."
- I think total channel_points is important to add. it doesn't take much space.
       like:     **time - +50 - username - total - reason**

;o)

**Comment by Tkd-Alex** [comment]
> if emoji=False there's still a \u2192 ( → ) print on most lines. that should be gone.
Are you on Window? :cry:  Or just you don't want the arrow?

**Comment by Tkd-Alex** [comment]
> - [ ] if emoji=False there's still a \u2192 ( → ) print on most lines. that should be gone.

> - [x] the entire line print of "claiming the bonus for..." is redundant and unnecessary. we already see the +50 claim line. 

**Removed**

> - [x] the " Streamer: " is also redundant as well, as they're all streamers.

**Removed**

> - [x] prediction lines should mention streamer's name, or at least on the first line "Start betting for.."

Edit for complete and start bet event
- **Start betting for {event} owned by {event.streamer}**
- **Going to complete bet for {event} owned by {event.streamer}**

> - [x] I think total channel_points is important to add. it doesn't take much space.

**Edited with: {streamer-name} (xxxx points)**

**Comment by testdev123456** [comment]
yes, unfortunately i'm on windows! and don't see the emojis.  I would have liked to have them.. ;o(

**Comment by Tkd-Alex** [comment]
> (btw... i'm experiencing errors on raids since last night.. maybe it's just me.. I'll wait a little.. ) 

Should be fixed in the latest related commit, this bug It's present only in the Watch Streak branch
