### ISSUE TITLE
Make it Heroku friendly

### ISSUE THREAD

**Issue by hokagay7** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#130]
I've been trying to run it on Heroku and its quite hard. Every time I restart dynos, it will create new session thus needing to enter 2fa key. Without console, it really hard.
![image](https://user-images.githubusercontent.com/68209911/113466732-9a3eff80-9470-11eb-90df-632151f1d792.png)

If i remove 2fa this happen:
![image](https://user-images.githubusercontent.com/68209911/113466822-3a952400-9471-11eb-8e0b-5efadb14988d.png)

**Comment by RakSrinaNa** [comment]
Well if jerky doesn't allow you to provide inputs (doesn't seem like it in the screens) then your only way will probably be to upload your cookies file manually along with the sources.
It then shouldn't ask you for any auth and just start directly.

**Comment by leognutzmann** [comment]
Can you show me how did you uploaded it to heroku? 
I did like I always do but keep falling into this error
Traceback (most recent call last):
  File "/app/run.py", line 11, in <module>
      twitch_miner = TwitchChannelPointsMiner(
  TypeError: 'module' object is not callable`

**Comment by Jeysef** [comment]
I first run it in pc so i have the cookie folder, then I make procfile where I write "worker: python run.py" ,then I upload everything to github and then conect to heroku and deploy. if you cannot upload it to github try rename or delete some info in setup.py/ setuptools. I did it acording this video maybye this will help you: https://www.youtube.com/watch?v=iLvMYXKIcPo

**Comment by Jeysef** [comment]
If it will still want tke twich login key then you probably have to write it straight into code.
my heroku is working:
![obrazek](https://user-images.githubusercontent.com/77840731/116506587-de7dbe00-a8bd-11eb-83d0-fbf68ebc3468.png)

**Comment by hokagay7** [comment]
> Can you show me how did you uploaded it to heroku?
> I did like I always do but keep falling into this error
> Traceback (most recent call last):
> File "/app/run.py", line 11, in
> twitch_miner = TwitchChannelPointsMiner(
> TypeError: 'module' object is not callable`

That seems like the same error i got when using the og TCPM. That's the reason why I switch to TCPMv2. I think twitch update something which broke the script :p
So far I didn't found any fix.

**Comment by josephisticated** [comment]
https://youtu.be/QUvxrzINj5Q
this would be nice

**Comment by leognutzmann** [comment]
I found a fix to my problem and managed to upload to heroku.
Change line 5 from this 
`from TwitchChannelPointsMiner import TwitchChannelPointsMiner` 
to this 
`from TwitchChannelPointsMiner.TwitchChannelPointsMiner import TwitchChannelPointsMiner`
Huge thanks to @erickventura for that

Then use the following code in your procfile:
`worker: python run.py -p $PORT`

If you fall into authentication problem like @hokagay7 did, you can use it locally then push your entire cookies folder into heroku after you login.

**Comment by hokagay7** [comment]
I managed to run it on heroku thanks to everyone.

All i did:
1.Run it on local (to get the cookies file)
2.Retrieve the cookies folder and upload it on github
3.Then setup everything on heroku normally.

TQ!
If anyone need help, you can just create new issue or [email me](mailto:safianad@outlook.com) or something

**Comment by Diogovski** [comment]
@hokagay7 can you help me?

**Comment by Diogovski** [comment]
mine only says 2021-06-28T19:41:06.000000+00:00 app[api]: Build succeeded

**Comment by Diogovski** [comment]
i get this sometimes at=error code=H14 desc="No web processes running" method=GET path="/"

**Comment by hokagay7** [comment]
Is that the only output from the log? Try restart it and read the logs

> i get this sometimes at=error code=H14 desc="No web processes running" method=GET path="/"

That is common, i always get that it doesn't affect anything.

**Comment by Diogovski** [comment]
yes its the only output

**Comment by Diogovski** [comment]
i think he is not running the procfile

**Comment by Diogovski** [comment]
idk how but i was able to make it work on replit, which is strange since i tried a lot of times and always failed. problem is if i close the replit, replit stops debbuging

**Comment by hokagay7** [comment]
> i think he is not running the procfile

Try checking at the resources tab if the worker is on. My other app were switch off by default.

**Comment by Diogovski** [comment]
![Screenshot_2021-06-29-15-58-19-811_com.android.chrome.jpg](https://user-images.githubusercontent.com/81532541/123821147-0fe12d00-d8f3-11eb-9520-90e866d69dd9.jpg)

Here?

**Comment by hokagay7** [comment]
have you create the Procfile? It should be like this "worker: python run.py"(remove " obviously)

**Comment by Diogovski** [comment]
Yes
![Screenshot_2021-06-29-16-26-07-483_com.android.chrome.jpg](https://user-images.githubusercontent.com/81532541/123825688-08238780-d8f7-11eb-997a-70912c52fb8e.jpg)
![Screenshot_2021-06-29-16-26-47-719_com.android.chrome.jpg](https://user-images.githubusercontent.com/81532541/123825789-1b365780-d8f7-11eb-8fd1-d1857bc068a6.jpg)

**Comment by hokagay7** [comment]
ahh thats the problem. Procfile has no extension. It should be "Procfile" without .txt

**Comment by Diogovski** [comment]
Still doesn't work

**Comment by Diogovski** [comment]
"The Procfile must live in your app’s root directory. It does not function if placed anywhere else."


I have min next to run.py it's on root right?

**Comment by hokagay7** [comment]
That's weird. Is there any way for me to contact you? Perhaps on steam or something?

**Comment by Diogovski** [comment]
I have Discord

**Comment by hokagay7** [comment]
> I have Discord

adyn#7813

**Comment by Diogovski** [comment]
Maybe i have a file or my folder contains wrong files idk

**Comment by hokagay7** [comment]
> Maybe i have a file or my folder contains wrong files idk
it should look like this.
![image](https://user-images.githubusercontent.com/68209911/123833728-3924ac00-d939-11eb-82b9-5a928d55cceb.png)

what is your discord id tho..

**Comment by Diogovski** [comment]
i dont have the package json file, is it important?

**Comment by Diogovski** [comment]
Diogovski#5791

**Comment by Diogovski** [comment]
it´s working now, idk what worked but i didnt had a space between worker: and python i had worker:python i changed it to worker: python, and it didnt workedthen i restartet all dynos and it recognized the Procfile, then i just switch it on , thx for the help!!!!!!!!!!!!!

**Comment by JhnV21** [comment]
can someone help me to setup it ? i already tried everything on this post, my discord: JhnV#8257
