### ISSUE TITLE
Hi, can I run the program with a proxy?

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#134]
I have many copies of your program running at the same time with different accounts, is it possible to somehow configure it so that everyone works through different proxies?

**Comment by Tkd-Alex** [comment]
I don't know why you have closed this issue.
Anyway, no. 
For the moment proxy It's not supported but obv If you are a programmer you can easily achieve your goal 😉
