### ISSUE TITLE
When I try to start I claim drops then it freezes

### ISSUE THREAD

**Issue by alexjshepler** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#136]
Hi, so when I try to start it I get ![this](https://user-images.githubusercontent.com/19987488/114103837-a961eb00-987e-11eb-8133-9c583a772602.png) and it seems to be claiming it mutliple times (I don't have the ability to check rn) , but I had to run it like 5-10 times before I got the program to start

**Comment by alexjshepler** [comment]
This is my run.py also 
`# -*- coding: utf-8 -*-

import logging
from colorama import Fore
from TwitchChannelPointsMiner import TwitchChannelPointsMiner
from TwitchChannelPointsMiner.logger import LoggerSettings, ColorPalette
from TwitchChannelPointsMiner.classes.Settings import Priority
from TwitchChannelPointsMiner.classes.entities.Bet import Strategy, BetSettings, Condition, OutcomeKeys, FilterCondition
from TwitchChannelPointsMiner.classes.entities.Streamer import Streamer, StreamerSettings

twitch_miner = TwitchChannelPointsMiner(
    username="Geekwired",
    password="",           # If no password will be provided, the script will ask interactively
    claim_drops_startup=True,                  # If you want to auto claim all drops from Twitch inventory on the startup
    priority=[                                  # Custom priority in this case for example:
        Priority.STREAK,                        # - We want first of all to catch all watch streak from all streamers
        Priority.DROPS,                         # - When we don't have anymore watch streak to catch, wait until all drops are collected over the streamers
        Priority.ORDER                          # - When we have all of the  drops claimed and no watch-streak available, use the order priority (POINTS_ASCENDING, POINTS_DESCEDING)
    ],
    logger_settings=LoggerSettings(
        save=True,                              # If you want to save logs in a file (suggested)
        console_level=logging.INFO,             # Level of logs - use logging.DEBUG for more info)
        file_level=logging.DEBUG,               # Level of logs - If you think the log file it's too big, use logging.INFO
        emoji=True,                             # On Windows, we have a problem printing emoji. Set to false if you have a problem
        less=True,                             # If you think that the logs are too verbose, set this to True
        colored=True,                           # If you want to print colored text
        color_palette=ColorPalette(             # You can also create a custom palette color (for the common message).
            STREAMER_online="GREEN",            # Don't worry about lower/upper case. The script will parse all the values.
            streamer_offline="red",             # Read more in README.md
            BET_wiN=Fore.CYAN                   # Color allowed are: [BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE, RESET].
        )
    ),
    streamer_settings=StreamerSettings(
        make_predictions=True,                  # If you want to Bet / Make prediction
        follow_raid=True,                       # Follow raid to obtain more points
        claim_drops=True,                       # We can't filter rewards base on stream. Set to False for skip viewing counter increase and you will never obtain a drop reward from this script. Issue #21
        watch_streak=True,                      # If a streamer go online change the priotiry of streamers array and catch the watch screak. Issue #11
        join_chat=True,                         # Join irc chat to increase watch-time
        bet=BetSettings(
            strategy=Strategy.SMART,            # Choose you strategy!
            percentage=50,                      # Place the x% of your channel points
            percentage_gap=20,                  # Gap difference between outcomesA and outcomesB (for SMART stragegy)
            max_points=5000000,                 # If the x percentage of your channel points is gt bet_max_points set this value
            stealth_mode=True,                  # If the calculated amount of channel points is GT the highest bet, place the highest value minus 1-2 points #33
            filter_condition=FilterCondition(
                by=OutcomeKeys.TOTAL_USERS,    # Where apply the filter. Allowed [PERCENTAGE_USERS, ODDS_PERCENTAGE, ODDS, TOP_POINTS, TOTAL_USERS, TOTAL_POINTS]
                where=Condition.LTE,           # 'by' must be [GT, LT, GTE, LTE] than value
                value=800
            )
        )
    )
)

# You can customize the settings for each streamer. If not settings were provided, the script would use the streamer_settings from TwitchChannelPointsMiner.
# If no streamer_settings are provided in TwitchChannelPointsMiner the script will use default settings.
# The streamers array can be a String -> username or Streamer instance.

# The settings priority are: settings in mine function, settings in TwitchChannelPointsMiner instance, default settings.
# For example, if in the mine function you don't provide any value for 'make_prediction' but you have set it on TwitchChannelPointsMiner instance, the script will take the value from here.
# If you haven't set any value even in the instance the default one will be used

twitch_miner.mine([Streamer("Ailincia")],followers=True)                    # Automatic download the list of your followers (unable to set custom settings for you followers list)

`

**Comment by Tkd-Alex** [comment]
uhm for debug and fix this kind of problems I need the log files with DEBUG level

**Comment by alexjshepler** [comment]
Sorry, here are some of the logs (I am 99% sure that the last one was a successful mine, cause all of the other ones were max of 16kb)

[Geekwired.20210408-152304.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/6288612/Geekwired.20210408-152304.log)
[Geekwired.20210408-152320.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/6288614/Geekwired.20210408-152320.log)
[Geekwired.20210408-152330.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/6288615/Geekwired.20210408-152330.log)
[Geekwired.20210408-152349.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/6288616/Geekwired.20210408-152349.log)
[Geekwired.20210408-152418.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/6288617/Geekwired.20210408-152418.log)
[Geekwired.20210408-152439.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/6288618/Geekwired.20210408-152439.log)
[Geekwired.20210408-152456.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/6288620/Geekwired.20210408-152456.log)

**Comment by Tkd-Alex** [comment]
Can you please test the latest commit? 
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/68e7ca5d3789b7bb9885f9e274c3e29427641943

**Comment by Tkd-Alex** [comment]
@alexjshepler news?
