### ISSUE TITLE
now MODs can participate in predictions

### ISSUE THREAD

**Issue by testdev123456** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#138]
not much of a bug, but a feature update..

now mods can 'bet', so we should revert #15

**Comment by Tkd-Alex** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/214e2e2c-3a98-46f6-9b61-50c57a0d8fca-0c230afe-4f2b-4a6d-a61c-5e97da59f558-v1.png?transparent=1&palette=1&width=246)

**Comment by RakSrinaNa** [comment]
Yeah seem like it is the case.

When starting a prediction:
![image](https://user-images.githubusercontent.com/1688389/114157724-3a3ed200-9924-11eb-9ec1-88011e105df9.png)
"Mods who have voted will not be able to choose the outcome."

When betting:
![image](https://user-images.githubusercontent.com/1688389/114157871-66f2e980-9924-11eb-8ae3-dc1852da41a9.png)

Prediction is accepted as a mod:
![image](https://user-images.githubusercontent.com/1688389/114157943-78d48c80-9924-11eb-9f37-05f74ca5bd41.png)

**Comment by Tkd-Alex** [comment]
One of you want to do the PR? :smile_cat:
