### ISSUE TITLE
Unable to complete the bet. "Cast prediction" button issue.

### ISSUE THREAD

**Issue by Tkd-Alex** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#14]
![image](https://user-images.githubusercontent.com/14061593/105629617-53b3a000-5e44-11eb-9979-bbb5bbe42454.png)

I think the problem is related to this "Cast prediction"
I've never seen before :fearful:

_Originally posted by @Tkd-Alex in https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/6#issuecomment-766334818_

---

We are currently waiting the @Element21 html logs for fix this.

**Comment by Element21** [comment]
[Html for the pages](https://gofile.io/d/01Iaae)

BONUS: No cookies this time!

**Comment by Tkd-Alex** [comment]
@Element21 Bro, the cookie is inside the .7z archive :laughing: 
Keep attention, It's for your safety ... You have recursively zip all the folders

![image](https://user-images.githubusercontent.com/14061593/105747116-a5d9eb80-5f40-11eb-9664-a9e6f57eb5ba.png)

**Comment by Tkd-Alex** [comment]
However, the logs are not enough because no html refers to the "cast prediction" button.

**Comment by Element21** [comment]
HOW

**Comment by Element21** [comment]
I MADE SURE THIS TIME :facepalm:

**Comment by Tkd-Alex** [comment]
We wait your news :)

**Comment by Element21** [comment]
https://gofile.io/d/F9MSKb

**Comment by Tkd-Alex** [comment]
> https://gofile.io/d/F9MSKb

Awesome! If you have also the screenshots will be very helpful!

**Comment by Element21** [comment]
[screenshots](https://gofile.io/d/ymValp)

**Comment by Tkd-Alex** [comment]
Finally, we have HTML code of this strange issue :smile: . I'm working on this.

![image](https://user-images.githubusercontent.com/14061593/105993219-662d1400-60a6-11eb-95cb-56ecd864dfc1.png)

```html
<div class="tw-relative tw-transition-group">
   <div style="transition-property: transform, opacity; transition-timing-function: ease; transition-delay: 0ms; transition-duration: 250ms;" class="tw-transition tw-transition--enter-done tw-transition__slide-over-right tw-transition__slide-over-right--enter-done">
      <div class="tw-align-center tw-align-items-center tw-flex tw-flex-column tw-pd-x-1">
         <img alt="Temporary Chat Badge" class="prediction-terms-step__icon tw-image tw-mg-y-1" src="https://static.twitchcdn.net/assets/predictions_blue-1-bfd06aad609c80001f12.png">
         <div class="tw-mg-b-1">
            <h5 class="tw-semibold">Predict <span style="color: rgb(56, 122, 255);">"yes"</span> with Channel Points?</h5>
         </div>
         <p class="">You will receive a temporary chat badge. You will not be able to change your pick.</p>
         <div class="tw-mg-t-1">
            <p class="">By clicking "Cast Prediction" below, you agree to the <a class="tw-link" rel="noopener noreferrer" target="_blank" href="https://www.twitch.tv/p/legal/predictions-terms-and-conditions/">Predictions Terms &amp; Conditions</a>.</p>
         </div>
         <div class="tw-flex tw-mg-t-2">
            <div class="tw-mg-r-1">
               <button data-test-selector="prediction-terms-step__cancel-button" class="tw-align-items-center tw-align-middle tw-border-bottom-left-radius-medium tw-border-bottom-right-radius-medium tw-border-top-left-radius-medium tw-border-top-right-radius-medium tw-core-button tw-core-button--secondary tw-inline-flex tw-justify-content-center tw-overflow-hidden tw-relative">
                  <div class="tw-align-items-center tw-core-button-label tw-flex tw-flex-grow-0">
                     <div data-a-target="tw-core-button-label-text" class="tw-flex-grow-0">Go Back</div>
                  </div>
               </button>
            </div>
            <button data-test-selector="prediction-terms-step__accept-button" class="tw-align-items-center tw-align-middle tw-border-bottom-left-radius-medium tw-border-bottom-right-radius-medium tw-border-top-left-radius-medium tw-border-top-right-radius-medium tw-core-button tw-core-button--primary tw-inline-flex tw-justify-content-center tw-overflow-hidden tw-relative">
               <div class="tw-align-items-center tw-core-button-label tw-flex tw-flex-grow-0">
                  <div data-a-target="tw-core-button-label-text" class="tw-flex-grow-0">Cast Prediction</div>
               </div>
            </button>
         </div>
      </div>
   </div>
</div>
```

**Comment by Tkd-Alex** [comment]
@Element21 are you able to test https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/cast-prediction-button for us?

**Comment by Element21** [comment]
sure!

**Comment by Element21** [comment]
oof

**Comment by Element21** [comment]
```
27/01 22:06:54 - 🔧  Going to complete bet for EventPrediction: Does he die in FS again owned by mizkif (136 points)
27/01 22:06:55 - 🔧  Decision: no (PINK), Points: 3M, Users: 291 (68.96%), Odds: 1.25 (80.0%)
27/01 22:06:55 - 🔧  Going to write: 102 channel points on input B
27/01 22:06:56 - 🔧  Going to place the bet for EventPrediction: Does he die in FS again
27/01 22:07:07 - Exception raised with: (//div[@id='channel-points-reward-center-body']//div[contains(@class,'custom-prediction-button')]//button)[2]
Traceback (most recent call last):
  File "/home/aiden/cast-predictions-fix/TwitchChannelPointsMiner/classes/TwitchBrowser.py", line 306, in __click_when_exist
    element = WebDriverWait(self.browser, timeout).until(
  File "/home/aiden/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

27/01 22:07:07 - Failed to execute: document.getElementById("channel-points-reward-center-body").getElementsByTagName("button")[1].click();
```

**Comment by Element21** [comment]
seems like we're clicking the element even if it doesn't exist! Can you just add another check to make sure the element exists?

**Comment by Element21** [comment]
or we're not clicking the right button? Shouldn't we just click ```prediction-terms-step__accept-button```?

**Comment by Tkd-Alex** [comment]
Nope, I think It's just an isolated case...
Your error referee to 'Vote' button, after click on this we should click on the prediction terms button
1. `self.__click_on_vote(event, selector_index)`
2. `self.__accept_bet_terms(event, timeout=1.5)`

Have you the screen `event_id___send_text.timestamp.png` to share with us?
I'm currently testing the same branch, and It's working without any crashes after 12h+. I've also placed a lot of prediction this night without any error. So the branch It's fully working up to the method `__click_on_vote` after that I don't know if the fix for the `prediction-terms-step__accept-button` is working because I've not this button. You are the only one :confused:

**Comment by RakSrinaNa** [comment]
> You are the only one

I saw that button once. Though when I clicked it to "Accept the terms" it never appeared again.

I think this may be shown to accounts that were created before predictions were here and that now have to accept the conditions. Newer accounts probably already accept it upon inscription.

**Comment by Tkd-Alex** [comment]
@Element21 you have never accepted that terms? :rofl:

**Comment by Element21** [comment]
I have, but only on the twitch app, I might need to do it in the browser that the bot uses to save a cookie or something. The accept conditions only appears if you bet over x number of chanel points it seems because I'm not getting the error sometimes. Hmmm

**Comment by Tkd-Alex** [comment]
Please continue the test ...
I hope you should receive at least one time the message:
`Agree to Predictions Terms & Conditions`
After:
`Going to place the bet for {event}`

**Comment by Tkd-Alex** [comment]
It's possible is related to each streamer? and not based on points betted

**Comment by Element21** [comment]
Well, it keeps happening with the streamer [mizkif](https://twitch.tv/mizkif) (to my knowledge), so that is more than likely the case.

**Comment by Tkd-Alex** [comment]
@Element21 we have any update on this?

**Comment by Element21** [comment]
Well, it seems to work fine on every other streamer than mizkif, but I have to wait for him to go live to test it

**Comment by Element21** [comment]
> Please continue the test ...
> I hope you should receive at least one time the message:
> `Agree to Predictions Terms & Conditions`
> After:
> `Going to place the bet for {event}`

I've never seen `Agree to Predictions Terms & Conditions`

**Comment by Tkd-Alex** [comment]
Are you testing the right branch, right?
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/cast-prediction-button

**Comment by Element21** [comment]
:sweat_smile: Definitely not using master...
