### ISSUE TITLE
AUTH

### ISSUE THREAD

**Issue by ezbooz** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#140]
Can I authorize many accounts through tokens and massively get points?

**Comment by ezbooz** [comment]
Or add more LOG:PASS

**Comment by RakSrinaNa** [comment]
Read step 3 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use

You can provide user and password.

**Comment by ezbooz** [comment]
> Read step 3 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use
> 
> You can provide user and password.

Maybe I don't see something, but I can only add 1 account. Should I run a separate file with a new account?

**Comment by ezbooz** [comment]
I have a list of accounts (~ 1k), I want all accounts to earn points at once

**Comment by RakSrinaNa** [comment]
Then you need to run the script 1k times with each account setup.

Though let's be honest, farming with 1k account on the same IP... Twitch might flag you.

#69

**Comment by ezbooz** [comment]
I got it, thanks for the answer. you can close
