### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LoreWasTaken** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#141]
So i was wondering if is it possible somehow to not, everytime i start the script, ask for my 2FA, or if there isn't yet and is possible an option to automatically login to twitch so if next time i start the script don't need to put my 2FA again, it doesn't really bothers me but would be nice to have :)

**Comment by Tkd-Alex** [comment]
When you log in for the first time the script will create a cookie session file.
You don't need to log in every time and verify with 2FA.

**Comment by LoreWasTaken** [comment]
Yea i didn't saw, sorry for wasting your time.
