### ISSUE TITLE
final report 

### ISSUE THREAD

**Issue by papiLUL** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#148]
how do I get the final report?

**Comment by Tkd-Alex** [comment]
Close the script with CTRL+C

**Comment by papiLUL** [comment]
Im using pycharm to run it. Does it also work?

**Comment by papiLUL** [comment]
oh it does, but I get this error message after that
https://user-images.githubusercontent.com/78660438/114545752-a0955e80-9c5c-11eb-967f-9f92e2838719.png

**Comment by papiLUL** [comment]
wait it works now, anyway thanks for the help
