### ISSUE TITLE
Problem with bets

### ISSUE THREAD

**Issue by IvIedweD** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#149]
Hello, I have 3 accounts in the stream. The fact is that all 3 accounts write to the log that they are placing bets. But in reality, 2 accounts are betting, and 3 are not betting. What could be the problem?

**Comment by RakSrinaNa** [comment]
2 betting and 3 not betting? So there's actually 5 in total?

Maybe the stream got bet on had its prediction closed before you were able to get on? This should be written in the logs though.

**Comment by IvIedweD** [comment]
There are 3 twitch accounts in total. All 3 accounts are written to the log. But 2 bets, and 1 does not.
