### ISSUE TITLE
prediction errors if viewer is a channel 'mod'

### ISSUE THREAD

**Issue by testdev123456** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#15]
basically, predictions aren't enabled for channel moderators. so the script currently tries to cast prediction anyways and breaks in errors.
there should be a simple way to check if we're a 'mod' on that channel  and avoid predictions. 

;o)

**Comment by Tkd-Alex** [comment]
You think It's related to #14 ? Or are two different things?

**Comment by testdev123456** [comment]
nope.. that user list is of real stream viewers. the bot doesn't get us in that list as far as I know.  Also, that list is not real-time, often delayed for like 5 minutes.   I'm gonna be looking what can we 'grab' as a mod indicator

**Comment by testdev123456** [comment]
Ok, mods have that icon to 'go to mod view' 
![mod](https://user-images.githubusercontent.com/76866156/105753379-5f2bc780-5f27-11eb-84ef-5abe00965540.png)

and that code is:

`<a aria-label="Go to Mod View" data-test-selector="mod-view-link" aria-describedby="5a95e78e80662483bc67f09a85ee77eb" class="tw-align-items-center tw-align-middle tw-border-bottom-left-radius-medium tw-border-bottom-right-radius-medium tw-border-top-left-radius-medium tw-border-top-right-radius-medium tw-button-icon tw-core-button tw-inline-flex tw-justify-content-center tw-overflow-hidden tw-relative" href="/moderator/channelName"><span class="tw-button-icon__icon"><div style="width: 2rem; height: 2rem;"><div class="ScIconLayout-sc-1bgeryd-0 kbOjdP tw-icon"><div class="ScAspectRatio-sc-1sw3lwy-1 dNNaBC tw-aspect"><div class="ScAspectSpacer-sc-1sw3lwy-0 gkBhyN"></div><svg width="100%" height="100%" version="1.1" viewBox="0 0 20 20" x="0px" y="0px" class="ScIconSVG-sc-1bgeryd-1 cMQeyU"><g><path fill-rule="evenodd" clip-rule="evenodd" d="M7.812 12.397L16 6.022V4h-2.022l-6.375 8.188.209.21zm-2.27.56l-2.249-2.25 1.414-1.414 1.47 1.47L13 2h5v5l-8.763 6.822 1.47 1.471-1.414 1.414-2.25-2.25L3.5 18 2 16.5l3.543-3.543z"></path></g></svg></div></div></div></span></a>`

that doesn't appear in non-mod html.

also, there's a 'harsh' way to check 'live' if you're MOD by requesting the url : https://www.twitch.tv/moderator/channelName

**Comment by Tkd-Alex** [comment]
> So, is it as easy to search all html code for text: "Go to Mod View" , if positive.. > skip prediction ?

Yes this is a really and very fast trick, but for non-English user maybe can be a problem.
In Italian is: `aria-label="Vai a visual. per i moderatori"`

I think I'll try to use the url: https://www.twitch.tv/moderator/channelName

**Comment by testdev123456** [comment]
you're right...  but you can still use :  data-test-selector="mod-view-link"
 that is internal html...

**Comment by Tkd-Alex** [comment]
Can you check If also in pop-up mode is present the icon to 'go to mod view'

**Comment by testdev123456** [comment]
> Can you check If also in pop-up mode is present the icon to 'go to mod view'

NO !

I;ll keep checking what to use

**Comment by testdev123456** [comment]
ok, found in popout mode this difference as mod :

![popout mod](https://user-images.githubusercontent.com/76866156/105756899-fd219100-5f2b-11eb-8e35-459a75719184.png)

the "switch to non mod settings " code:

`<button data-test-selector="moderation-mode-toggle-selector" class="tw-link tw-link--button tw-link--hover-underline-none"><div class="tw-flex tw-full-width"><button data-a-target="switch-chat-settings-mode" class="tw-align-items-center tw-align-middle tw-border-bottom-left-radius-medium tw-border-bottom-right-radius-medium tw-border-top-left-radius-medium tw-border-top-right-radius-medium tw-core-button tw-core-button--text tw-full-width tw-inline-flex tw-justify-content-center tw-overflow-hidden tw-relative"><div class="tw-align-items-center tw-core-button-label tw-core-button-label--icon tw-flex tw-flex-grow-0"><div class="tw-align-items-center tw-flex tw-mg-r-05"><div class="tw-align-items-center tw-core-button-icon tw-inline-flex"><div class="ScIconLayout-sc-1bgeryd-0 kbOjdP tw-icon" data-a-selector="tw-core-button-icon"><div class="ScAspectRatio-sc-1sw3lwy-1 dNNaBC tw-aspect"><div class="ScAspectSpacer-sc-1sw3lwy-0 gkBhyN"></div><svg width="100%" height="100%" version="1.1" viewBox="0 0 20 20" x="0px" y="0px" class="ScIconSVG-sc-1bgeryd-1 cMQeyU"><g><path fill-rule="evenodd" d="M7 2a4 4 0 00-1.015 7.87c-.098.64-.651 1.13-1.318 1.13A2.667 2.667 0 002 13.667V18h2v-4.333c0-.368.298-.667.667-.667.908 0 1.732-.363 2.333-.953.601.59 1.425.953 2.333.953.369 0 .667.299.667.667V18h2v-4.333A2.667 2.667 0 009.333 11c-.667 0-1.22-.49-1.318-1.13A4.002 4.002 0 007 2zM5 6a2 2 0 104 0 2 2 0 00-4 0z" clip-rule="evenodd"></path><path d="M15 7l3 3-3 3v-2h-3V9h3V7z"></path></g></svg></div></div></div></div><div data-a-target="tw-core-button-label-text" class="tw-flex-grow-0">Switch to Non-Mod Settings</div></div></button></div></button>`


**so I think we can look for :    data-test-selector="moderation-mode-toggle-selector"**

**Comment by Tkd-Alex** [comment]
I want to reduce the use of Selenium to mainly actions.
Can you check this CURL request?

```
curl 'https://gql.twitch.tv/gql' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Authorization: OAuth <write-your-token-here>' \
  -H 'DNT: 1' \
  -H 'Accept-Language: it-IT' \
  -H 'Client-Id: kimne78kx3ncx6brgo4mv6wki5h1ko' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36' \
  -H 'X-Device-Id: 0433ffc66c638dde' \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  -H 'Accept: */*' \
  -H 'Origin: https://www.twitch.tv' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://www.twitch.tv/moderator/<streamer-username>' \
  --data-raw '{"operationName":"ModViewChannelQuery","variables":{"channelLogin":"<streamer-username>"},"extensions":{"persistedQuery":{"version":1,"sha256Hash":"df5d55b6401389afb12d3017c9b2cf1237164220c8ef4ed754eae8188068a807"}}}' \
  --compressed
```

If you don't know how to take the token you can find on Chrome-Developer tools

![image](https://user-images.githubusercontent.com/14061593/105768136-3b36a900-5f5c-11eb-8e8a-f1c037eb1e42.png)

The answer seems to be pretty interesting

![image](https://user-images.githubusercontent.com/14061593/105768323-881a7f80-5f5c-11eb-8ffd-881bd06ce482.png)

**Comment by testdev123456** [comment]
that's perfect !


`"data":{
   "user":{
      "id":"489772100",
      "login":"streamer-username",
      "displayName":"streamer-username",
      "profileImageURL":"https://static-cdn.jtvnw.net/jtv_user_pictures/6ba5c458-c7c6-4410-a6e5-de4y4y34f1-profile_image-70x70.png",
      "self":{
         "isModerator":true,
         "__typename":"UserSelfConnection"
      },
      "__typename":"User"
   },
   "currentUser":{
      "id":"497804614",
      "__typename":"User"
   }
},
"extensions":{
   "durationMilliseconds":23,
   "operationName":"ModViewChannelQuery",
   "requestID":"01EWXQVFH2844J4G1YE0GHFCD5"
}
}`

**Comment by Tkd-Alex** [comment]
@testdev123456 please check the last commit https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/6c6f1579d6ae2eb163d2e916ee405f57bf59edd2

**Comment by testdev123456** [comment]
> @testdev123456 please check the last commit [6c6f157](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/6c6f1579d6ae2eb163d2e916ee405f57bf59edd2)

I am..  the 'pull' was done great, but still waiting for some live channel that I mod to test predictions!

**Comment by testdev123456** [comment]
Sorry, you are moderator of xx (xx points) and you can't start the bet

perfect....

(btw.. when I was closing the script.. after doing CTRL+C  I got errors.  Wasn't getting them yesterday before the pull.. so  if happens again I'll report back !)

**Comment by testdev123456** [comment]
@Tkd-Alex
