### ISSUE TITLE
Autocrash when double clicked and error when ran in console.

### ISSUE THREAD

**Issue by dklmapperpl** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#151]
So it has been working for a while when I was using 3.7 python and then I installed 3.9 python and it sopped working. When I double click the file it just blinks and closes and when I run it from console it tells me this:
C:\Users\David>python "C:\Users\david\desktop\Twitch-Channel-Points-Miner-v2\run.py"
Traceback (most recent call last):
  File "C:\Users\david\desktop\Twitch-Channel-Points-Miner-v2\run.py", line 4, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'.

Can you please help?

**Comment by RakSrinaNa** [comment]
Everything should be in the readme. Especially sections "How to use" and "windows".

**Comment by Tkd-Alex** [comment]
Solved?
