### ISSUE TITLE
Can anyone make me a tutorial: How to install Twitch-Channel-Points-Miner on a Raspberrypi Pi (3b+)

### ISSUE THREAD

**Issue by sudojamoin** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#152]
I don´t understand how to install this on a Raspberry Pi. Please Help me! And write down a tutorial! ThankYou! PLEASE!!

**Comment by dmunozv04** [comment]
You should just follow the steps on the [how to use section of the readme](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use). I can confirm it works perfectly with a pi 3b+ and even older pi models. 

Just make sure to have pip installed `sudo apt install python3-pip`

Let me know if you have any issues

**Comment by Tkd-Alex** [comment]
Search also in the past issue (also closed) 😄 
Close the issue when you have solved
