### ISSUE TITLE
How to mine for all following channels but with the make_predictions=false

### ISSUE THREAD

**Issue by feytus** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#155]
I tried doing this : `twitch_miner.mine(followers=True, make_predictions=False)` but it doesn't work...
I'm looking for a way to do this need help please

**Comment by RakSrinaNa** [comment]
I'd do something like this. Like it's written in the readme (https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use point 3):

````py
twitch_miner = TwitchChannelPointsMiner(
    ...
    streamer_settings=StreamerSettings(
        make_predictions=True
        ...
    )
)
twitch_miner.mine(followers=True)
````

Of course the `...` are to be replaced by the rest of the config, here I just "highlighted" what is to change for the question.
