### ISSUE TITLE
Reconnecting to Twitch PubSub server in ~60 seconds

### ISSUE THREAD

**Issue by m0ood** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#156]
Hello. I got an error:
22/04/21 11:19:53 - ERROR - [on_error]: #0 - WebSocket error: [WinError 10060] An attempt to establish a connection was unsuccessful because the desired response was not received from another computer within the required time, or an already established connection was terminated due to an incorrect response from an already connected computer
22/04/21 11:19:54 - INFO - [on_close]: #0 - WebSocket closed
22/04/21 11:19:54 - INFO - [handle_reconnection]: #0 - Reconnecting to Twitch PubSub server in ~60 seconds
What can be wrong?

**Comment by anger** [comment]
I have this same issue.

**Comment by Yishaqel** [comment]
It's been happening to me for a long time, I haven't notified because I thought maybe it was related to my Internet on the laptop or maybe Twitch wasn't working properly

**Comment by VitaliShilov** [comment]
same

**Comment by Emmes420** [comment]
Does anyone know if he's going to fix it or still active on this project?

**Comment by RakSrinaNa** [comment]
Crearly it's network related. To me it looks more like it's related to the connection you have or twitch status.

It happened to me only once in months. It lasted less than 24h and it was when twitch had some issues.
Not sure that much can be done about it.

Maybe if you farm a lot of channels you could try to reduce the amount of them to avoid opening several connections, this could help a bit.

**Comment by anger** [comment]
> 
> 
> Crearly it's network related. To me it looks more like it's related to the connection you have or twitch status.
> 
> It happened to me only once in months. It lasted less than 24h and it was when twitch had some issues.
> Not sure that much can be done about it.
> 
> Maybe if you farm a lot of channels you could try to reduce the amount of them to avoid opening several connections, this could help a bit.

How many channels do you have running? I have three and it still has the problem.

**Comment by RakSrinaNa** [comment]
I have ~50-60 without any problems.

**Comment by Tkd-Alex** [comment]
Your problem how much It's frequently?

**Comment by anger** [comment]
> 
> 
> Your problem how much It's frequently?

For me it's ALL the time, here's a screenshot. 
https://i.imgur.com/m3tFm8T.png

**Comment by RakSrinaNa** [comment]
This isn't the same as the original post though. This is more like #159.

**Comment by Emmes420** [comment]
> Your problem how much It's frequently?



> Your problem how much It's frequently?

Every time I open it
