### ISSUE TITLE
Analytics bug

### ISSUE THREAD

**Issue by rindes** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#157]
#10

**Analytics enabled**
![error_censored](https://user-images.githubusercontent.com/36708183/115948303-b6611a00-a4cd-11eb-8335-24c59dc9339d.jpg)

**Analytics disabled**
![error2_censored](https://user-images.githubusercontent.com/36708183/115948379-561ea800-a4ce-11eb-8eb3-c04f9cd74ce0.jpg)

**Comment by Tkd-Alex** [comment]
uhm with _Analytics enabled_ the logs are duplicated?

**Comment by rindes** [comment]
> uhm with _Analytics enabled_ the logs are duplicated?

Yes, correct.

**Comment by Tkd-Alex** [comment]
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/175#issuecomment-835882186
