### ISSUE TITLE
Temporary fix for SLL verification problem. Credit: @RakSrinaNa

### ISSUE THREAD

**Issue by anger** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#160]
You can disable SSL verification like this:
```patch
Index: TwitchChannelPointsMiner/classes/WebSocketsPool.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/TwitchChannelPointsMiner/classes/WebSocketsPool.py b/TwitchChannelPointsMiner/classes/WebSocketsPool.py
--- a/TwitchChannelPointsMiner/classes/WebSocketsPool.py	(revision 4d6d0f0afb8e2e986e6bf39b45e5cc9ef314d295)
+++ b/TwitchChannelPointsMiner/classes/WebSocketsPool.py	(date 1619385799247)
@@ -2,6 +2,7 @@
 import logging
 import random
 import time
+import ssl
 from threading import Thread, Timer
 
 from dateutil import parser
@@ -67,7 +68,7 @@
         )
 
     def __start(self, index):
-        thread_ws = Thread(target=lambda: self.ws[index].run_forever())
+        thread_ws = Thread(target=lambda: self.ws[index].run_forever(sslopt={"cert_reqs": ssl.CERT_NONE}))
         thread_ws.daemon = True
         thread_ws.name = f"WebSocket #{self.ws[index].index}"
         thread_ws.start()
```

Though I wouldn't really recommend it. Would be better to find how to clear out the websocket's cache of certificates.

_Originally posted by @RakSrinaNa in https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/159#issuecomment-826392509_

**Comment by Tkd-Alex** [comment]
Disable SSL verification It's always a bad thing 😞

**Comment by anger** [comment]
> 
> 
> Disable SSL verification It's always a bad thing 😞

Why's that? I'm not very knowledgeable in this area.

**Comment by RakSrinaNa** [comment]
I'm not really for implementing that fix either. You do it at your own risks.

I guess you're on Windows. Maybe a better solution would be to actually import the new twitch certificate into windows "keychain".

**Comment by RakSrinaNa** [comment]
> > 
> 
> > 
> 
> > Disable SSL verification It's always a bad thing 😞
> 
> 
> 
> Why's that? I'm not very knowledgeable in this area. 

To make it short disabling SSL makes it so that you're not sure anymore that you're really talking to twitch. It could very well be someone acting as twitch but not really them.
