### ISSUE TITLE
How to make colors in console work?

### ISSUE THREAD

**Issue by LukysGaming** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#162]
I cant make the colors in console works, could i get some help?

[https://pastebin.com/935Qw1mH](my cfg)
Could I get some help? I guess i am dumb

**Comment by RakSrinaNa** [comment]
You need a terminal that supports coloring. Si depending on how you start it you may have different results.

**Comment by LukysGaming** [comment]
What terminal would be functional? rn i have "git bash" or whats that

**Comment by RakSrinaNa** [comment]
To me git bash will or won't support coloring depending on how you installed it. (If you wanna know more about this, you can look it up online)

As a personal choice I'd use [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701) with [Powershell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1).

Though Command Prompt should also work fine I suppose, it's just older.

**Comment by Tkd-Alex** [comment]
Read here: https://stackoverflow.com/questions/48749738/how-do-i-get-colorized-output-on-my-windows-git-bash-terminal :)
