### ISSUE TITLE
Double clicking on the run.py file then it crashes.

### ISSUE THREAD

**Issue by Mattxew** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#163]
Hello! I've tried everything that I've been told to and none of them have worked.

How do you mange to open this file without it crashing?

**Comment by RakSrinaNa** [comment]
Don't run it from a double click and read the errors it'll show you.

Also read the readme, especially sections how to use & windows.

#31

**Comment by Mattxew** [comment]
> Don't run it from a double click and read the errors it'll show you.
> 
> Also read the readme, especially sections how to use & windows (I'm guessing you're on it).
> 
> [gottagofaster236/Twitch-Channel-Points-Miner#31](https://github.com/gottagofaster236/Twitch-Channel-Points-Miner/issues/31)

thank you! It is now working. :)
