### ISSUE TITLE
multiple accounts

### ISSUE THREAD

**Issue by josephisticated** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#164]
**Is your feature request related to a problem? Please describe.**
using multiple accounts

**Describe the solution you'd like**
it'd be nice to be able to add more than one account

**Describe alternatives you've considered**
:P

**Additional context**

**Comment by RakSrinaNa** [comment]
Duplicate of #69

**Comment by kelukelol** [comment]
![image](https://user-images.githubusercontent.com/76735490/116399371-87caa280-a831-11eb-849b-6cad5da0181d.png)
You did not even read the file that everyone should read before creating an issue/pull request, it is on the first lines of the files so you could see it faster than the other text in the file, that's just sad :/
Duplicate of #69 _nice_

**Comment by josephisticated** [comment]
sorry :(

**Comment by kelukelol** [comment]
> sorry :(

It's ok! We are humans and we all make mistakes, but next time, please read the project readme.md file.
