### ISSUE TITLE
Mine points for channels you are subscribed to only by grabbing through API?

### ISSUE THREAD

**Issue by KillaBoi** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#166]
**Is your feature request related to a problem? Please describe.**
I'd like to mine points for the channels that I am subscribed to only

**Describe the solution you'd like**
Get an API endpoint or something where you can see all the channels you are currently subscribed to and mine channel points for those only.

**Describe alternatives you've considered**
Manually adding all the streamers I'm subbed to but that would be tedious and take an extremely long time.

**Comment by dmunozv04** [comment]
Sorry, you mean channels that you have a paying subscription or that you simply follow? Because if it’s the latter, it’s already implemented

**Comment by KillaBoi** [comment]
I mean channels that I have a paying subscription for.

**Comment by Tkd-Alex** [comment]
Interesting :thinking: 
On Twitch exist a page that list all subscription?

**Comment by KillaBoi** [comment]
Yes, https://www.twitch.tv/subscriptions has your active subscriptions and https://www.twitch.tv/subscriptions?tab=expired shows the subscriptions that you had which are now expired.

**Comment by dmunozv04** [comment]
It may be able to check for each one of the people that you are following if you are also subscribed with [this](https://dev.twitch.tv/docs/api/reference#check-user-subscription) , but if someone is subscribed but not following this won’t work.

**Comment by KillaBoi** [comment]
Twitch also has a graphql API that can be access way more easily than having to use OAUTH to check. Also the API you linked is to check whether a certain user AND broadcaster combo match.
