### ISSUE TITLE
Reconnecting to Twitch PubSub server in 30 seconds

### ISSUE THREAD

**Issue by SoosKakasiAdam** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#168]
Im on mac. Its just saying the sentence above. Anyone can help me?
<img width="1440" alt="Screen Shot 2021-05-04 at 21 46 43" src="https://user-images.githubusercontent.com/80282233/117061465-85c97d80-ad22-11eb-93be-378be8664e47.png">

**Comment by Tkd-Alex** [comment]
I think you are currently using the oldest version of this repo.
Plese upgrade
