### ISSUE TITLE
Idea for the betting by the script

### ISSUE THREAD

**Issue by Al0shka228** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#18]
I have an idea. For me auto betting is not cool. Can you make the script which will login in the accoun. And then we can choose the variant RED/BLU to make bet by the letters or numbers. ?
For exemple log of the srcipt))
Succesfully logged in the twich tlalala
Streamer ..... online.
(If we can make a bet write) "You can make the bet"
(If no just wait for the prediction) 

"Choose the amount of coins (all for the all coins and side Red - 1 Blue 2 
user input (for exemple) ALL 2,   300 1

That will be very usefull for me who need to make bets in the multiple accounts. Thanks) 
If will do that can you make that we can login by the twich cookies from the gottagofaster236/Twitch-Channel-Points-Miner.
Thanks for attention)
I am looking forward to hearing from you

**Comment by Tkd-Alex** [comment]
I don't understand how multiple accounts and manually bet are linked

**Comment by Tkd-Alex** [comment]
I've read you issue more times, and I'm a bit confused :confused: 
If you want to make the bet manually why you don't by yourself? 
Or, we should keep the script as is and just notify the bet? Then, wait for manual input? In this case you should have the terminal open and keep attention to it.

In Italy most of the prediction are only 60 seconds you should enough speed to read the data (users, percentage, odds), choose a decision and place the bet. I don't think It's a good idea to insert a manual interaction in this miner/bot.

But if you want and maybe other users think It's a good idea I can do, but please explain better the problem.

About the cookies from  [the original repository](https://github.com/gottagofaster236/Twitch-Channel-Points-Miner) you can read more about here: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#migrating-from-old-repository-the-original-one

If you want to start multiple accounts just create multiple run.py files or use the multithreading. 
```python
# username1.py
from TwitchChannelPointsMiner import TwitchChannelPointsMiner
twitch_miner = TwitchChannelPointsMiner("username1")
twitch_miner.mine(["streamer1", "streamer2"])    
```
```python
# username2.py
from TwitchChannelPointsMiner import TwitchChannelPointsMiner
twitch_miner = TwitchChannelPointsMiner("username2")
twitch_miner.mine(["streamer1", "streamer2"])    
```

**Comment by Tkd-Alex** [comment]
@Al0shka228 do you want to share something with us? :smile_cat:

**Comment by Al0shka228** [comment]
I realized that I needed a separate betting software. And it would not be practical to combine them
So i think that we can close that topic.
