### ISSUE TITLE
WebSocketsPool.on_close() takes 1 positional args, 3 given

### ISSUE THREAD

**Issue by ColinShark** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#180]
When closing with <kbd>Ctrl+C</kbd>, I get this below error

```
^C19/05 18:55:06 - CTRL+C Detected! Please wait just a moment!
19/05 18:55:06 - 💬  Leave IRC Chat: [channel-name]
19/05 18:55:06 - error from callback <function WebSocketsPool.on_close at 0x7fdeec983620>: on_close() takes 1 positional argument but 3 were given
  File "/home/colinsh/twitch-miner/venv/lib64/python3.6/site-packages/websocket/_app.py", line 400, in _callback
    callback(self, *args)


19/05 18:55:18 - 🛑  Ending session: [...]
```

### To Reproduce
Steps to reproduce the behavior. For me this is reproducible and happens every time I quit the program.
1. Install with latest version  
  1.1. `git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2.git`
  1.2. `git checkout 28f61dfec87a5bc7fd49aac3556d51eda681b01d`
2. Start `python run.py`
3. Stop <kbd>Ctrl+C</kbd>

### Expected behavior
I would've expected this not to appear 😝 

### Desktop (please complete the following information):**
* OS: `centos-release-7-9.2009.1.el7.centos.x86_64` via `rpm -q centos-release`
* Python Version: 
```
Python 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

**Comment by skupfer** [comment]
Same here, same commit. Happened without CTRL+C during the current run (first time usage)

```
20/05/21 18:23:00 - ERROR - [on_error]: #0 - WebSocket error: Connection is already closed.
20/05/21 18:23:00 - ERROR - [error]: error from callback <function WebSocketsPool.on_close at 0x7f2a104258b0>: on_close() takes 1 positional argument but 3 were given
  File "/home/kupfer/git/Twitch-Channel-Points-Miner-v2/venv/lib/python3.8/site-packages/websocket/_app.py", line 400, in _callback
    callback(self, *args)
20/05/21 18:31:34 - INFO - [claim_bonus]: 🎁  Claiming the bonus for Streamer(username=****, channel_id=****, channel_points=*k)!
20/05/21 18:31:34 - INFO - [claim_bonus]: 🎁  Claiming the bonus for Streamer(username=****, channel_id=****, channel_points=*k)!
20/05/21 18:34:53 - INFO - [run]: #0 - The last PING was sent more than 10 minutes ago. Reconnecting to the WebSocket...
20/05/21 18:34:53 - INFO - [handle_reconnection]: #0 - Reconnecting to Twitch PubSub server in ~60 seconds
```

**Comment by misterkoko** [comment]
Got the exact same thing. But it still keeps claiming points and joining the chat for you guys, right?

**Comment by RakSrinaNa** [comment]
Seem related to a newer version of a library. If anyone wanna try #189 to see if it's fixed.

**Comment by misterkoko** [comment]
Can confirm that #189 fixes the problem for me.

**Comment by ColinShark** [comment]
Proposed changes from PR 189 forked for me, too.

I had to google how to install and test PR changes, this below worked for me lol
<details><summary>Installation process for PRs</summary>

```sh
$ git fetch origin pull/189/head:pr-189
$ git checkout pr-189
$ python -m pip install -Ur requirements.txt
$ python run.py
```
See https://stackoverflow.com/a/30584951/10045952
</details>
