### ISSUE TITLE
ERROR ClientIRC no reactor

### ISSUE THREAD

**Issue by StasYong** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#182]
After starting run.py (with default setings) in console arrive error: 
"21/05/21 20:21:22 - [start]: Exception raised: 'ClientIRC' object has no attribute 'reactor'. Thread is active: True"

- Linux Mint
- Python 3.6.9
![Python3](https://user-images.githubusercontent.com/84591223/119183235-75ccd000-ba7c-11eb-8e57-ada141d64597.png)

**Comment by Tkd-Alex** [comment]
Maybe It's only because you have the default settings also for streamers list.
Remove all the `streamer-usernamexx` and keep only the streamer that you desire to collect

**Comment by StasYong** [comment]
Problem was on linux mint with installed all versions of python:

ls /usr/bin/python*
/usr/bin/python     /usr/bin/python3     /usr/bin/python3m
/usr/bin/python2    /usr/bin/python3.6   /usr/bin/python3-wsdump
/usr/bin/python2.7  /usr/bin/python3.6m

I think problem was in this many versions or something problems with some files of python. 
I try the same python file on linux mint with only python 3:

ls /usr/bin/python*
/usr/bin/python3  /usr/bin/python3.8  /usr/bin/python3.8-config  /usr/bin/python3-config

and no error has no appear now
