### ISSUE TITLE
Auto chatting bot

### ISSUE THREAD

**Issue by Jeysef** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#188]
It would be interesting if everytime when somebody gift sub to somebody except me, program wil write somthing like: "Never lucky 😢 " or "No sub to me :Sadge " etc.. Because if sombody gift me sub then i will get the points multiplied by 1.2x, 1,4x or 2x depending on sub tier and my t-ch-p wil grow much faster 😃 .

**Comment by RakSrinaNa** [comment]
To me this isn't something that should be part of the bot. It's objective if to farm points for you, not to try to make you earn subs.

**Comment by ss2oo7** [comment]
I would like the software to sometimes write something in the chat, is it possible? ready to pay)

**Comment by NotSafarad** [comment]
Would love to see that. Not for subs but for other reasons.

**Comment by Tkd-Alex** [comment]
It's not related to this project

**Comment by NotSafarad** [comment]
> It's not related to this project

Sadge
