### ISSUE TITLE
Bet function question

### ISSUE THREAD

**Issue by deion** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#19]
Can this be run without the bet function enabled?

**Comment by testdev123456** [comment]
> Can this be run without the bet function enabled?

yes, edit the file  run.py

       make_predictions=False

that's all.
remember to close issue.

**Comment by testdev123456** [comment]
Yes,

removing these lines from run.py  should work : 

```
    bet_settings=BetSettings(
        strategy=Strategy.SMART,        # Choose you strategy!
        percentage=4,                   # Place the x% of your channel points
        percentage_gap=30,              # Gap difference between outcomesA and outcomesB (for SMART stragegy)
        max_points=999,               # If the x percentage of your channel points is gt bet_max_points set this value
    )
```

**Comment by RakSrinaNa** [comment]
I personally would set `make_predictions=False` instead of removing the predictions' settings.

**Comment by Tkd-Alex** [comment]
If you remove the bet_settings the script will assign a default value

The correct option is make_prediction=False suggest by @RakSrinaNa 

Anyways, it's also write in the readme 😁
