### ISSUE TITLE
Doesn't enter streams that go online after the program's started

### ISSUE THREAD

**Issue by chronoquairium** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#192]
Pretty self-explanatory. When I run the program, it works fine for all the online streams, but any streams that are offline when it starts don't get checked again. I don't get why.

**Comment by RakSrinaNa** [comment]
1 - you can only mine 2 people at the same time. So if they come online while others are being mined, depending on your priorities, they won't be mined.

2 - what's your config ?

**Comment by chronoquairium** [comment]
Seems to be inconsistent. Probably just my computer. Sorry.
