### ISSUE TITLE
Error with GQLOperations

### ISSUE THREAD

**Issue by ozonestrike** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#194]
I have the message: Error with GQLOperations (VideoPlayerStreamInfoOverlayChannel): HTTPSConnectionPool (host = 'gql.twitch.tv', port = 443): Max retries exceeded with url: / gql (Caused by NewConnectionError ('<urllib3.connection.HTTPSConnection.HTTPSConnection object at 0x000001D189CF8A60>: Failed to establish a new connection: [WinError 10060]

Error with GQLOperations (ModViewChannelQuery): HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FFF8C5B700>: Failed to establish a new connection: [WinError 10060]

Thank you for your understanding.

**Comment by Tkd-Alex** [comment]
It's permanent? Frequently or randomly?

**Comment by ozonestrike** [comment]
permanent :(

**Comment by cakehm** [comment]
I'm also getting this problem except the gql operations tries to make the connection on repeatly until you stop the script.

**Comment by ozonestrike** [comment]
I have the impression that it does not come back anymore =)

**Comment by cakehm** [comment]
> 
> 
> I have the impression that it does not come back anymore =)

It doesn't for me. works fine again.

**Comment by Tkd-Alex** [comment]
@ozonestrike @cakehm 
Can we close this? :)
