### ISSUE TITLE
Is this even possible?

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#195]
How to prioritize channels according to the list, for example, I have a list of 10 channels. 1 if not in the network then it should farm for 2, if 2 is not in the network then for 3, ....

**Comment by RakSrinaNa** [comment]
Just read the README... https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#settings `ORDER`
