### ISSUE TITLE
redeeming points

### ISSUE THREAD

**Issue by josephisticated** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#196]
**Is your feature request related to a problem? Please describe.**
some streamers have limited supply channel points rewards and i always miss them, cant catch them on time

**Describe the solution you'd like**
it would be nice if we could add an option to redeem channel points for a specific streamer's specific item/s

**Describe alternatives you've considered**
we can try to catch them manually but its hard in hundreds of people

**Additional context**
![image](https://user-images.githubusercontent.com/53388005/120634112-8e24ed80-c473-11eb-9dfb-92911dbdd9e9.png)
![image](https://user-images.githubusercontent.com/53388005/120634142-954bfb80-c473-11eb-8b17-0713af864faf.png)

**Comment by RakSrinaNa** [comment]
In my opinion this doesn't get into the scope of the bot. This feature would just automate redeeming things and isn't really "farming points" in any way. The best it does is actually make you lose points. This is similar to #190 in a way.

This is just my opinion though. But seeing how this project is already quite complex with a ton of config, I personally think that kind of thing would fit better in a separate project.
