### ISSUE TITLE
It does not place the bet.

### ISSUE THREAD

**Issue by cavitcakir** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#198]
The miner catches when the prediction starts, also outputs about the odds, etc. However, after prediction outputs, it does not automatically place the bet. 

These are my settings;
```
streamer_settings=StreamerSettings(
        make_predictions=True,       
        follow_raid=True,            
        claim_drops=True,            
        watch_streak=True,           
        join_chat=True,              
        bet=BetSettings(
            strategy=Strategy.SMART, 
            percentage=40,            
            percentage_gap=20,       
            max_points=5000000,        
            stealth_mode=True,       
            filter_condition=FilterCondition(
                by=OutcomeKeys.TOTAL
                where=Condition.GTE,
                value=4
            )
        )
    )
```

output:
```
INFO - [on_message]: ⏰  Place the bet after: 115.65s for: EventPrediction(event_id=x streamer=Streamer(username=luquelol, channel_id=x, channel_points=310), title=x)
INFO - [make_predictions]: 🍀  Going to complete bet for EventPrediction(event_id=x, streamer=Streamer(username=x, channel_id=x, channel_points=310), title=x)
INFO - [make_predictions]: 🍀  Place 124 channel points on: x (BLUE), Points: 24k, Users: 5 (71.43%), Odds: 1.87 (53.48%)
```

 - OS: MacOs
 - Python version 3.8.3

**Comment by RakSrinaNa** [comment]
Maybe the sentence isn't very clear but `INFO - [make_predictions]: 🍀  Place 124 channel points on: x (BLUE), Points: 24k, Users: 5 (71.43%), Odds: 1.87 (53.48%)` actually indicates that it did make a prediction of 124 points on the blue choice.

**Comment by cavitcakir** [comment]
Firstly thank you,
Yes but afterward it just keeps mining, whereas I expect some information about the bet.

**Comment by RakSrinaNa** [comment]
You'll get info when the bet ends. For example:

```
05/06 15:24:52 - 🍀  Going to complete bet for EventPrediction: rainbow6hu (15.61k points) - Mennyit lő REXHUN?
05/06 15:24:52 - 🍀  Place 780 channel points on: 9.5 ALATT (BLUE), Points: 82k, Users: 15 (41.67%), Odds: 2.96 (33.78%)
...
05/06 16:15:43 - 🚀  +2294 → rainbow6hu (17.12k points) - Reason: PREDICTION.
05/06 16:15:43 - 📊  EventPrediction: rainbow6hu (17.12k points) - Mennyit lő REXHUN? - Decision: A: 9.5 ALATT (BLUE) - Result: WIN, Gained: +1.51k
```

In the middle it'll continue mining normally. Like in my example it kept doing its normal thing while the bet was ongoing (~1h).

**Comment by cavitcakir** [comment]
I waited for so long and I did not get "Reason: PREDICTION." line. 
I would like to give my logs but I don't want to share it for privacy.

**Comment by cavitcakir** [comment]
I figured out the bug. 
My server was in a country in which Twitch's betting system is not allowed. 
I just changed the location of my server to another country and the problem is solved.
I think there should be an error message which indicates, betting is not allowed in your country.
