### ISSUE TITLE
How to change points shown in console logs from rounded decimal to exact number?

### ISSUE THREAD

**Issue by chronoquairium** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#201]
As of current, this is what I see in my console when it loads:
![image](https://user-images.githubusercontent.com/68948661/121292697-62ad6300-c8b8-11eb-93d8-b7c833c29fc7.png)

I want to change the points to be an exact number, like from 79.09k to 79093, or 8.6k to 8602. I'm okay with editing the file myself, but I don't know where to look. How would I go about doing this?

**Comment by RakSrinaNa** [comment]
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/master/TwitchChannelPointsMiner/classes/entities/Streamer.py#L-196

Honestly changing it won't bring you much more info. You'll only one more digit precision (the units) and we'll, it isn't really that useful.

The linked line will change some of the points display in the app but not all. If you want them all you should probably search for `millify`.
