### ISSUE TITLE
Betting system

### ISSUE THREAD

**Issue by rustransl** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#202]
Good day. Is it possible to add a Martingale betting system?

**Comment by Yishaqel** [comment]
I suggested this at the beginning of this project and I think it is not easy to do when the percentages are variable, it should be equal to 50% to be able to do this strategy.

**Comment by rustransl** [comment]
We always place bets on high odds. It usually ranges from 1:2 to 1:5.
