### ISSUE TITLE
black list

### ISSUE THREAD

**Issue by vegych** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#203]
Hi!
and it's me again. Again, I am unable to create a blacklist for streamers. I do not understand where to insert these lines

**Comment by RakSrinaNa** [comment]
There's a written example in "How to use" at the end of step 3...
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use

**Comment by vegych** [comment]
![image](https://user-images.githubusercontent.com/84208023/121406100-71525380-c966-11eb-9faa-cc76700e1e6b.png)
Do I understand correctly that these lines should be here?

**Comment by vegych** [comment]
Ok, but here's the thing. Everything starts as it should, but after some waiting for the list of streamers, the window just closes

**Comment by RakSrinaNa** [comment]
If you're on Windows and run the script by double clicking it, then I'd advise you to stop doing that and run it from the command line instead.
In general python programs are not meant to be ran the same way as exe files.

**Comment by vegych** [comment]
![image](https://user-images.githubusercontent.com/84208023/121408822-782e9580-c969-11eb-90b9-749a8642c7da.png)
ok now i have this problem

**Comment by RakSrinaNa** [comment]
I never used the blacklisting system, but to me it looks like you blacklisted the user ilame but don't follow him/her.

**Comment by RakSrinaNa** [comment]
Ok it's not really that, it's because the name is `iLame` and not `ilame`. Case is important.
