### ISSUE TITLE
Cant figure out this error?

### ISSUE THREAD

**Issue by 0cryptex0** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#210]
I have recently used this program on my windows 10 pc and its worked great, but my pc is in my room and I wanted to not have to run my pc 24/7 while I am sleeping. I  have a raspberry pi 4, but when I try running the program I get this error: 

![IMG_1704](https://user-images.githubusercontent.com/79380032/122311969-4aa19900-cee1-11eb-85f1-98fe23fce098.jpg)

**Comment by Element21** [comment]
Make sure you run `python3 -m pip install -r requirements.txt` from the
root of the project!

**Comment by 0cryptex0** [comment]
> Make sure you run "python3 -m pip install -r requirements.txt" from the root of the project!

Yes, I have done this and still get the same error...

**Comment by Tkd-Alex** [comment]
Execute `pip freeze --local` and paste here the output please
For me, you haven't correct installed all the requirements, as suggested by @Element21

**Comment by 0cryptex0** [comment]
> Execute `pip freeze --local` and paste here the output please
> For me, you haven't correct installed all the requirements, as suggested by @Element21

pi@raspberrypi:~ $ pip freeze --local
appdirs==1.4.4
backports.functools-lru-cache==1.6.4
configparser==4.0.2
contextlib2==0.6.0.post1
distlib==0.3.2
filelock==3.0.12
importlib-metadata==2.1.1
importlib-resources==3.3.1
inflect==3.0.2
irc==16.4
jaraco.classes==2.0
jaraco.collections==2.1
jaraco.functools==2.0
jaraco.itertools==4.4.2
jaraco.logging==2.0
jaraco.stream==2.0
jaraco.text==3.2.0
more-itertools==5.0.0
pathlib2==2.3.5
pytz==2021.1
scandir==1.10.0
singledispatch==3.6.2
tempora==1.14.1
typing==3.10.0.0
virtualenv==20.4.7
zipp==1.2.0

**Comment by RakSrinaNa** [comment]
you should check what your command pip refers to.

Often pip refers to a python2 installation, and pio3 to a python3 installation. Depending on how you install your python then executables may have different names.

In a general manner you can do `python3 -m pip freeze --local` to execute the same command but with pip associated with python3.

**Comment by 0cryptex0** [comment]
> you should check what your command pip refers to.
> 
> Often pip refers to a python2 installation, and pip3 to a python3 installation. Depending on how you install your python then executables may have different names.
> 
> In a general manner you can do `python3 -m pip freeze --local` to execute the same command but with pip associated with python3.

yes, this does seem to be the issue. I entered the command `python3 -m pip freeze --local` and nothing came up.

**Comment by Element21** [comment]
Have you just tried `python3 -m pip install requests==2.25.1
websocket-client==1.0.1
browser_cookie3==0.12.1
pillow==8.2.0
python-dateutil==2.8.1
emoji==1.2.0
millify==0.1.1
pre-commit==2.13.0
colorama==0.4.4
flask==2.0.1
irc==19.0.1`?
