### ISSUE TITLE
TwitchChannelPointsMiner

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#211]
![image](https://user-images.githubusercontent.com/78689718/122443804-98350900-cfa8-11eb-97f8-118171cd7ad2.png)
The "requirements" file has been executed
How do I install the "TwitchChannelPointsMiner" module?

**Comment by YaZanuda111111** [comment]
python-3.10.0b1

**Comment by ss2oo7** [comment]
Привет,ты русский?а то тут все на английском,есть телеграм?мог бы помочь

**Comment by YaZanuda111111** [comment]
Да русский, телега @qikert

**Comment by YaZanuda111111** [comment]
Решилось, установил "pip install browser-cookie3==0.6.0"
