### ISSUE TITLE
Place the bet on different sides with different accounts

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#213]
How can I make it ALWAYS placed on the side where the% is lower and how can I make it placed on the side where the% is higher? Who understands how to indicate this correctly, can you throw off these 2 examples please?

Here is what I have indicated right now
strategy=Strategy.PERCENTAGE,
            percentage=100,
            percentage_gap=1,
            max_points=50,
            stealth_mode=True,
            filter_condition=FilterCondition(
                by=OutcomeKeys.ODDS_PERCENTAGE,
                where=Condition.LTE,
                value=800

**Comment by YaZanuda111111** [comment]
Or you can just 2 codes that are placed on opposite sides

**Comment by Tkd-Alex** [comment]
uhm, I don't understand what do you want

**Comment by YaZanuda111111** [comment]
I have 2 accounts. I want him to bet on one side and the other on the opposite side.

I am writing through a translator

**Comment by Tkd-Alex** [comment]
@YaZanuda111111 Solved? Just write a different `FilterCondition` for each streamer

**Comment by YaZanuda111111** [comment]
@Tkd-Alex   I do not want to farm points, but try to be online at the same time on more than 10 streams using your bot. For everyone, prescribing filters is not suitable.
Right now, I changed a little data in the code and I will check it, maybe it's decided

**Comment by Tkd-Alex** [comment]
You have asked in this issue about bet placing :confounded: 
I think I can close this issue.

**Comment by YaZanuda111111** [comment]
oh, sorry, I answered the wrong topic. Yes, this issue can be closed, it has already been resolved. Thanks.
