### ISSUE TITLE
Watch all online Streamers

### ISSUE THREAD

**Issue by BrenoFariasdaSilva** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#214]
The Script you created is almost perfect. I really love it, but i really needed it to watch all streamers, not just 2.
The reason is that i follow 200+ streamers and, on the weekend where there are a lot of streamers with drops enabled, i have like 100+ online streamers at the same time.

The best solution for me was for it to watch all followed streamers by an account so, even if the streamer is offline, it would raid follow and get the points.
In case that's not possible, watch only online streamers would also be awesome.
In case that's also not possible, try to increase the streamers watched at the same time (and make a comment in example.py) with the new limit.

I think that's it. Thank you for your time!

**Comment by RakSrinaNa** [comment]
This is in the readme... This is a twitch limitation. You can't watch more than 2 at once. 

If you do watch more then only 2 of them will be counted.

**Comment by ss2oo7** [comment]
can you drop me list of your strimer pls))

**Comment by BrenoFariasdaSilva** [comment]
> This is in the readme... This is a twitch limitation. You can't watch more than 2 at once.
> 
> If you do watch more then only 2 of them will be counted.

The limit is for the Account itself or IPAdress?

**Comment by ss2oo7** [comment]
I write you in telegram)Please check

**Comment by Tkd-Alex** [comment]
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#limits

> Twitch has a limit - you can't watch more than two channels at one time. We take the first two streamers from the list as they have the highest priority.
