### ISSUE TITLE
Auto Clear Logs Files

### ISSUE THREAD

**Issue by BrenoFariasdaSilva** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#215]
I just realized i had +5gb of usage on the logs folder.

With that in mind, considering that i have the Twitch Drops in backup to my Google Drive's account, it is using lots of space.
It ain't a big deal. I could just remind myself of cleaning logs folder, but it would be cool if it did regularly by itself (like on script start it deleted old profile logs).

**Comment by Tkd-Alex** [comment]
5gb :scream: 
I use the script 24/24h, and I've only 1gb 

anyway, you can always disable the logs
`logger_settings=LoggerSettings(save=False)`

We need the logs only for debugging special issue

**Comment by ColinShark** [comment]
Perhaps as a suggestion for Log Rotation:

[Loguru](https://github.com/Delgan/loguru#readme) allows for both rotation and retention, as well as compression. Maybe that's worth a shot [to configure automatic removal of older/bigger log files](https://loguru.readthedocs.io/en/stable/overview.html#easier-file-logging-with-rotation-retention-compression).

**Comment by Tkd-Alex** [comment]
> [b874d95](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/b874d95ec323549abcf6ee3dbad17135b4e75b30) bad change. I'm using logs for gathering data. Almost screwed all my collected logs. Should be manually activated.

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/181d0368aff5ed6e23f555bc13aa7bc4aded788b

**Comment by 1v** [comment]
> 181d036

thanks
