### ISSUE TITLE
Option to Follow Channels on the list (if we do not follow them already)

### ISSUE THREAD

**Issue by BrenoFariasdaSilva** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#216]
Other cool feature that would be awesome, is to be an option in the "profile.py" file with the option to follow streamers on the list. With that in mind, if i wanted to add a new streamer to my list, i won't need to open Twitch and follow the streamer, cause i would leave that option on and would save time. 

It could be an option like:
```
streamer_settings=StreamerSettings(
         follow_channels_from_list = True,
        make_predictions=True,               
        follow_raid=True,                    
        claim_drops=True,                       
        watch_streak=True,                  
        join_chat=True, 
```

**Comment by ss2oo7** [comment]
Please Check your telegram.i write you 
Tg:Photoprikolchik

**Comment by ss2oo7** [comment]
for automatic tracking (Follow) on various streamers, I use a program that I wrote in bas

**Comment by BrenoFariasdaSilva** [comment]
Why didn't you publish it into Github?

**Comment by Tkd-Alex** [comment]
Duplicated of #145

**Comment by Sunkwii** [comment]
Did you manage to do this feature?
