### ISSUE TITLE
i need your help

### ISSUE THREAD

**Issue by ss2oo7** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#217]
Guys and the author, I pray for your help!
I created 5 folders on my virtual computer, each of the 5 folders has its own account (that is, the accounts are different).
the problem is that only one account 5 successfully places bets and there is a log that so many coins have been won ... (it was this account that I entered through the browser)
The other 4 accounts only try to do it, but do not do it ((((
here are the logs (which cannot place bets): Photo1
I do not understand why this is so. The author or someone, help me, this is very important, I rechecked all the settings.
I am inclined to believe that he makes bets only on the account that was authorized through the browser (without entering a password in the run.py file)
![image](https://user-images.githubusercontent.com/84682083/122824989-03087c00-d2ea-11eb-9c43-dacc6f4c50d8.png)

**Comment by RakSrinaNa** [comment]
If you have 5 different accounts then you need to log onto each of them... 
Else it'll only be the same account connect and therefore only mine with one account.

**Comment by ss2oo7** [comment]
I did this too. I specified both the name and password for my training records in the run.py file. But this does not help, I know what can be done so that all 5 miners would place bets working on the same computer at the same time

**Comment by ss2oo7** [comment]
**_I ask everyone who knows for help. I am ready to pay for your help_**
@Tkd-Alex The problem is even that let's say I have 5 different copies of the miner folder with different accounts.
Suppose if I run the first miner with my main account Twitch (data from which I will indicate in the run.py file), then it will make bets.
if I run conditionally the second folder with my non-main account twitch (I run only one program with a non-main account), then he will not make bets, dropped the log above
I ask everyone who knows for help. I am ready to pay for your help

**Comment by RakSrinaNa** [comment]
To me it's not clear. You should give more info. What is the structure of your "duplicated folder".
Logs... you should have 5 separate logs, not just one. And share the log files themselves (anonymized if you want) not a screenshot.

**Comment by ss2oo7** [comment]
> Мне непонятно. Вы должны дать больше информации. Какова структура вашей «дублированной папки».
> Журналы ... у вас должно быть 5 отдельных журналов, а не один. И поделитесь самими лог-файлами (анонимными, если хотите), а не скриншотами.

I downloaded a folder with the program from GitHub.
copied and pasted it a couple of times, it turned out that there is twich miner, twich miner copy, twich miner copy copy and so on ..
Then I just changed the individual nickname and password in each folder.
How can I share the logs with you?

**Comment by ss2oo7** [comment]
> Мне непонятно. Вы должны дать больше информации. Какова структура вашей «дублированной папки».
> Журналы ... у вас должно быть 5 отдельных журналов, а не один. И поделитесь самими лог-файлами (анонимными, если хотите), а не скриншотами.

Can i write you in telegram maybe?
