### ISSUE TITLE
2FA enabled login not fully working

### ISSUE THREAD

**Issue by SiIason** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#22]
When running initial setup with a 2FA enabled account, the twitch login backup code is unable to read required "persistent" field information to bypass robot protection from host browser cookies.

Tested with Chrome and Firefox latest builds, Win10, Python 3.9

Tested if other cookie fields were available for output but appears no information is been read from host browser twitch cookie. Will do further testing and post traceback output shortly.

**Comment by Tkd-Alex** [comment]
Maybe I missed something, or I've not understood your issue, but the 2FA is working for me
![image](https://user-images.githubusercontent.com/14061593/106045189-f0926980-60e0-11eb-9d8d-d4136d73a5eb.png)

**Comment by SiIason** [comment]
I cant get it to reproduce. I think it was happening because captcha was being returned at login.
I remember the log prompt changed from "INFO - [login_flow]:" to "INFO - [login_flow_backup]:"

I'm trying to get the captcha to reactivate using VPN but no luck as yet.

**Comment by Tkd-Alex** [comment]
I had a similar problem only time after change password and logged-in multiple times on different browser.
So when I attempt to log in with script I have an error related to robot-captcha, but after logged-in with browser It's work perfectly

I'm on ArchLinux. The login system was not developed by me, It's from the original repository and I think that some code was caught from another one (cited in comment). I keep the issue open, If you are able to reproduce again and provide steps we can try to fix :smile:

**Comment by SiIason** [comment]
So I got captcha to prompt, and it worked perfectly... *shrug*
Apologies my system must have just been having an off day yesterday.
