### ISSUE TITLE
My script stopped working today got a lot of errors, did twitch made an update?

### ISSUE THREAD

**Issue by zDioogoSilva** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#221]
Yesterday was working fine but today i got a lot of errors on my 2 accounts running the script

**Comment by Yishaqel** [comment]
A little information on the errors you are receiving would be great to try to help you. So far it is working fine for me, could it be due to your internet connection?

**Comment by zDioogoSilva** [comment]
> A little information on the errors you are receiving would be great to try to help you. So far it is working fine for me, could it be due to your internet connection?

![image](https://user-images.githubusercontent.com/61512612/122947747-c6bc3680-d350-11eb-8f98-572c5cc4afa6.png)

Idk what happened , i don't think that this is my internet

**Comment by Yishaqel** [comment]
I just opened it and it's working without problems so far, try restarting it.

**Comment by zDioogoSilva** [comment]
> I just opened it and it's working without problems so far, try restarting it.

what a weird thing, has been working fine for like 3 weeks for me , and today suddenly starts bugging

**Comment by Yishaqel** [comment]
I honestly have no idea about programming to be able to help you, that message reminds me when you bet manually and the bot does it too. I hope someone can help you with the problem but so far it is working normally for me.

**Comment by RakSrinaNa** [comment]
Your analytics data is probably corrupted. Delete it or fix it manually.

**Comment by zDioogoSilva** [comment]
> Your analytics data is probably corrupted. Delete it or fix it manually.

How can i do that? My knowledge of programing is very bad

**Comment by RakSrinaNa** [comment]
Delete the analytics folder

**Comment by zDioogoSilva** [comment]
> Delete the analytics folder

Thanks , i deleted the logs and the analytics folder and it solved the problem

**Comment by MrChuw** [comment]
same problem, https://i.imgur.com/YtkGso4.png , the problem https://i.imgur.com/4FluZq7.png
