### ISSUE TITLE
Bets are not being places (Time runs out?)

### ISSUE THREAD

**Issue by Pajkaa** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#222]
The time after which bet is going to be placed is longer than the bet is open.
![Screenshot_14](https://user-images.githubusercontent.com/63790728/123521929-0f118680-d6ba-11eb-8e6c-944a8007edb3.png)

**Comment by RakSrinaNa** [comment]
The delay is correct. What probably happened is that the bet was closed by a moderator manually before the end time to bet was reached.

**Comment by Pajkaa** [comment]
Apparently they do it on LEC channel too then. Is there a way to make the bet go through a few seconds earlier or something like that?

**Comment by RakSrinaNa** [comment]
For now there is not way to change that though the settings. You can change the code but it'll apply to all your streamers.

Or you can try #224 . I don't really have much channels that do this behavior except r6. In that case what can be done is set `delay_mode=FROM_START` and `delay=300` for example. This way the bet would be placed 5mins after the bet is opened as the bet is often still open after 5mins (and we avoid waiting basically 29mins 55s). This PR needs testing though, it may have bugs.

**Comment by Pajkaa** [comment]
I played with it for a bit and it seems to work perfectly for me.

**Comment by ss2oo7** [comment]
> Я немного поиграл с ним, и, похоже, он отлично работает для меня.

How mach delay you do?i have this problem too

**Comment by ss2oo7** [comment]
> Я немного поигрался с ним, и, похоже, он отлично работает для меня.

Can you help me pls

**Comment by ColinShark** [comment]
@Pajkaa I experienced this a whole while back too. I didn't open an issue because I realized what was going on.

As @/RakSrinaNa pointed out, the R6 channel makes the predictions for the map win, but closes the poll right when the match starts, instead of letting the 30 minute timer run out. Them closing the poll early causes this "error" to appear. The suggested custom timer would probably aid.

**Comment by Berksmb** [comment]
I am getting similar behaviour, except no Event is no longer active message.
![image](https://user-images.githubusercontent.com/12162231/127191797-c37070b8-2303-4aee-b851-ff856dc64ea0.png)
