### ISSUE TITLE
Use comma instead of period for delimeter

### ISSUE THREAD

**Issue by Element21** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#23]
Twitch says I have 5.7k points (5,700), but the script says ```5.700``` points. I think this is why millify doesn't work. We just have to replace the period with a coma or remove the formatting that uses a period.

**Comment by Tkd-Alex** [comment]
So in prettify we should use as second parameters `','` 
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/6e1f74c9c21615eec051489ca5339629d55d1703/TwitchChannelPointsMiner/classes/Streamer.py#L37

**Comment by Tkd-Alex** [comment]
![image](https://user-images.githubusercontent.com/14061593/106202478-4d158780-61ba-11eb-8751-c28929649c41.png)

In Italy translation we have the dot for period. 88k = 88.583

**Comment by Element21** [comment]
Thanks for the advice, I will author a pr soon. By the way, how many hours have you sunk into this project? It seems like there are updates every day!

**Comment by Tkd-Alex** [comment]
Not many 😂
I'm fast with the code 🤣🤣🤣

**Comment by Tkd-Alex** [comment]
> Thanks for the advice, I will author a pr soon. 

Anyway, If you will do a PR remember to reference this issue. The issue should be open and once the PR accepted this will be closed.

I have only one question about this:
So the correct form on English number comma is used for decimal numbers?
Like: 12.234,67 ?

**Comment by vadrozh** [comment]
I think it's better to use space. It's more universal.

**Comment by Element21** [comment]
> > Thanks for the advice, I will author a pr soon.
> 
> Anyway, If you will do a PR remember to reference this issue. The issue should be open and once the PR accepted this will be closed.
> 
> I have only one question about this:
> So the correct form on English number comma is used for decimal numbers?
> Like: 12.234,67 ?

No, a comma is used for numbers to the left of the decimal place, like 100,000,000 = 1M and the period signifies the start of decimal places (example: 100,000,000.1234)

**Comment by Element21** [comment]
But it doesn't really matter what delimiter we use, as long as we tell that to millify so it can convert to more universal charters like K, and M

**Comment by Element21** [comment]
By the way, what is the point of the TWITCH_CLIENT_ID constant? Should I try to use mine because I'm in the US, so it will use commas or something?

**Comment by Tkd-Alex** [comment]
> By the way, what is the point of the TWITCH_CLIENT_ID constant? Should I try to use mine because I'm in the US, so it will use commas or something?

It's not related to this issue. Anyway I think you have the same value. If you search for this value on GitHub It's overused:
https://github.com/search?q=kimne78kx3ncx6brgo4mv6wki5h1ko&type=code
