### ISSUE TITLE
git clone not working on Termux Android

### ISSUE THREAD

**Issue by IDerFlohI** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#236]
the command for cloning the application for Termux isn't working. 
Its asking for my username and password and when I enter it correctly I get this error:
`remote: Password authentification is temporarely disabled as part of brownout. Please use a personal access token instead`
`fatal: unable to access 'https://github.com/Tkg-Alex/Twitch-Channel-Points-Miner-v2/' : The reqest URL returned error: 403`

Weird is also that in general for some github projects it works and for some don't
I installed Termux on my Android phone if that helps

Has anyone an idea why it isn't working ?

**Comment by RakSrinaNa** [comment]
This has nothing to do with this repo and is a restriction put in place by github. Searching your issue on google will give lots of results.

You can't use your username/password to perform git commands. You need to use a ssh key or use user/token.

**Comment by IDerFlohI** [comment]
Thanks now I got everything working 😄
