### ISSUE TITLE
Problem to install the script on Debian

### ISSUE THREAD

**Issue by EEEmill** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#238]
Hello everybody.

I have followed the install info but when I am going to run "pip install -r requirements.txt " I got the error message. "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'".

Any ideas?

**Comment by RakSrinaNa** [comment]
Run the command in the correct directory (root of project)

**Comment by Tkd-Alex** [comment]
- `git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2`
- `cd Twitch-Channel-Points-Miner-v2`
- `pip install -r requirements.txt`
