### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by ceoshikhar** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#242]
Hi @Tkd-Alex 

I am also trying to build something similar to this. I have been going through the repository to understand how the miner works. Although I am not able to understand it very clearly (PS - I work with JavaScript and never worked with Python). 

I want to ask two things :
1. Are you using some sort of headless browser to "simulate" watching a stream? So that you get to farm the channel points.
2. If you are not using the above, you must be using some sort of Twtich API. If yes, please share some links to the documentation of that API. I have been  going through Twitch API docs but couldn't find anything about claim channel points, make bets, etc. Although I somewhat felt like you have reverse engineered Twitch API calls from the "Network" tab of the browser and you are just simulating it as if the logged in user is interacting with the Twitch app.

I think I am just asking you to briefly explain the design and architecture of how this works.

Thanks you in advance and cheers!

**Comment by RakSrinaNa** [comment]
1. Communication is done through a websocket. The same Twitch uses if you use the developer tools of the browser (gql requests)
2. This API isn't public.

**Comment by Tkd-Alex** [comment]
Little hint for JavaScript 
![image](https://user-images.githubusercontent.com/14061593/127780910-a0d41105-6867-4d39-a641-d84f7ba7b640.png)
