### ISSUE TITLE
NameError: name 'DelayMode' is not defined

### ISSUE THREAD

**Issue by hoak2** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#243]
cloned latest version, but parameter delay_mode is not recognized. latest phyton, tried with windows and linux.

    delay_mode=DelayMode.FROM_END,       # When placing a bet, we will wait until `delay` seconds before the end of the timer
NameError: name 'DelayMode' is not defined

    delay_mode=FROM_END,       # When placing a bet, we will wait until `delay` seconds before the end of the timer
NameError: name 'FROM_END' is not defined

The readme is not very precise on the implementation, beside of this one example that doesnt work.

**Comment by RakSrinaNa** [comment]
Did you add the import like in the readme?

**Comment by hoak2** [comment]
Yeah I copied the lines

**Comment by RakSrinaNa** [comment]
Can you maybe share your script? That'd be easier to help.

**Comment by Tkd-Alex** [comment]
`from TwitchChannelPointsMiner.classes.entities.Bet import DelayMode`

**Comment by hoak2** [comment]
> `from TwitchChannelPointsMiner.classes.entities.Bet import DelayMode`

thank you, thats it.
