### ISSUE TITLE
Typo when Ctrl+C

### ISSUE THREAD

**Issue by SiIason** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#25]
On Ctrl+C...
INFO - [end]: CTRL+C Detected! Please wait just a moment!s

**Comment by Tkd-Alex** [comment]
Something was wrong with the review :rage: 
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/20/files/5812b1ab8abd97b42f3a6fe6e4cccafdfc68b22c#r564995392
