### ISSUE TITLE
Hi, how to raise the limit of simultaneously watched channels?

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#252]
I know that the maximum points can be farmed on a maximum of 2 channels at the same time. Where can I change the value?

**Comment by YaZanuda111111** [comment]
...\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py 
Which line is responsible for the maximum number of simultaneous views of broadcasts?
line 264?

**Comment by Tkd-Alex** [comment]
Have you already searched on this repo or simply read the README? 😪

**Comment by mrcsdl** [comment]
You can only farm on 2 channels at the same time. This is a hard cap from twitch.

**Comment by YaZanuda111111** [comment]
How to raise the simultaneous number of channel views in the new version of the program? I know that twitch allows you to farm points only on 2 channels, but the program can sit on more than 2 channels
