### ISSUE TITLE
No vote is send for prediction

### ISSUE THREAD

**Issue by NoSpread** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#257]
**Describe the bug**
I have the feeling that predictions do not work atm.

19/08 13:08:26 - Place the bet after: 116.98s for: EventPrediction: streamer (4.74k points) - question?
19/08 13:10:23 - Going to complete bet for EventPrediction: streamer (4.74k points) - question?
19/08 13:10:23 - Place 237 channel points on: No (PINK), Points: 549k, Users: 229 (60.74%), Odds: 1.85 (54.05%)

The bet is never placed when I check in my browser. Therefor, there is also no "won" message afterwards.

**To Reproduce**
Wait for are prediction of a watched streamer to happen

**Expected behavior**
It should send a vote, so you can collect the reward afterwards.

**Desktop (please complete the following information):**
 - OS: Debian
 - Python version 3.7.3

Let me know if I might do something wrong or if I can provide additional information.

**Comment by Tkd-Alex** [comment]
Maybe It's a wrong filter?

**Comment by RakSrinaNa** [comment]
I think if a filter is applied, it is logged.

Maybe you can try #251 and you'll have more infos why twitch rejected the bet. I personally had lots of "event not active" because predictions were closed manually by the streamer and so the bet was placed too late.

**Comment by NoSpread** [comment]
> I think if a filter is applied, it is logged.
> 
> Maybe you can try #251 and you'll have more infos why twitch rejected the bet. I personally had lots of "event not active" because predictions were closed manually by the streamer and so the bet was placed too late.

Thank you that could be it, I'll try and will report if that fixes it.

**Comment by NoSpread** [comment]
@RakSrinaNa Indeed you were right, the terms of service have to be accepted, now it seems to work. Thank you.
