### ISSUE TITLE
IDK what this error is

### ISSUE THREAD

**Issue by olkoxd** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#260]
**ERROR: Could not find a version that satisfies the requirement websocket-client==1.0.1 (from -r requirements.txt (line 2)) (from versions: 0.3, 0.4, 0.4.1, 0.5.0a0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.15.0, 0.16.0a0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.39.0, 0.40.0, 0.42.0, 0.42.1, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0, 0.53.0, 0.54.0, 0.55.0, 0.56.0, 0.57.0, 0.58.0, 0.59.0)
ERROR: No matching distribution found for websocket-client==1.0.1 (from -r requirements.txt (line 2))**

**Comment by Tkd-Alex** [comment]
Make sure to have the latest version of python

**Comment by olkoxd** [comment]
i downloaded 3.9.6 but in cmd it still shows old version
<img width="440" alt="Snímka obrazovky 2021-08-30 o 21 34 22" src="https://user-images.githubusercontent.com/89806878/131394917-d634b8d5-c1a7-477a-a6b4-2af84f9157c8.png">
![Snímka obrazovky 2021-08-30 o 21 34 41](https://user-images.githubusercontent.com/89806878/131394926-6e4c81b4-4607-4b6e-a73c-1180052bd495.png)

**Comment by Tkd-Alex** [comment]
It's not a problem related to this script.
Maybe you need to setup a virtual env or venv variable

**Comment by olkoxd** [comment]
ok thanks ill try to fix it

**Comment by RakSrinaNa** [comment]
Use need to use python3 and not python.
python is the default python installed by default in the os (version 2).

**Comment by olkoxd** [comment]
oh yeah i was suppose to use pip3 not pip thx for help
