### ISSUE TITLE
Want to understand the code

### ISSUE THREAD

**Issue by ceoshikhar** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#263]
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/ef7cf97c408dd22152c40259f4033e5556f92055/TwitchChannelPointsMiner/classes/Twitch.py#L342

Can someone please tell me if the `data` being sent on the `watch minute event` is `JSON` data or `FormData` ?

**Comment by ceoshikhar** [comment]
I am trying to implement the same in Node.js and I am not able to replicate the `send_minute_watch` request. I am able to replicate all the other requests. Note: I have the correct `info.url` and `info.payload` values sent in a POST request. I am starting to think maybe it's not JSON data like other requests but it's a `multipart/form-data` body.

**Comment by RakSrinaNa** [comment]
Just use the debug tools in the browser while in the browser. What is used is GraphQL, so JSON based queries.

#242

**Comment by ceoshikhar** [comment]
Thank you so much!! @RakSrinaNa  I have been trying to figure this out for the last 2 days. With your screenshot I could see it was supposed to be have a `body` of type  `application/x-www-form-urlencoded`. It worked!!! Can't tell you how frustrating it was.

PS - how did you get this screenshot? I have no idea how to do this. Did you use some IDE for Python?

**Comment by RakSrinaNa** [comment]
Just debug the python code and go down the the `requests` library. You can use whatever tool you want for debugging. In the screenshot it's Pycharm.
