### ISSUE TITLE
"ModuleNotFoundError: No module named 'colorama'"

### ISSUE THREAD

**Issue by BasicallyBasic99** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#265]
PS C:\Users\Admin\Documents\GitHub\Twitch-Channel-Points-Miner-v2> python run.py
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\GitHub\Twitch-Channel-Points-Miner-v2\run.py", line 4, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

This is something that pops up. I have tried doing other methods but when I try to install colorama I get 

"Requirement already satisfied: colorama in c:\program files\python36\lib\site-packages (0.4.4)"

Not too sure what to do about this.

**Comment by RakSrinaNa** [comment]
You probably should look other issues as it has been asked many times.

You probably have 2 python installed and you execute the pup command onto one and run the script with the other.

**Comment by CalebSiriban** [comment]
pip install -r requirements.txt
