### ISSUE TITLE
Exception raised when a sub

### ISSUE THREAD

**Issue by billyabong** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#266]
When farming points on a channel I'm subed to an error is thrown, prevents the graphing for that channel from updating and prevents the logger from reporting correctly on how many points have been farmed.  _The farming doesn't actually stop just loses from functions._

**To Reproduce**
1. Sub to a channel
2. Try farm points on that channel
3. Wait ~5 mins until console logs error.

**Expected behavior**
05/09 23:49:37 - Exception raised for topic: community-points-user-v1 and message: {'type': 'points-earned', 'data': {'timestamp': '2021-09-05T23:49:37.332626357Z', 'channel_id': '_redacted_', 'point_gain': {'user_id': '_redacted_', 'channel_id': '_redacted_', 'total_points': 12, 'baseline_points': 10, 'reason_code': 'WATCH', 'multipliers': [{'reason_code': 'SUB_T1', 'factor': 0.2}]}, 'balance': {'user_id': '_redacted_', 'channel_id': '_redacted_', 'balance': 300851}}}
Traceback (most recent call last):
  File "/root/twitch/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 182, in on_message
    ws.streamers[streamer_index].persistent_series(
  File "/root/twitch/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 207, in persistent_series
    self.__save_json("series", event_type=event_type)
  File "/root/twitch/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 222, in __save_json
    json_data = json.load(open(fname, "r")) if os.path.isfile(fname) else {}
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1173 column 5 (char 24576)

**Desktop (please complete the following information):**
 - OS: Linux Container on a Proxmox Server
 - Python version 3

**Additional context**
I've tried a clean install same exception is still thrown.

**Comment by Tkd-Alex** [comment]
Your JSON file analytics is broken. Please delete the entire folder of analytics, or single file (if you know the streamer).
You can also try to fix the JSON file.

Duplicated of https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/187 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/221

**Comment by billyabong** [comment]
Resolved.  Removing the JSON file associated with the streamer fixed the error.
