### ISSUE TITLE
Script stopped working: Error while trying to listen for a topic: {response}

### ISSUE THREAD

**Issue by IDerFlohI** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#267]
So the Script tries to load the streamers, but says *'does not exist'* after every streamer (instead of *'online'* or *'offline'*) and at the end (If all streamers are *'not'* loaded) I get this error Message:

`error from callback <function WebSocketsPool.on_message at 0x000001D7DD8760D0>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'pk7T3YQxDQmGtpFcLnOsLSlI5EZxTn'}`

  `File "C:\Users\...\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\websocket\_app.py", line 400, in _callback
    callback(self, *args)`

  `File "D:\...\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 358, in on_message
    raise RuntimeError(f"Error while trying to listen for a topic: {response}")`

I change nothing, it worked for a few months and now it doesn't. Has anyone an idea how to fix it?
Thanks in advance

**Comment by Tkd-Alex** [comment]
Delete your cookie and try to login again :)

**Comment by IDerFlohI** [comment]
> 
> 
> Delete your cookie and try to login again :)

Deleted the Twitch cookies but sadly nothing changed

**Comment by IDerFlohI** [comment]
> 
> 
> Delete your cookie and try to login again :)

Ok worked but now I get a different error:
`You'll have to login to Twitch!`
`Console login unavailable (CAPTCHA solving required).`

**Comment by IDerFlohI** [comment]
Seems the deleting of cookies did some things:

`Exception has occurred: MissingSectionHeaderError
File contains no section headers.`
`file: 'C:\Users\...\Firefox\\profiles.ini', line: 1
'ÿþ[\x00I\...\n`
  `File "D:\...\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 169, in login_flow_backup
    cookie_jar = browser_cookie3.firefox(domain_name=twitch_domain)`

**Comment by Tkd-Alex** [comment]
Same with chrome?

**Comment by IDerFlohI** [comment]
Havn't tried yet. Don't have that much time currently. But I'll let you know

**Comment by 66Lord69** [comment]
Good afternoon, a similar problem, but not solved by deleting the cookie folder. At startup, everything is fine showing who is offline who is online. Just 2 minutes ago an error message came out: 15/07 17:30:52 - error when calling back <WebSocketsPool.on_message function at 0x000002A451B16660>: Error when trying to listen to the topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'qmw3dYdO40HzZq3LyB4SIMg38HkDS9'}
15/07 17:30:52 - error on callback <WebSocket spool.on_message function at 0x000002A451B16660>: Error when trying to listen to the topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'Wh8glfMBSeUbLzTjjmfZRBNjWFMNk0'
