### ISSUE TITLE
Extra priority for streamers with drops active

### ISSUE THREAD

**Issue by SiIason** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#27]
Currently if a streamer with Drops enabled is in your list but late getting loaded as 'online' drops collection will not happen.

Would like to see streams with Drops enabled receive extra priority over other online streams so they always make it to the top of the online list, Drops > Channel Points.

**Comment by Tkd-Alex** [comment]
We should also change priority after claim or If a user have the drop active automatically we fixed on top of priority list?

**Comment by SiIason** [comment]
Yes, would need a post claim check to see if all drops had been collected for that campaign ie no further drop updates. And, if so return the stream to its normal priority allowing another drop enabled stream (diff game) to start collecting. Maybe blacklist the finished game for an hour instead of rechecking every drop enabled stream for that game?

**Comment by egorcreep** [comment]
Note that drop can be claimed, and streamer can be online with Drops enabled thing, so he should not prioritize after taking the drop if there are any other streamers where u didn't take the drop yet.

**Comment by SiIason** [comment]
I think you need to check if a drop is actually active and ticking, or they just have the tag enabled.
Streamer will change games or campaigns will change times but they keep the 'drops enabled' tag.

If a drop is active then boost them to the top.

Having drop priority/balance within the streamers is less important imo as there's normally only a couple of campaigns active at any one time so you shouldn't be missing out. But campaign priority would be very nice :)
