### ISSUE TITLE
Bet fails, error: MUST_ACCEPT_TOS

### ISSUE THREAD

**Issue by rrweller** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#274]
**Describe the bug**
When the script attempts to place a bet, I get the following

`4/09 10:54:15 - 🍀  Going to complete bet for EventPrediction: valorant (8.73k points) - Who will win Map 1?
14/09 10:54:15 - 🍀  Place 436 channel points on: ZETA DIVISION  (BLUE), Points: 4M, Users: 2k (51.02%), Odds: 2.89 (34.6%)
14/09 10:54:15 - 🍀  Failed to place bet, error: MUST_ACCEPT_TOS
`

**To Reproduce**
Place bet using default settings

**Expected behavior**
A bet is placed

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Python version Python 3.8.6

**Additional context**

**Comment by RakSrinaNa** [comment]
You must go accept the predictions TOS on Twitch.

**Comment by rrweller** [comment]
This fixed it, thank you

**Comment by mohammadmehri94** [comment]
> Do a prediction manually once, you'll see it on the way.

Thank you so much it now fixed
