### ISSUE TITLE
web app

### ISSUE THREAD

**Issue by GoodGodSpeaks** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#280]
I can't always keep my pc on and so I can,t mine points effectively for the streamers who are live when I am offline

If you can develop a web based tool that runs on cloud and doesn't necessarily need a pc, this will also help everyone

**Comment by RakSrinaNa** [comment]
This is basically developing a new project for this.... Plus the script can be run in the cloud too...

**Comment by Vulcanraven91** [comment]
Just rent a vps server for 1 € a month like me and you are good to go.

**Comment by EEEmill** [comment]
> 
> 
> Just rent a vps server for 1 € a month like me and you are good to go.

Do you have some small tutorial on how to setup the miner in a vps?

**Comment by LC-BWF** [comment]
you can make get a 1 core AWS EC2 (amazon) windows server for free.
