### ISSUE TITLE
"X streamer does not exist" - Happens when launching run.py

### ISSUE THREAD

**Issue by DarkVypr** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#281]
When I started my point miner today, this issue appeared. I'm not sure what caused the issue because all of my settings are the same and I haven't changed a single thing.

I have attached a screenshot of the issue and a pastebin (without personal info ofc) of my run.py.

OS: Windows 11 (Beta Channel)

Python 3.9

RUN.PY PASTEBIN: https://pastebin.com/raw/vh0g6Fcd

SCREENSHOT OF ERROR: https://i.imgur.com/f7Hzn9E.png 

EDIT: Before posting this, I reinstalled the miner, didn't work.

--------------------------------------------------------------------------------

EDIT 2:

There has been a [little fix](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/288) that works perfectly for now!

[Use This](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/wout-helix-api)

**Comment by RakSrinaNa** [comment]
Try recreating your cookies (delete them (or move them somewhere else) and log in again)

**Comment by markdlib** [comment]
> Try recreating your cookies (delete them (or move them somewhere else) and log in again)

just tried this (having the same issue) and it still doesn't work for me, not sure what else to do.

**Comment by ceoshikhar** [comment]
I think Twitch API has changed.

`https://api.twitch.tv/helix/users?login=streamer_login` is returning 404 instead of `streamer_login` details.

**Comment by DarkVypr** [comment]
> I think Twitch API has changed.
> 
> `https://api.twitch.tv/helix/users?login=streamer_login` is returning 404 instead of `streamer_login` details.

yea seems like the issue. guess we'll have to wait lol

> Try recreating your cookies (delete them (or move them somewhere else) and log in again)

did this to avail. looks like @ceoshikhar found the issue

**Comment by ceoshikhar** [comment]
The API being used is https://dev.twitch.tv/docs/api/reference#get-users and apparently its not working as expected.

**Comment by borzaka** [comment]
No related mentions about changes here: https://dev.twitch.tv/docs/change-log

**Comment by Tkd-Alex** [comment]
The Client-ID used by us doesn't work any more. 
I'll figure out If I'm able to find another Client-ID or we had to create by our-self

**Comment by Tkd-Alex** [comment]
Someone can test this?
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/288

**Comment by rrweller** [comment]
> Someone can test this? #288

This is working for me

**Comment by curv3ball** [comment]
Not sure what else to do, [#288 ](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/288) doesn't work for me so i'm not sure why it works for some others that have said so. If anyone knows what i can try, please let me know
