### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by Rezanans-wow** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#287]
**Describe the bug**
Unknown error

**To Reproduce**
1. Open script

**Expected behavior**
Yesterday me got some errors, but it not break script
Today i cant start script

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version 3.7

**Additional context**

**Comment by RakSrinaNa** [comment]
Duplicate of #281

**Comment by Rezanans-wow** [comment]
Ok
