### ISSUE TITLE
Error Pagination

### ISSUE THREAD

**Issue by Ak1n3** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#289]
Today all of a sudden this issue started happening, I tried reinstalling but it still didn't fix, If someone knows the solution plzz help
![Screenshot_20210929-203657_Termux 1](https://user-images.githubusercontent.com/91618934/135296607-e5f095bb-ffeb-499b-b060-9a1dd7b7f908.jpg)

**Comment by Dauriel** [comment]
Duplicate of #281

**Comment by Tkd-Alex** [comment]
yup, pagination was already removed with the GraphQL
Please test this: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/288

**Comment by Ak1n3** [comment]
I tried the #288 and now i'm getting this new error
![Screenshot_20210929-221251_Termux 1](https://user-images.githubusercontent.com/91618934/135312996-b3328327-9e46-4a9f-bd07-fc63b4fb89ae.jpg)

**Comment by Rafa-Alex** [comment]
I have the same problem

**Comment by init-andrea** [comment]
The same is happening to me. I am using the configuration #288 and getting the same 'NoneType' object is not subscriptable error.

**Comment by Tkd-Alex** [comment]
I've done another little fix to handle the `NoneType`.
Please test again https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/288/commits/5f6c75560e131f17c17f304444c62060e5acf982

**Comment by Dauriel** [comment]
Tested and working!

**Comment by Ak1n3** [comment]
its working now thanks
