### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by Oxtane** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#292]
keep getting this error idk what to do help?

 return int(self.get_cookie_value("persistent").split("%")[0])
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Matze1526** [comment]
I have the same Problem on two Unix-systems and Windows! 👍 :(

**Comment by matschik** [comment]
It worked perfectly until today, got the exact same bug.
I suppose Twitch changed something.

**Comment by Matze1526** [comment]
> 
> 
> Please test #288

WORKED Thanks 👍

**Comment by Oxtane** [comment]
> It worked perfectly until today, got the exact same bug. I suppose Twitch changed something.
> 
> ```shell
> 30/09/21 15:35:20 - INFO - [run]: 🤓  Loading data for 2 streamers. Please wait...
> 30/09/21 15:35:21 - INFO - [run]: 😢  Streamer xxx does not exist
> 30/09/21 15:35:22 - INFO - [run]: 😢  Streamer yyy does not exist
> 
> Traceback (most recent call last):
>   File "miner/run.py", line 65, in <module>
>     twitch_miner.mine(
>   File "miner/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 122, in mine
>     self.run(streamers=streamers, blacklist=blacklist, followers=followers)
>   File "miner/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 246, in run
>     user_id=self.twitch.twitch_login.get_user_id(),
>   File "miner/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 214, in get_user_id
>     return int(self.get_cookie_value("persistent").split("%")[0])
> AttributeError: 'NoneType' object has no attribute 'split'
> ```

if u fix lmk

**Comment by matschik** [comment]
You can fix it with the fix branch:
```
$ git checkout wout-helix-api
```
It works perfectly now ! :)

**Comment by Oxtane** [comment]
> You can fix it with the fix branch:
> 
> ```
> $ git checkout wout-helix-api
> ```
> 
> It works perfectly now ! :)

So wait i have it get the error then rype that?
