### ISSUE TITLE
Attribute error?

### ISSUE THREAD

**Issue by NotSafarad** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#293]
I just have to start it and i get this error. A re-download did nothing. it just statrted one day, before i only got weird 20 line errors sometimes, something about websocket error.

 - OS: Windows 10
 - Python version 3.9

![vlc_n06Vy2C6w3](https://user-images.githubusercontent.com/88512718/135502137-553d1932-3543-4aa8-b7a1-5065ae6083fe.png)

**Comment by RakSrinaNa** [comment]
`CTRL+C Detected....` The program has been stopped before it had the chance to initialize.

**Comment by NotSafarad** [comment]
![image](https://user-images.githubusercontent.com/88512718/135566911-61f1fb12-a850-4619-88d8-6a61d5f5b1c6.png)

**Comment by RakSrinaNa** [comment]
This is another issue. #288
