### ISSUE TITLE
 question about the number of followers  

### ISSUE THREAD

**Issue by Assaf21** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#294]
i have more than 100 followers  and i need to load more than 100 

can i ??  , if i can how 

![image](https://user-images.githubusercontent.com/91670636/135646583-2f3edc65-6733-4873-87ee-1ae86dd58806.png)

**Comment by Tkd-Alex** [comment]
Probably with the latest update we lost the ability to load more than 100 followers.
Someone knows a page on Twitch where It's possible to find all the followers?

**Comment by Assaf21** [comment]
that mean i cant load  more than 100 in the current time

**Comment by LordAsperheim** [comment]
> Probably with the latest update we lost the ability to load more than 100 followers. Someone knows a page on Twitch where It's possible to find all the followers?

This website "https://twitchinsights.net/followlist" show's all followers (i think), it's atleast over 100, i can confirm

**Comment by Sorrow81** [comment]
The offeset are limited to 100 channel :
![image](https://user-images.githubusercontent.com/43729314/135709716-91afaae4-77ba-4fc5-a6c3-4103613b5734.png)

The solution would be to make the first call on the first 100 items. Then look at the **_total** value to see if you should continue to query the next 100 items.

The solut
![image](https://user-images.githubusercontent.com/43729314/135709768-d36401db-9006-4193-ad91-0d98109a8cbb.png)

**Comment by Tkd-Alex** [comment]
> The offeset are limited to 100 channel : ![image](https://user-images.githubusercontent.com/43729314/135709716-91afaae4-77ba-4fc5-a6c3-4103613b5734.png)
> 
> The solution would be to make the first call on the first 100 items. Then look at the **_total** value to see if you should continue to query the next 100 items.
> 
> The solut ![image](https://user-images.githubusercontent.com/43729314/135709768-d36401db-9006-4193-ad91-0d98109a8cbb.png)

:thinking:  uhm here we don't use the `kraken api`

**Comment by Sorrow81** [comment]
Ah shame. With the twitchinsights client_id, I managed to get the users. By not forgetting to add the twitch api in the constant and replacing your client_id with theirs.

![image](https://user-images.githubusercontent.com/43729314/135712632-cab862b5-73f5-48d3-9267-c76b6c7816d4.png)

**Comment by Tkd-Alex** [comment]
PR are welcome ^^

**Comment by RakSrinaNa** [comment]
`while 1` woo...

Maybe a better approach to this would be something like:
```py
def get_followers(self, limit=100, offset=0):
    followers = {}
    json_response = <make query>
    followers += [<process response>]
    if <has next page (maybe can be when len(followers) == limit)>:
        followers += get_followers(limit, offset + limit)
    return followers
```

This way this is way more flexible as the `limit` can be changed, and doesn't have kinda "tricky" loops like `while 1`.

**Comment by Sorrow81** [comment]
It works. I try to do a PR during the day.

```python
    def __do_kraken_request(self, query, response_as_json=True):
        url = f"{API}/{query.strip('/')}"
        response = self.twitch_login.session.get(url)
        logger.debug(
            f"Query: {query}, Status code: {response.status_code}, Content: {response.json()}"
        )
        return response.json() if response_as_json is True else response

    def get_followers(self, limit=100, offset=0):
        followers = []
        query = f"/kraken/users/{self.twitch_login.get_user_id()}/follows/channels?limit={limit}&direction=asc&sortby=login&offset={offset}"
        json_response = self.__do_kraken_request(query)
        followers += [i["channel"]["name"] for i in json_response["follows"]]
        if len(followers) == limit:
            followers += self.get_followers(limit, offset + limit)
        return followers
```

![image](https://user-images.githubusercontent.com/43729314/135715844-ca89ff3c-d2ab-42b1-88ab-26bf31d1421b.png)

Users are sorted for those who are not personalised.

**Comment by Tkd-Alex** [comment]
> i have more than 100 followers and i need to load more than 100
> 
> can i ?? , if i can how
> 
> ![image](https://user-images.githubusercontent.com/91670636/135646583-2f3edc65-6733-4873-87ee-1ae86dd58806.png)

Have you any chance to test this PR #341 ?
