### ISSUE TITLE
Scrips just closes straight after opening it!

### ISSUE THREAD

**Issue by LordAsperheim** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#295]
**Describe the bug**
When i double-press the run.py it just opens a small tab, and shows some text very fast, and then closing it again.

**To Reproduce**
1. Go to the Twitch-Channel-Points_miner-v2
2. Open the run.py

**Expected behavior**
i expected it to just open as normal, and start mining, but it didn't

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version Python 3.9 

**Additional context**
i have added the Log that shows in the log folder when it opens and closes. I see some "ERROR" but i am not goot at these codings, so i don't understand the error! 
[lordasperheim.20211001-211408.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/7269656/lordasperheim.20211001-211408.log)

**Comment by RakSrinaNa** [comment]
Do not start it from a double clic. Use a terminal.

**Comment by LordAsperheim** [comment]
> Do not start it from a double clic. Use a terminal.
> 
> (see [Readme](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use))

I've tried creating a .bat file to start it, but i just get "python was not found run without arguments to install from the microsoft store" when i try running the .bat file

**Comment by RakSrinaNa** [comment]
At this point this isn't even linked to the repo.... just install python correctly, including the PATH variable.

You may have to use `python3` depending on how you installed it.

**Comment by LordAsperheim** [comment]
> At this point this isn't even linked to the repo.... just install python correctly, including the PATH variable.
> 
> You may have to use `python3` depending on how you installed it.

I just uninstalled python, and installed it again, but still the same thing

**Comment by RakSrinaNa** [comment]
https://docs.python.org/3/using/windows.html

**Comment by LordAsperheim** [comment]
> https://docs.python.org/3/using/windows.html

![image](https://user-images.githubusercontent.com/91757261/135686370-96a77669-d6b8-455d-bb56-165cf60fe668.png)
This is the "error" i get now when trying to open the run.py using a .bat file

**Comment by RakSrinaNa** [comment]
Read the readme (how to use)

**Comment by LordAsperheim** [comment]
> Read the readme (how to use). You're missing dependencies.

where am i supposed to do this? Just in my standard Python terminal?

**Comment by LordAsperheim** [comment]
> > Read the readme (how to use). You're missing dependencies.
> 
> where am i supposed to do this? Just in my standard Python terminal?

refering to the "pip install -r requirements.txt" from the dependencies

**Comment by RakSrinaNa** [comment]
In a terminal. CMD, powershell, pwsh,... Whatever, a terminal.

**Comment by LordAsperheim** [comment]
> In a terminal. CMD, powershell, pwsh,... Whatever, a terminal.

![image](https://user-images.githubusercontent.com/91757261/135687378-e86843dd-d337-4271-8713-37fec49a9473.png)

now this shows up in the .bat

**Comment by RakSrinaNa** [comment]
Either you did the improts wrong, or you run the script from the wrong working directory, or have an outdated version.

**Comment by LordAsperheim** [comment]
> Either you did the improts wrong, or you run the script from the wrong working directory, or have an outdated version.

I did a fresh install and now it works! thanks for all the help!
