### ISSUE TITLE
Error: Streamer does not exist

### ISSUE THREAD

**Issue by polat0almdar** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#301]
It was working fine with no issues at all but suddenly when I run the python code it doesn't work and says the streamer doesn't exist.

 - OS: Windows Server
 - Python version 3.9

**This is what is showing on the CMD:**

03/10/21 23:52:02 - INFO - [run]: Analytics running on http://127.0.0.1:5000/
03/10/21 23:52:02 - INFO - [run]: Start session: 'afb74630-7cc7-4683-a851-38fa9399c0b5'
03/10/21 23:52:02 - INFO - [run]: Loading data for 40 streamers. Please wait...
03/10/21 23:52:02 - INFO - [run]: Streamer ludwig does not exist
03/10/21 23:52:03 - INFO - [run]: Streamer baboabe does not exist
03/10/21 23:52:04 - INFO - [run]: Streamer lilypichu does not exist
03/10/21 23:52:04 - INFO - [run]: Streamer fuslie does not exist
03/10/21 23:52:05 - INFO - [run]: Streamer natsumiii does not exist
03/10/21 23:52:06 - INFO - [run]: Streamer scarra does not exist
03/10/21 23:52:06 - INFO - [run]: Streamer pokimane does not exist
03/10/21 23:52:07 - INFO - [run]: Streamer pestily does not exist
03/10/21 23:52:08 - INFO - [run]: Streamer itshafu does not exist
03/10/21 23:52:08 - INFO - [run]: Streamer itsryanhiga does not exist
03/10/21 23:52:09 - INFO - [run]: Streamer kristoferyee does not exist
03/10/21 23:52:09 - INFO - [run]: Streamer peterparktv does not exist
03/10/21 23:52:10 - INFO - [run]: Streamer kkatamina does not exist
03/10/21 23:52:11 - INFO - [run]: Streamer 5uppp does not exist
03/10/21 23:52:12 - INFO - [run]: Streamer ariasaki does not exist
03/10/21 23:52:12 - INFO - [run]: Streamer sykkuno does not exist
03/10/21 23:52:13 - INFO - [run]: Streamer moistcr1tikal does not exist
03/10/21 23:52:14 - INFO - [run]: Streamer dakotaz does not exist
03/10/21 23:52:15 - INFO - [run]: Streamer brofain does not exist
03/10/21 23:52:16 - INFO - [run]: Streamer hjune does not exist
03/10/21 23:52:16 - INFO - [run]: Streamer xchocobars does not exist
03/10/21 23:52:17 - INFO - [run]: Streamer glorious_e does not exist
03/10/21 23:52:17 - INFO - [run]: Streamer tinakitten does not exist

**Comment by RakSrinaNa** [comment]
Get the latest version. #281
