### ISSUE TITLE
😳Predictions aren't working for me after i cleared cookies 😥.

### ISSUE THREAD

**Issue by villait** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#308]
😳Predictions aren't working for me after i cleared cookies and updated some files 😥.
deleted me.pkl and updated the files and got this

06/10 15:53:20 - Exception raised for topic: predictions-channel-v1 and message: {'type': 'event-created', 'data': {'timestamp': '2021-10-06T14:53:19.213828274Z', 'event': {'id': '799196ae-775d-4faf-bb28-83102aabcbd5', 'channel_id': '57292293', 'created_at': '2021-10-06T14:53:19.197957387Z', 'created_by': {'type': 'USER', 'user_id': '57292293', 'user_display_name': 'RATIRL', 'extension_client_id': None}, 'ended_at': None, 'ended_by': None, 'locked_at': None, 'locked_by': None, 'outcomes': [{'id': 'e52f3534-ddd7-47c8-a87a-fdef3bee256a', 'color': 'BLUE', 'title': 'win', 'total_points': 0, 'total_users': 0, 'top_predictors': [], 'badge': {'version': 'blue-1', 'set_id': 'predictions'}}, {'id': 'e13be7c1-082e-4c2b-a2f5-8a1a0cfc8e57', 'color': 'PINK', 'title': 'lose', 'total_points': 0, 'total_users': 0, 'top_predictors': [], 'badge': {'version': 'pink-2', 'set_id': 'predictions'}}], 'prediction_window_seconds': 60, 'status': 'ACTIVE', 'title': 'win or lose', 'winning_outcome_id': None}}}
Traceback (most recent call last):
  File "D:\ChannelMiner\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 249, in on_message
    prediction_window_seconds = ws.streamers[
AttributeError: 'Streamer' object has no attribute 'get_prediction_window'

**Comment by Tkd-Alex** [comment]
@villait solved?
