### ISSUE TITLE
importing cookies from files and not from the browser.

### ISSUE THREAD

**Issue by wollframium** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#319]
I worked hard to make your software work, installed a bunch of libraries and tried a bunch of configs, but when I ran the database, I generated a bunch of "py" files, I realized that I could not generate cookies because it is somehow encrypted.
make an add-on so that you can import cookies from txt. it would be convenient and you don't need to start the browser at all then ...

**Comment by wollframium** [comment]
> You mean browser addon?

нет я имею в виду, cookie-botname.txt превращать в botname.pkl что бы не нужно было запускать браузер, у меня 100+ аков, и каждым авторизироваться в браузере, так себе идея, файлы запуска я легко на генерировал BASом, но файл куков я не могу нагенерировать потому что там какаято дич зашифрованная. 
`Ђ•љ      ]”(}”(Њname”Њ	api_token”Њvalue”Њ e815`

**Comment by 1v** [comment]
В этом зашифрованном файле `user.pkl` вот эти данные:
```
[
    {"name": "api_token", "value": "..."},
    {"name": "bits_sudo", "value": "..."},
    {"name": "last_login", "value": "..."},
    {"name": "login", "value": "..."},
    {"name": "name", "value": "..."},
    {"name": "persistent", "value": "..."},
    {"name": "spare_key", "value": "..."},
    {"name": "sudo", "value": "..."},
    {"name": "auth-token", "value": "..."},
]
```
Если у тебя есть эти данные то ты можешь их зашифровать вот так 
```
pickle.dump([{'name': 'api_token',...], open("bot1.pkl", "wb"))
```

**Comment by Tkd-Alex** [comment]
@wollframium can we close? It's solved?
