### ISSUE TITLE
Running on ARM8 / Raspberry Pi 3

### ISSUE THREAD

**Issue by anoviel** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#32]
Dear channel points miners,
i am kind of hooked by this project, because it works very well on my desktop machine for several hours.
So i decided to launch it on my raspberry pi 3 b+ model.

But there are some challenges to make it work.
First of all, when you are using Raspbian, your latest available firefox-esr version will be 52.9.0
Check it out using `firefox-esr -version`
That means you have to use geckodriver v0.18.0 ( thanks to MJ Richardson on [stackoverflow](https://stackoverflow.com/questions/52684900/selenium-webdriverexception-connection-refused-occuring-on-headless-pi))

I didn't change my selenium version: 3.141.0
I update my python to verion: 3.9.1

To fix the geckodriver error `Error: GDK_BACKEND does not match available displays` i had to add 3 lines of code into the TwitchBrowser class and remove `self.browser.set_window_size(450, 800)` call, because of an `WebDriverException: Message: setWindowRect` exception.

`from pyvirtualdisplay import Display`

```
def init(self):
        display = Display(visible=0, size=(450, 800)) # initialize a virtual display
        display.start()
       # ...
        if self.browser is not None:
            # self.browser.set_window_size(450, 800)
            self.browser.implicitly_wait(self.settings.implicitly_wait)
       # ...
```

The twitch channel points miner starts now as expected, but it can't find DOM Elements for placing a bet.

Claiming channelpints by watching seems to work fine.

Maybe because I removed the window size?
Did someone else got this program running on a raspberry pi with all of it's funtions?

**Comment by RakSrinaNa** [comment]
I got it running on a raspberry 3B+ too without any problem. Though I'm using chrome webdriver instead of firefox.

**Comment by Tkd-Alex** [comment]
I run the miner on Raspberry Pi4 without any problems too. 24h/24h Manjaro and Firefox. Please save the screenshots so we can If It's a problem related with window size or something else

**Comment by Tkd-Alex** [comment]
It's also possible that you need to disabled the headless mode while you are using a virtual display. 

Test with BrowserSettings.show = False

**Comment by anoviel** [comment]
I reverted my virtual display changes to be as close as possible to this repository.
Running chromium-browser, chromium-chromedriver and chromium-codecs-ffmpeg in version 86.0.4240.198.
Miner is running right now. 
I will wait until i catch a PREDICTION / WATCH / STREAK / RAID / wait for streamer event
I will close this issue, when everything works fine. 
Thanks for your help so far!

**Comment by Tkd-Alex** [comment]
Fun-fact: I'm unable to start my project on Raspberry with Chrome :laughing:

**Comment by anoviel** [comment]
- [x]  WATCH
- [x] CLAIM
- [x] WATCH_STREAM
- [x] PREDICTION
- [x] RAID
- [ ] GOING LIVE

Everything works fine! Awesome.
For future purpose:
I use the following binaries from [here](https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/20285965)
- [chromium-browser](https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/20285965/+files/chromium-browser_86.0.4240.198-0ubuntu0.16.04.1_armhf.deb)
- [chromium-chromedriver](https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/20285965/+files/chromium-chromedriver_86.0.4240.198-0ubuntu0.16.04.1_armhf.deb)
- [chromium-codecs-ffmpeg](https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/20285965/+files/chromium-codecs-ffmpeg_86.0.4240.198-0ubuntu0.16.04.1_armhf.deb)
- [chromium-codecs-ffmpeg-extra](https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/20285965/+files/chromium-codecs-ffmpeg-extra_86.0.4240.198-0ubuntu0.16.04.1_armhf.deb)
