### ISSUE TITLE
error on login to twitch account

### ISSUE THREAD

**Issue by mohammadmehri94** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#323]
The bot works fine with one of my accounts bot on the other one I get this error:
error from callback <function WebSocketsPool.on_message at 0x7fcf4db7eb80>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': '6cJyPh9uIvr0I1BP5vaq4VS5BbJ86g'}

**Desktop (please complete the following information):**
 - OS: [linux/ubuntu]
 - Python version [3.7]

**Comment by javifdeezg** [comment]
same error for me, literally I cant open it even the first time

**Comment by Tkd-Alex** [comment]
Make sure to have the latest version :)
