### ISSUE TITLE
No module named 'browser_cookie3' - Termux

### ISSUE THREAD

**Issue by ghost** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#329]
when i enter the command `pip install browser_cookie3`

the installation process occurs, then it takes a long time with various errors installing cryptography-x.x.x

when the installation finishes and I run python run.py it asks me to install 'browser_cookie3' again

I have tried installing `pkg install rust` but I still have the same problem.
any solution?

thanks

**Comment by Tkd-Alex** [comment]
@SmokoGuwap solved?

**Comment by Mejkiz** [comment]
Hello, I can't solve the same problem. Here are the screenshots
![Screenshot_2022-01-01-12-02-13-635_com termux](https://user-images.githubusercontent.com/57387122/147843717-4d69671e-093d-49a6-9c22-74ea0ba66b57.jpg)
![Screenshot_2022-01-01-12-02-20-031_com termux](https://user-images.githubusercontent.com/57387122/147843719-874a1d0d-bd1d-4d15-9cd5-437daf7aade9.jpg)
![Screenshot_2022-01-01-12-02-25-050_com termux](https://user-images.githubusercontent.com/57387122/147843721-1afb06b6-5e84-4a6f-a960-3ccdc9be640c.jpg)
![Screenshot_2022-01-01-12-02-30-413_com termux](https://user-images.githubusercontent.com/57387122/147843722-bc046ece-c5ee-4483-a9fa-1cdda4c86a22.jpg)
![Screenshot_2022-01-01-12-02-34-757_com termux](https://user-images.githubusercontent.com/57387122/147843724-23ff3264-8020-4154-8210-05e2086957c3.jpg)
![Screenshot_2022-01-01-12-02-39-120_com termux](https://user-images.githubusercontent.com/57387122/147843725-2fa2a05d-15d8-4fbc-bdf2-a36a9422b6b7.jpg)

**Comment by iPaff367gg** [comment]
solved?

**Comment by Mejkiz** [comment]
> решено

No

**Comment by iPaff367gg** [comment]
> 

Nice...

**Comment by tOFuWuerstchen** [comment]
for me worked these 3 steps after the same error

pip Install rust
export CARGO_BUILD_TARGET=aarch64-linux-android 
pip install cryptography

**Comment by Bigpower2012** [comment]
refer to this https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory , usually just an error for windows/your system rather than project error.
