### ISSUE TITLE
Predictions: 'Stealth Mode' betting

### ISSUE THREAD

**Issue by testdev123456** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#33]
Would be nice to have:

An **option to bet 1 point less than the current highest bet**.  I'll explain:

The prediction box, shows the username of the highest bet from OptionA and OptionB.  So, in a small channel, where sometimes everyone knows each other.. If we show up as the highest bet all the time... and don't even talk.. we would raise suspicion. Plus, since we don't show up in the user-list..  they would freak out even more..!

So my suggestion is..  that at the moment we're about to place our bet to Option2 for example....  check the amount of the highest bet from Option2 and place the bet just 1 point less of it.. and continue to be 'hidden' from chat.  

Of course, that value will continue to obey and be within:  `bet_settings=BetSettings(percentage=5,max_points=50000)`
if it's an option in run.py .. .we could call it `stealth_mode=True`

;o)

_Originally posted by @testdev123456 in https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/29#issuecomment-770383961_

**Comment by Tkd-Alex** [comment]
If you want you can this feature on this branch :smile: 
This will help us to release very soon on master
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/betting-improvement

**Comment by testdev123456** [comment]
> If you want you can try this feature on this branch 
> This will help us to release very soon on master
> https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/betting-improvement

I'm on it.. will report back!

**Comment by testdev123456** [comment]
I can't see `stealth_mode` in run.py for this branch

should I add it manually?

**Comment by testdev123456** [comment]
closed it by mistake..  again, 

I can't see stealth_mode in run.py for this branch

should I add it manually?

**Comment by Tkd-Alex** [comment]
Yup, I forgot to add in the example file.
But you should be able to see the README.md with all settings explained

**Comment by testdev123456** [comment]
got it. running it now..  i'll report back

**Comment by testdev123456** [comment]
so far I haven't experienced a prediction.. but for some reason the script is running soooo delayed..   no errors, but  I have 10 live streamers and there are 'gaps' of  no script activity at all  for like 15-20 minutes.. so strange.     the main branch doesn't behave like this.    I've restarted the script twice and same issue..   
I'll keep checking if this continues..
