### ISSUE TITLE
Betting strategy: Smart money

### ISSUE THREAD

**Issue by chrswt** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#331]
Allow a betting strategy that follows the side with the largest individual bet placed

**Comment by Tkd-Alex** [comment]
Can you explain better?

**Comment by chrswt** [comment]
When a prediction is live, Twitch shows the following information: total amount placed on each side (giving the odds), number of bettors on each side, and the largest bet placed on each side. The largest bet placed on each side can usually give a clue as to where the smart money is betting on because the people with the most channel points have usually watched the channel for the longest amount of time (have the most knowledge) and/or have won the most bets (are good at predictions). This strategy would bet on the side that has the largest individual bet placed.

**Comment by Tkd-Alex** [comment]
Are you sure that this strategy doesn't already exist? https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#bet-strategy

**Comment by chrswt** [comment]
It's not MOST_VOTED or LEAST_VOTED because that is determined by the majority, not where the largest bet is placed.
It is not PERCENTAGE because that is determined by the odds, not where the largest bet is placed.
It is not SMART because that is determined by the majority, not where the largest bet is placed.

As far as I can tell, this strategy does not already exist. The strategy is using the information provided in the 4th row, the largest bet, and seeing which side the largest bet is placed on.

**Comment by RakSrinaNa** [comment]
In a more "technical way", what is being mentioned here to is basically to take the outcome which has the max value in the field `event.outcomes[].top_predictors[].points` of an eventCreated/Updated ws message.

**Comment by Tkd-Alex** [comment]
@chrswt have you the time to test smart-money branch?
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/smart-money

**Comment by chrswt** [comment]
Let me test it out over the next couple of days, tried today but there were no predictions running

**Comment by chrswt** [comment]
@Tkd-Alex As far as I can tell this works perfectly after having tested it the last couple of days, thank you so much! Feel free to merge into the main branch.
