### ISSUE TITLE
Add requirements to tutorial before 'Building wheels for pillow'

### ISSUE THREAD

**Issue by ssoaora** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#334]
**Describe the bug**
On Ubuntu 20.04LTS if a user installs the requirements, during 'Building wheel for pillow' shows a error message because it needs prerequisites.
I added a command how to add the prerequisites below.
Please add it to the tutorial.

**To Reproduce**
1. Go to :  ~/Twitch-Channel-Points-Miner-v2/
2. Run: pip install -r requirements.txt
3. See error

**Expected behavior**
If you run the command I added, users will have no error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Python version 3.8.10

**Additional context**
command:
```
sudo apt-get install libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
    libharfbuzz-dev libfribidi-dev libxcb1-dev
```

**Comment by RakSrinaNa** [comment]
Maybe it's better putting a warning stating that other dependencies may be required and that people have to check these vendors what are the installation steps.
This isn't really the responsibility of this package to provide installation steps of 3rd parties and these required libs may change anytime and may have different packages required depending on the architecture.
