### ISSUE TITLE
Use GQL API to list follows

### ISSUE THREAD

**Issue by RakSrinaNa** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#339]
**Is your feature request related to a problem? Please describe.**

This relates to #294 where not all follows are listed.
#296 was opened to fix this but uses a deprecated API that'll eventually be terminated.

While I worked on my version of the project I found that it is possible to find the wanted info through the GQL API. This would be nice to do so as it drops the need of yet another API and getting data is achieved through an already used API instead (just need a new query).

**Describe the solution you'd like**

The operation is named `ChannelFollows`.

Here's how I did it. There's tests where you can see examples of a query as well as some example responses. https://github.com/RakSrinaNa/ChannelPointsMiner/pull/63/commits/08c929ea3aab0797e95f4d2ea31bd5cc07f3749f

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Tkd-Alex** [comment]
<3
