### ISSUE TITLE
Drop collection on start-up not working

### ISSUE THREAD

**Issue by SiIason** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#34]
Started collecting a timed viewing drop tonight (no script was watching manual) without noticing they activated again.
When I started the script to see if it would collect the reward, it didn't.

Not sure what helpful info to include for this one as nothing happened. https://prnt.sc/xxrhqx

**Comment by SiIason** [comment]
An hour later and the script didn't collect the 2nd reward.

It appears to generate the rewards but not collect them currently.

**Comment by Tkd-Alex** [comment]
Strange, I've tested in the same way. Watched manually and claimer on startup by the script and worked for me.

I need the logs file with level `DEBUG` for understanding what's not worked

**Comment by SiIason** [comment]
[01022021-090027.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/5903074/01022021-090027.log)

**Comment by Tkd-Alex** [comment]
Can I also see your run.py file please? Are you on the latest commit? Seems that we are missing a lot of data 😔😔

**Comment by SiIason** [comment]
I deleted the first few lines that happen at start-up as they contained my account name and wasn't sure what else was included.
I re pulled the repo last night and that information now isn't included in the debug log, but removed the first few lines just in case.

As far as Im aware Im running the default run.py with a username/streamer added, but will recreate from latest pull and run again.

**Comment by Tkd-Alex** [comment]
Claim drops on start-up is False by default

**Comment by Tkd-Alex** [comment]
Default settings have claim drops disabled

**Comment by SiIason** [comment]
My most humblest apologies, I wasn't using the the latest run.py :(
I will be sitting in the furthest corner of the room for the rest of the day.
