### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Classic298** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#342]
**Describe the bug**
When starting my selfmade run.py, a SyntaxError of the TwitchChannelPointsMiner.py stops the mining IMMEDIATELY after starting it.

**To Reproduce**
1. create your own run.py
2. start it

**Expected behavior**
it works

**Desktop (please complete the following information):**
 - OS: RaspbianOS / Debian
 - Python 3.9

**Additional context**
```
pi@raspberrypi:~/Twitch-Channel-Points-Miner-v2$ python3 run.py
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 120
    logger.info(f"You are running the version {current_version} of this script")
                                                                              ^
SyntaxError: invalid syntax
pi@raspberrypi:~/Twitch-Channel-Points-Miner-v2$ 
```

**Comment by Tkd-Alex** [comment]
Are you sure that is the 3.9 version of Python? 🤔

**Comment by Classic298** [comment]
> Are you sure that is the 3.9 version of Python? 🤔

Yeeeeeeeeaaaah
About that

Just checked it
python3 starts python 3.5 for some reason
If i start it with "python3.9 run.py" it works!

My bad.
