### ISSUE TITLE
Multiple account w10

### ISSUE THREAD

**Issue by artu1231** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#346]
Hi, sorry for creating this topic, but i couldn´t find the solution anywhere in the github.

How do i log in multiple accounts when console login is unavaiable (twitch captcha from logging into different browsers)? If i log in 1 account and set the miner, when i log out, the miner stops.

I found this saying from Tkd-Alex

"As I already say you don't need to have multiple browser

All of your accounts seems to be had a captcha problem
You can always log out from the browser and use It for login with another user"

I tried also to use chrome's profiles and it didnt work.

Is there a solution? 

os windows10
python 3.9

Thank you very much.

**Comment by Tkd-Alex** [comment]
You can try instead of logout on your account to log in with the new user to cancel the cookies.
![image](https://user-images.githubusercontent.com/14061593/142623539-a6e07365-61e3-459d-b6c0-3c5f1ce34c5e.png)

**Comment by artu1231** [comment]
It worked! 

Thank you very much Alex <3 

Please put this information in the readme because i added an user from this github and he a lso had this problem.
