### ISSUE TITLE
Help me for telegram

### ISSUE THREAD

**Issue by turpez** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#353]
Hello I can't set up to have notifications on telegram can you please help me ?

**Comment by simonk83** [comment]
Are you using the Telegram branch? It's not included in master.

**Comment by turpez** [comment]
> 

I tried to install with this but it doesn't work

**Comment by simonk83** [comment]
When you clone colin's repo with these changes, make sure you get the correct branch with:

git clone -b tg https://github.com/ColinShark/Twitch-Channel-Points-Miner-v2.git

The changes are in that "tg" branch. After you pull this down, add your stuff to the run.py file as usual and go through the steps to create the Telegram bot. I just tested it and it worked, but I initially stuffed up and only cloned the master branch. After getting the tg branch it seems fine
