### ISSUE TITLE
LZ4 error (Build tools) 

### ISSUE THREAD

**Issue by MicroWazzle** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#355]
So i'm getting a lz4 error and it's telling me to install build tools but which ones i don't know can anyone tell me what tools I need?

**Comment by RuDUSKII** [comment]
You need to install lz4 or install the Microsoft build tools depending on what os you are using. [](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

**Comment by xBlackZero** [comment]
same issue here, I downloaded and installed build tools and nothing, why this s*îtty program has to be so complicated to install? I really miss the version 1.0 u.u

**Comment by RuDUSKII** [comment]
Did you install the right tools? 
![image](https://user-images.githubusercontent.com/88993603/145142135-73cab70c-dec4-478c-80b2-164712a47172.png)
Also, upgrade your pip and setuptools.
python -m pip install --upgrade pip
pip install --upgrade setuptools
This all worked for me.

**Comment by xBlackZero** [comment]
Thanks, finally made it to work, it's still bad that a month ago I didn't need to do this, now my small vps has 6.86 GB less space cuz of this bloated tools that i'll never use again :D

**Comment by MicroWazzle** [comment]
> Did you install the right tools? ![image](https://user-images.githubusercontent.com/88993603/145142135-73cab70c-dec4-478c-80b2-164712a47172.png) Also, upgrade your pip and setuptools. python -m pip install --upgrade pip pip install --upgrade setuptools This all worked for me.

This has fixed it.
