### ISSUE TITLE
json.decoder.JSONDecodeError on [on_message] 

### ISSUE THREAD

**Issue by KillaBoi** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#358]
**Describe the bug**
For some reason, these errors have started to appear recently and I am not sure as to what is causing them. I have tried a fresh install of the bot and of python as well and they seem to persist after that as well...

**To Reproduce**
1. Run bot
2. Let streamers load
3. After loading, you will get the exception error "11/12/21 00:01:00 - ERROR - [on_message]: Exception raised for topic: community-points-user-v1" 
![image](https://user-images.githubusercontent.com/46409262/145655872-4a575c02-a673-44c3-b8f2-388e5bb1d02c.png)
4. See error, it will spam every few minutes

**Expected behavior**
Error shouldn't be spammed

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version 3.9.7 and 3.9.9

**Additional context**
N/A

**Comment by KillaBoi** [comment]
I've also noticed that a letter of the IRC usernames are missing but the channel names are correct, not sure as to why it's like this:

![image](https://user-images.githubusercontent.com/46409262/145655845-fb58ecd0-9b7c-4e9e-aaa0-aa5136c259af.png)

**Comment by Tkd-Alex** [comment]
Analytics JSON file corrupted.
Try to fix by yourself or just delete the file and start the script again

**Comment by KillaBoi** [comment]
That worked perfectly, thanks.
I assume it was because it was insanely large and somehow it just corrupted itself plus the browser itself was lagging tremendously when I was browsing the graphs as well...

Thanks for the help, I'm closing this issue :)
