### ISSUE TITLE
[Windows] Run.py won't run

### ISSUE THREAD

**Issue by Thlybs** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#367]
**Describe the bug**
When I try to run run.py, I get this error : 
"
File "C:\Users\thiba\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\AnalyticsServer.py", line 6, in <module>
    from flask import Flask, Response, cli, render_template
ModuleNotFoundError: No module named 'flask'
"
Then it won't run the script. What did I do wrong please ? I don't think I've got any issue during the pip install of my requirements.

**Desktop:**
 - OS: Windows
 - Python version 3.10.1

**Comment by Tkd-Alex** [comment]
`pip install -r requirements`

**Comment by quasar09** [comment]
yeah I literally did pip install -r requirements 
i also don't know what you mean whenever you say "open it from terminal" or whatever

**Comment by Yishaqel** [comment]
You need a minimum of knowledge to run this, if you have no idea what the terminal is you might want to consider quitting. You can have a look at the installation guide and if you can't get it to work, try to show us the errors it is causing you...
