### ISSUE TITLE
Messages file

### ISSUE THREAD

**Issue by Jarsa132** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#37]
I would like to see an file with all messages so we can customize them.

**Comment by Tkd-Alex** [comment]
> I would like to see an file with all messages so we can customize them.
> 

Which messages?

**Comment by Jarsa132** [comment]
Info logs
For example i want to change "streamer_name is online" to "streamer_name - live" and if i want to do that i need to change it in miner's files and sometimes i can't find some of them

**Comment by Tkd-Alex** [comment]
I don't think I will work on this feature.
I don't understand how this can improve the script.

**Comment by testdev123456** [comment]
let's close this..
