### ISSUE TITLE
 Farming only on one channel

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#375]
![image](https://user-images.githubusercontent.com/78689718/147825682-6ecfce64-5255-47f7-bbae-319277b44f3b.png)
Throughout the entire time, there were 3 or more channels online, but he was farming all the time on one. This was not the case in previous versions.

**Comment by YaZanuda111111** [comment]
Channel "welov..." was online all the time

**Comment by YaZanuda111111** [comment]
```
twitch_miner.mine(
    [
        "yanu....",
        "arhip...."
    ],
    followers=True
)
```

**Comment by Tkd-Alex** [comment]
#252 ?
