### ISSUE TITLE
Dont work bug

### ISSUE THREAD

**Issue by Hyp9x-afk** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#376]
i install browser_cookie3
https://prnt.sc/25r9gpz

**Comment by Tkd-Alex** [comment]
Probably you have installed `browser_cookie3` with another version of python.
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#by-cloning-the-repository

You can try to create a virtualenv or use the pip version / or docker

**Comment by Hyp9x-afk** [comment]
did not help

**Comment by Tkd-Alex** [comment]
> did not help

It's a problem related to your PC configuration
