### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by BazZziliuS** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#380]
When I write "pip install -r requirements.txt" an error pops up

**To Reproduce**
cd C:\Users\User\Documents\Twitch-Channel-Points-Miner-v2
pip install -r requirements.txt
![image](https://user-images.githubusercontent.com/18011884/147996700-3430a0c2-2aa7-4420-bc27-97e81abf02e8.png)
Full log https://pastebin.com/UyKx4HeQ

**Expected behavior**
It will be installed

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 (2009 build 19043)
 - Python: Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37)

**Comment by mkmephistopheles** [comment]
So... what did you do to solve it?
