### ISSUE TITLE
StreamElements Logs

### ISSUE THREAD

**Issue by bttfw** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#387]
Id what be nice for the miner to log if he is watching a streamelements Streamer like every 5 to 10 minutes 

for example

11/01 01:43:12 - 🚀  +10 → lululuvely (159.1k points) - Reason: WATCH.
11/01 01:43:12 - 🚀  Streamelements → Kobi - Reason: WATCHING.

**Comment by Tkd-Alex** [comment]
StreamElements It's not currently 100% supported. 
We just join in IRC Chat, nothing else

**Comment by bttfw** [comment]
Yeah i figured as much but it would nice to know if its watching the streamer or not

**Comment by byaura** [comment]
It's useless it works like a charm, no need to log that since it would take more resources for a useless log.
