### ISSUE TITLE
Reconnecting to Twitch PubSub server in ~60 seconds

### ISSUE THREAD

**Issue by jzhang9632** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#390]
**Describe the bug**
#0 - Reconnecting to Twitch PubSub server in ~60 seconds using VPN
[Errno 60] Operation timed out

**To Reproduce**
1. use VPN and run "python run.py"

**Expected behavior**
it works

**Desktop (please complete the following information):**
 - OS: Macos 11.2.1
 - Python version 3.8.3;

**Additional context**
 🥳  Streamer(username=xxx, channel_id=xxx, channel_points=320) is Online!
11/01/22 23:43:56 - ERROR - [on_error]: #0 - WebSocket error: [Errno 60] Operation timed out
11/01/22 23:43:56 - INFO - [on_close]: #0 - WebSocket closed
11/01/22 23:43:56 - INFO - [handle_reconnection]: #0 - Reconnecting to Twitch PubSub server in ~60 seconds
11/01/22 23:45:42 - ERROR - [on_error]: #0 - WebSocket error: [Errno 60] Operation timed out
11/01/22 23:45:42 - INFO - [on_close]: #0 - WebSocket closed
11/01/22 23:45:42 - INFO - [handle_reconnection]: #0 - Reconnecting to Twitch PubSub server in ~60 seconds
11/01/22 23:47:28 - ERROR - [on_error]: #0 - WebSocket error: [Errno 60] Operation timed out
11/01/22 23:47:28 - INFO - [on_close]: #0 - WebSocket closed

**Comment by Ryanevans94** [comment]
I get this on Windows 10, Python 3.9 keeps losing connection and will reconnect every couple minutes
