### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BarboPT** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#392]
--> python3 -m poetry add Twitch-Channel-Points-Miner-v2
Using version ^2.0.7 for Twitch-Channel-Points-Miner-v2

Updating dependencies
Resolving dependencies...

  SolverProblemError

  Because no versions of twitch-channel-points-miner-v2 match >2.0.7,<3.0.0
   and twitch-channel-points-miner-v2 (2.0.7) depends on irc (19.0.1), twitch-channel-points-miner-v2 (>=2.0.7,<3.0.0) requires irc (19.0.1).
  So, because repl-python3-bot depends on both irc (^20.0.0) and Twitch-Channel-Points-Miner-v2 (^2.0.7), version solving failed.

  at /opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)

error on packages (replit) @Tkd-Alex

**Comment by Tkd-Alex** [comment]
Probably this script won't run on `replit`, sorry

**Comment by BarboPT** [comment]
all run with pip and with dependency no

**Comment by BarboPT** [comment]
the script run with the pip install Twitch-Channel-Points-Miner-v2 but with the package dont work xD
