### ISSUE TITLE
[Windows]

### ISSUE THREAD

**Issue by Charlyma24** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#401]
I try to run and always receive the same errors:

Traceback (most recent call last):
  File "C:\Users\Carlos Lopez\Twitch-Channel-Points-Miner-v2\charlyma.py", line 5, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "C:\Users\Carlos Lopez\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "C:\Users\Carlos Lopez\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 14, in <module>
    from TwitchChannelPointsMiner.classes.AnalyticsServer import AnalyticsServer
  File "C:\Users\Carlos Lopez\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\AnalyticsServer.py", line 6, in <module>
    from flask import Flask, Response, cli, render_template
ModuleNotFoundError: No module named 'flask'

Any comment?

**Comment by Tkd-Alex** [comment]
`pip install flask`

**Comment by Charlyma24** [comment]
> 
Thank you for the reply, I run that. But Still receive the same answer.

**Comment by Charlyma24** [comment]
Running what you recommend this is the outcome

$ pip install flask
Requirement already satisfied: flask in c:\users\carlos lopez\appdata\local\programs\python\python310\lib\site-packages (2.0.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\carlos lopez\appdata\local\programs\python\python310\lib\site-packages (from flask) (2.0.1)
Requirement already satisfied: click>=7.1.2 in c:\users\carlos lopez\appdata\local\programs\python\python310\lib\site-packages (from flask) (8.0.3)
Requirement already satisfied: Werkzeug>=2.0 in c:\users\carlos lopez\appdata\local\programs\python\python310\lib\site-packages (from flask) (2.0.2)
Requirement already satisfied: Jinja2>=3.0 in c:\users\carlos lopez\appdata\local\programs\python\python310\lib\site-packages (from flask) (3.0.3)
Requirement already satisfied: colorama in c:\users\carlos lopez\appdata\local\programs\python\python310\lib\site-packages (from click>=7.1.2->flask) (0.4.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\carlos lopez\appdata\local\programs\python\python310\lib\site-packages (from Jinja2>=3.0->flask) (2.0.1)

**Comment by Charlyma24** [comment]
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/384

@boryyy

**Comment by Boryyy** [comment]
why do u need flask on windows? or ur trying repl?

**Comment by Boryyy** [comment]
when u see this error ModuleNotFoundError: No module named 'flask'

always do pip and the module name , in this case

`pip install flask`

**Comment by Charlyma24** [comment]
That was the last module that need. It's working! Thanks man!
