### ISSUE TITLE
Failed to find Chrome cookie 

### ISSUE THREAD

**Issue by markdlib** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#402]
**Describe the bug**
When I run the program it says that it could not find chrome cookie. Tried to log out and log in again on chrome, have deleted the cookie in the files, have tried firefox (which ran, but failed to find any streamer and did not record cookie (I assume it failed to grab cookie too). Not exactly sure what to do. Reinstalled requirements multiple times as well.

**Comment by markdlib** [comment]
So, it turns out that google recently(?) changed the file location for cookies (at least for windows). It is no longer found under default only, but inside another folder called network. The code was therefore unable to find the cookie as the file did not exist where expected. I assume that the app will need to be updated for that.

**Comment by markdlib** [comment]
if anyone wants a quick fix, simply make a copy of their cookies file under C:\Users\username\AppData\Local\Google\Chrome\User Data\Default\Network 
and paste it in the default folder (C:\Users\username\AppData\Local\Google\Chrome\User Data\Default). 
Then, simply launch the app again and it will work.

**Comment by nxrner** [comment]
I also ran into this problem, thank you

**Comment by rdavydov** [comment]
> The code was therefore unable to find the cookie as the file did not exist where expected. I assume that the app will need to be updated for that.

The app uses a python module called "browser_cookie3" for the cookie extraction process. There is [an open PR](https://github.com/borisbabic/browser_cookie3/pull/105) regarding the cookies path change. I guess we have to wait for this PR to be merged.
