### ISSUE TITLE
I need setup help

### ISSUE THREAD

**Issue by HarryBaalsZack** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#404]
Simply put, I'm a dumbass. I've watched videos, checked issues, guides, etc but I just can't get Run.py to run. I've seen in comment sections that a lot of people have had the same issue. Bug? Maybe. Me and many others being an idiot? Probably. Don't really know how GitHub works but if you would like to help me you can contact me on Discord @ MemeManXTreme#4545

**Comment by Tkd-Alex** [comment]
What's the issue? What have you tried?

**Comment by HarryBaalsZack** [comment]
> What's the issue? What have you tried?

I've tried everything I found online. When I run Run.py it just crashes. I've seen fixes but they don't work. I probably messed something really important up somewhere but I'm not very good with these types of things

**Comment by Tkd-Alex** [comment]
Pasta the crash error :)
Screen, text, video, something

**Comment by HarryBaalsZack** [comment]
> Paste the crash error :) Screen, text, video, something
It runs, doesn't do anything at all, no text or anything, and then closes. I don't know how to get to the crash error

**Comment by Tkd-Alex** [comment]
Are you on Windows? Launch the script via powershell

**Comment by HarryBaalsZack** [comment]
> Are you on Windows? Launch the script via powershell

Tried it, same thing

**Comment by Yishaqel** [comment]
To start and see the errors it is causing you should not double click on the file, you must run it from the command console "python example.py".

**Comment by HarryBaalsZack** [comment]
> To start and see the errors it is causing you should not double click on the file, you must run it from the command console "python example.py".

Made it work, thanks a lot both of you!
