### ISSUE TITLE
irc

### ISSUE THREAD

**Issue by BarboPT** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#405]
@Tkd-Alex  are possible update irc?because i tried use keep_alive and dont working with my uptimerobot

**Comment by BarboPT** [comment]
Using version ^0.2.1 for websocket
Using version ^0.13.0 for browser-cookie3
Using version ^0.4.4 for colorama
Using version ^1.6.3 for emoji
Using version ^2.0.2 for Flask
Using version ^20.0.0 for irc
Using version ^0.1.1 for millify

Updating dependencies
Resolving dependencies...

  SolverProblemError

  Because twitch-channel-points-miner-v2 (2.0.7) depends on irc (19.0.1)
   and no versions of twitch-channel-points-miner-v2 match >2.0.7,<3.0.0, Twitch-Channel-Points-Miner-v2 (>=2.0.7,<3.0.0) requires irc (19.0.1).
  So, because bot-1 depends on both Twitch-Channel-Points-Miner-v2 (^2.0.7) and irc (^20.0.0), version solving failed.

  at /opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
exit status 1

**Comment by Tkd-Alex** [comment]
Please stop to tag me or open multiple issue without any reason

If you want to upgrade the IRC version you can do by yourself just type `pip install -U package` or change the version on the requirements.txt.

Most of your problem are related to repl, maybe change hosting can be a solution.

**Comment by BarboPT** [comment]
and how i go use automatic pip install Twitch-Channel-Points-Miner-v2?

**Comment by BarboPT** [comment]
Twitch-Channel-Points-Miner-v2-2.0.7.tar.gz i need this directory

**Comment by Tkd-Alex** [comment]
Clone the repository and the do `python setup.py`

**Comment by BarboPT** [comment]
23/01/22 20:41:22 - INFO - [print_report]: 🛑  Ending session: '5189bc66-2d4c-4f50-9c39-85d2da9fc1fe'
23/01/22 20:41:22 - INFO - [print_report]: 📄  Logs file: /home/runner/bot/logs/RicardoGamerYT.log
23/01/22 20:41:22 - INFO - [__print_report]: ⌛  Duration 0:00:12.665124

Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/home/runner/bot/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 348, in end
    sys.exit(0)
SystemExit: 0
signal: interrupt

