### ISSUE TITLE
[Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by mosheernser880** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#407]
When run, the script gives the following error: Error with GQLOperations (ReportMenuItem): HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.connection .HTTPSConnection object at 0x7fa7c9c87eb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
 - OS: Linux

**Comment by Tkd-Alex** [comment]
Probably It's a problem with your DNS

**Comment by mosheernser880** [comment]
tried restarting dns, it worked
