### ISSUE TITLE
question please

### ISSUE THREAD

**Issue by stickerx** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#408]
fixed

**Comment by Tkd-Alex** [comment]
You should just follow the tutorial in the readme :)

**Comment by stickerx** [comment]
I do but I didn't find the location file Twitch-Channel-Points-Miner-v2 on my RP4  or any idea

**Comment by stickerx** [comment]
![2022-01-24_141009](https://user-images.githubusercontent.com/41187653/150788757-89fa9e1f-3a3a-4e48-9ec6-62afb1d37d5f.jpg)

**Comment by stickerx** [comment]
any idea how to fix this above

**Comment by stickerx** [comment]
![2022-01-24_141712](https://user-images.githubusercontent.com/41187653/150789731-b6b1ccb6-9df9-416e-b145-d84c0b28d652.jpg)
