### ISSUE TITLE
MakePrediction transactionID

### ISSUE THREAD

**Issue by lay295** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#41]
I was bored and wanted to make my own predictions bot without selenium, and I ran into the same problem with the transactionID.

I finished a prototype, and found that just generating a random 32 length hex string as the transactionID works, and lets the bet go through. Thought you might find this useful and would be cool if the program could be updated to not use selenium.

**Comment by Tkd-Alex** [comment]
😍😍😍
I had two ideas about the transactionID
- Random strings as you say
- Hash of current timestamp

But I've never tried it.
I was scared about ban or something else 🤔🤔 But If you say that It's work ...

**Comment by Tkd-Alex** [comment]
@Yishaqel It's currently testing this branch for us :partying_face:
