### ISSUE TITLE
Error while downloading requirements.

### ISSUE THREAD

**Issue by 22mieszko** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#414]
When installing requirements I just get error where it says that I must download newer version of Microsoft Visual C++ 14.0 or greater. I already installed a newest version but still doesn't work. Here is a screenshot.
![obraz](https://user-images.githubusercontent.com/50804862/152180075-c5d1da8d-0891-478c-8032-3b475ef805ec.png)

**Comment by Tkd-Alex** [comment]
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/355
