### ISSUE TITLE
Not all websockets are checked if alive

### ISSUE THREAD

**Issue by RakSrinaNa** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#42]
**Describe the bug**

I may have had a problem similar to #39 but not sure. Was running it in debug without any breakpoints, and at some point checked what happened and saw no logs for around an hour. Played a bit with the debugger to see where it was hanging and then the logs all reappeared (compared to .

Though were I managed to pause it, there may be a problem. It was there:
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/51671a3c80d9fe9f20a9efdfd3c43fee43cea07e/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py#L251

It may not be the same issue but I think that if you subscribe to more than 50 topics (and so have more than one connection), this part of the code only checks if **the last opened connection** is alive.

Here the ws is rewritten at each opened connection:
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/51671a3c80d9fe9f20a9efdfd3c43fee43cea07e/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L52

Same probably happens here (and everywhere that pool.ws is used), the end method will only close the last opened socket:
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/51671a3c80d9fe9f20a9efdfd3c43fee43cea07e/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L64-L66

**To Reproduce**
1. Probably run the script with enough users that it creates at least 2 connections ?

**Expected behavior**
Handling an array of opened ws would probably be better.

* End method could iterate through them and close them all
* When subscribing to topics we could iterate through them, subscribe to topics if there some space left in them (topics < 50), or add a new one to the array if needed and subscribe
* When we check pings, iterate through all ws and check all pings

If multiple connection isn't a good idea, maybe limiting the number of users that can be added in the config could be another idea.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser /
 - Python version 3.9

**Comment by Tkd-Alex** [comment]
The WebSocketPool was written by the original maintainer and I don't really know much about this.
I've only tried to handle the disconnections with the `last_ping` and `last_pong`, but your message have full sense! I think you are right, I'll try to fix. An array of ws can be a good idea :partying_face:

**Comment by RakSrinaNa** [comment]
Let it run overnight on the ws-pool branch and I didn't experience any weird moment with no logs at all.

**Comment by Tkd-Alex** [comment]
I had problem with both commits :(

**Comment by Tkd-Alex** [comment]
as my imagination we had lost multiple times the error message from websocket:
```
04/02/21 06:00:00 - ERROR - TwitchChannelPointsMiner.classes.WebSocketsPool - [on_error]: #1 - WebSocket error: Connection is already closed.
04/02/21 06:00:00 - INFO - TwitchChannelPointsMiner.classes.WebSocketsPool - [on_close]: #1 - WebSocket closed
```
```
04/02/21 07:27:05 - ERROR - TwitchChannelPointsMiner.classes.WebSocketsPool - [on_error]: #0 - WebSocket error: [Errno 110] Connection timed out
04/02/21 07:27:05 - INFO - TwitchChannelPointsMiner.classes.WebSocketsPool - [on_close]: #0 - WebSocket closed
```

**Comment by RakSrinaNa** [comment]
The fact that the connection is lost probably closes the socket by itself (if connection is lost, then what would it be connected to?)
From the doc:
> In closes the connection if it doesn’t get a pong within 20 seconds.
> You can adjust this behavior with ping_interval and ping_timeout.

Maybe what can be done:
----
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/4ef5baddac573d29836cd7555fa4db014dc84826/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L100-L102
Here set the boolean `ws.is_closed = True`

----

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/4ef5baddac573d29836cd7555fa4db014dc84826/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L106

Add a safety check before closing and actually close it:
```py
if not ws.is_closed():
    ws.close()
```

https://websockets.readthedocs.io/en/stable/api.html#websockets.server.WebSocketServer.close

Same idea over there:
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/4ef5baddac573d29836cd7555fa4db014dc84826/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L71

----

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/4ef5baddac573d29836cd7555fa4db014dc84826/TwitchChannelPointsMiner/classes/WebSocketsPool.py#L111

To avoid any problem with the index being wrong, probably can directly remove the instance itset:
```py
ws.parent_pool.ws.remove(ws)
````

**Comment by Tkd-Alex** [comment]
Sorry, I've read just now, and I've already done another fix that should work. I'm currently testing.
____
We are currently using: https://pypi.org/project/websocket_client/ and not https://pypi.org/project/websockets/
I don't know If we have the method `.is_closed()`, but obv we have a boolean value that we can check.
______
About this: `ws.parent_pool.ws.remove(ws)`

We have currently `[ ws0, ws1, ws2 ]`, each ws have an index attribute.
If we use `remove(ws1)` the array will be` [ ws0, ws2 ]`, now the index of **ws2 is 1**, we should update all the index every time we do a remove. Or I'm wrong?

**Comment by RakSrinaNa** [comment]
Yeah my bad, didn't really check what lib was used.

Well I think that we could not use the index at all.
When pinging, closing etc can just iterate through them (`for socket in ws:`).
And when removing just provide the instance to remove with `.remove(ws)`.
But don't focus on that too hard for now I guess, can still keep indexes it works too.

----
This is not part of this issue I'm just saying it there for now. I think that the work you did to use objects etc compared to the original repo is cool. But I think it could be improved further and take advantage of those objects and avoid lots of repetitions and make the code easier to understand.
Maybe let's focus on the fixes/enhancements for now and small adjustments/refactor can be done later. Can even do a PR at some point to propose what I see as improvements. But will wait that the current ongoing branches are merged.
