### ISSUE TITLE
"Value" The maximum number of viewing channels at the same time.

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#444]
How to raise the maximum number of simultaneously viewed channels? In which file, which parameter needs to be changed? (I also want to chat on all these channels).

I know that twitch allows you to farm channel points on a maximum of 2 channels at the same time.

**Comment by kapiorr** [comment]
chat=ChatPresence.ONLINE,               # Join irc chat to increase watch-time [ALWAYS, NEVER, ONLINE, OFFLINE]

**Comment by YaZanuda111111** [comment]
> chat=ChatPresence.ONLINE, # Присоединяйтесь к irc-чату, чтобы увеличить время просмотра [ВСЕГДА, НИКОГДА, ОНЛАЙН, ОФЛАЙН]

This will fix the chat issue. And where can I find the option to watch more than 2 channels at the same time?

**Comment by YaZanuda111111** [comment]
File: example.py line 18-19
```
priority=[
    Priority.STREAK, 
```

File: ...\TwitchChannelPointsMiner\classes\Twitch.py line 289
`elif prior == Priority.STREAK and len(streamers_watching) < 2000:`

I correctly understood that with such parameters the bot will sit immediately with 2000 users in the chat?

**Comment by Tkd-Alex** [comment]
I don't understand your question, I'm a little confused

**Comment by kapiorr** [comment]
This is Twitch limit, You can claim channel points simultaneously only on 2 channels.

**Comment by YaZanuda111111** [comment]
> This is Twitch limit, You can claim channel points simultaneously only on 2 channels.

I don't need twitch points, I want to use this program to be on all channels at the same time online

**Comment by Tkd-Alex** [comment]
Ok, so `chat=ChatPresence.ONLINE` that's it

**Comment by YaZanuda111111** [comment]
> Хорошо, вот `chat=ChatPresence.ONLINE`и все
