### ISSUE TITLE
Cannot get it to Work on heroku

### ISSUE THREAD

**Issue by 45O** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#447]
So I did everything in #130 including the Line 5 and Procfile changes however, I am still met with this error, did I do something wrong or am I just being retarded
![image](https://user-images.githubusercontent.com/73535746/157455750-75f0062e-f3f3-488a-ad92-4f672321a23f.png)

**Comment by Tkd-Alex** [comment]
Are you attempting to use the entire repository or the pypi version?

**Comment by 45O** [comment]
I was trying to use the entire repo, exactly how it comes from a clone or zip download

**Comment by LeoAlt8** [comment]
@Tkd-Alex and the latest version does not work on Ubuntu

![2022-03-09 221018](https://user-images.githubusercontent.com/92355871/157526000-772ceae9-495b-4867-8123-795336e1d1c9.jpg)

**Comment by Tkd-Alex** [comment]
> @Tkd-Alex and the latest version does not work on Ubuntu
> 
> ![2022-03-09 221018](https://user-images.githubusercontent.com/92355871/157526000-772ceae9-495b-4867-8123-795336e1d1c9.jpg)
> 

This is the wrong place to talk about your problem. Anyway, join_chat is deprecated, read the readme

**Comment by LeoAlt8** [comment]
I'm sorry and thank you. I didn't edit the file "run3.py". My fault 😞

**Comment by Tkd-Alex** [comment]
Dear @45O @Microck , I've never used this script on Heroku, so I've 0 knowledge about this.
For the moment, I'm very busy, and I can't do any test for you.

I'll try asap, In the meantime I would suggest trying with the pypi version

**Comment by BarboPT** [comment]
@LeoAlt8  request me to friends on discord and i help you
Barbo ツ 🔥🐉#4896

**Comment by Sorrow81** [comment]
> @LeoAlt8 request me to friends on discord and i help you Barbo ツ firedragon#4896

Hi BarboPT, i can't add you on Discord, when i try to copy your username is wrong. Did you have a Procfile to run in heroku ?
