### ISSUE TITLE
Error on startup of bot.

### ISSUE THREAD

**Issue by eM-Krow** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#448]
09/03 21:16:46 - Start session: '-----'
09/03 21:16:46 - Load 0 followers from your profile!
09/03 21:16:46 - Loading data for 0 streamers. Please wait...
09/03 21:16:47 - error from callback <function WebSocketsPool.on_message at 0x00000removed>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'removed'}
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 400, in _callback
    callback(self, *args)
  File "S:\python\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 378, in on_message
    raise RuntimeError(f"Error while trying to listen for a topic: {response}")
09/03 21:17:47 - #0 - WebSocket error: Connection to remote host was lost.
09/03 21:17:47 - #0 - WebSocket closed
09/03 21:17:47 - #0 - Reconnecting to Twitch PubSub server in ~60 seconds

**Comment by Tkd-Alex** [comment]
Delete the cookie and login again
