### ISSUE TITLE
Messages in chat

### ISSUE THREAD

**Issue by klaksik** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#450]
Сan you make a function to write messages to the chat of a given text document?

**Comment by klaksik** [comment]
it's just that you can get a reward for points for 500+ messages

**Comment by Tkd-Alex** [comment]
> it's just that you can get a reward for points for 500+ messages

How?

**Comment by vykend** [comment]
> it's just that you can get a reward for points for 500+ messages

Is it repeated reward for every 500 messages or one-time thing?

If it's one-time thing just spam it in chat yourself, no need for automated tool.


Also do you have any source on this topic? This is the first time I'm reading about this reward.
