### ISSUE TITLE
Twitch Moments

### ISSUE THREAD

**Issue by ErdemUyanik** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#455]
**Is your feature request related to a problem? Please describe.**
Twitch added a new "moments" feature, that lets viewers collect a badge for being part of the stream when a special moment happend. An option to collect that moment would be nice. More information can be found here:

https://help.twitch.tv/s/article/moments?language=en_US

**Comment by Tkd-Alex** [comment]
Duplicate of #428
