### ISSUE TITLE
Could not install packages due to an OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by MAXOUXAX** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#460]
**Describe the bug**
_I'm using that script in a Docker container on Pterodactyl, that's why I don't use the proposed Docker image._

The container performs these actions at startup:
 - `git pull`
 - `pip install -U --target /home/container/ -r requirements.txt`
 - `python run.py`

After cloning the git repository, creating a run.py file and running my container, everything goes well until I get this error message:
```python
Installing collected packages: pycparser, zipp, more-itertools, cffi, pytz, jeepney, jaraco.functools, jaraco.context, importlib-resources, cryptography, tempora, six, SecretStorage, platformdirs, MarkupSafe, jaraco.text, jaraco.classes, importlib-metadata, filelock, distlib, Werkzeug, virtualenv, urllib3, toml, pyyaml, python-dateutil, pycryptodome, pyaes, pbkdf2, numpy, nodeenv, lz4, keyring, Jinja2, jaraco.stream, jaraco.logging, jaraco.collections, itsdangerous, idna, identify, click, charset-normalizer, cfgv, certifi, websocket-client, requests, pre-commit, pillow, pandas, millify, irc, flask, emoji, colorama, browser-cookie3
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device
```

Only thing is, the container has enough space (1GB), I already tried to increase it to 4GB and it doesn't solve any problem, and same on my host machine, there is more than enough disk space.
So I'm a bit confused, because even after completely reinstalling the container, the error persists.

**To Reproduce**
1. Install Pterodactyl
2. Create a container using [this egg](https://github.com/parkervcp/eggs/tree/master/bots/discord/discord.py)
3. Configure the container (repo url, branch, turn on auto updates, set the python bot file to run.py)
4. Start the container and observe

**Expected behavior**
The dependencies should install without any problem

**Desktop (please complete the following information):**
 - OS: Not relevant since this is a Docker container
 - Python version: Python 3.9 (also tested 3.8)

**Comment by Tkd-Alex** [comment]
Maybe the problem It's the same reported here?
https://askubuntu.com/questions/1326304/cannot-install-pip-module-because-there-is-no-space-left-on-device

**Comment by MAXOUXAX** [comment]
> Maybe the problem It's the same reported here? https://askubuntu.com/questions/1326304/cannot-install-pip-module-because-there-is-no-space-left-on-device

adding `export TMPDIR=/home/container/tmp;` to the startup command fixed the problem, although I'm not sure why I never had this problem before.

I never encountered this error in months of running the script - with a daily restart - and when the error occurred, I literally deleted all the files and started over, but got the same error again.
Maybe some dependencies were added recently and that somehow filled the default /tmp directory?
