### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BarboPT** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#462]
Traceback (most recent call last):
  File "Twitch-Channel-Points-Miner-v2/run.py", line 50, in <module>
    streamer_settings=StreamerSettings(
TypeError: __init__() got an unexpected keyword argument 'join_chat'

**Comment by Tkd-Alex** [comment]
join_chat is deprecated

**Comment by BarboPT** [comment]
@Tkd-Alex > join_chat is deprecated

thx are possible add hosts too if win points (idk)
