### ISSUE TITLE
From isnt recoginsed by my pi

### ISSUE THREAD

**Issue by rijksmc** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#466]
**Describe the bug**
vvvvvvvvvvvvvvvvv

pi@raspberrypi:~ $ python run.py
  File "run.py", line 4
    from colorama import Fore\
       ^
SyntaxError: invalid syntax

**Expected behavior**
It will just run

**Desktop (please complete the following information):**
 - OS: [Raspbian]
 - Python version [3.7.3]

**Additional context**
Please let me know what i have to install to get this programm running:)

**Comment by Tkd-Alex** [comment]
It's all written here: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use
