### ISSUE TITLE
Error related to numpy

### ISSUE THREAD

**Issue by danielbeckera** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#469]
I just cloned the repo, pip installed requirements and created the run.py file with the settings on it, but im getting this error:

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject.

I followed [this](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp) stackoverflow question but now I get other error:

ImportError: Unable to import required dependencies:
numpy:

 - OS: RaspberryPi OS
 - Python version 3.9.2

**Comment by DenisG1302** [comment]
Same problem in ubuntu for RaspberryPi.

**Comment by dmrm2312** [comment]
I had this same error, but I think a shared object dependency was missing since this command fixed my issue
```sudo apt-get install libatlas-base-dev```

**Comment by danielbeckera** [comment]
sudo apt-get install libatlas-base-dev

solved my problem
