### ISSUE TITLE
Question for drops

### ISSUE THREAD

**Issue by LukysGaming** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#472]
Hi, so rust drops started and I dont want to manually claim them all over the 17hour period.
The drops arent from specific streamer but from all streamers with drops enabled tag, so my question is what option do I need to enable to automatically claim them? thanks

**Comment by ColinShark** [comment]
You still have to watch Streams to be able to claim them, you can't just tell the miner to "Watch everything Rust". You have to put them into your config file still.

I just added the individual streamers (DisguisedToast and alexby11) to my config file, as well as several streamers that are streaming almost exclusively rust anyway (Welyn, spoonkid, TwitchRivals).

Just make sure that you actually `claim_drops=True` in your `StreamerSettings()`.
