### ISSUE TITLE
Doesnt automatically reconnect after internet/wifi disruption

### ISSUE THREAD

**Issue by Warlord21** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#486]
**Describe the bug**
The miner doesnt automatically reconnect after internet connection is available again , it gets stuck on trying reconnection after the connection is back....It continuously tries to reconnect when internet connection is not available but as soon as it is available it doesnt proceed to reconnect

**To Reproduce**
Run miner with internet disconnected
Connect back the internet 
it doesnt work then

**Expected behavior**
Should reconnect

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version [e.g. 3.10]

**Comment by Warlord21** [comment]
any updates?

**Comment by Tkd-Alex** [comment]
The bot was written to handle connection error and perform automatically the reconnection. 
Can you share a screen or the logs file?

**Comment by Warlord21** [comment]
I am extremely sorry but it was my mistake, it did reconnect but there was no visual indicator so i misinterpreted , i will close the issue now , sorry for wasting ur time :(
