### ISSUE TITLE
Raspberry Pi Supported?

### ISSUE THREAD

**Issue by laGameTV** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#493]
### Discussed in https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/discussions/492

<div type='discussions-op-text'>

<sup>Originally posted by **laGameTV** May  1, 2022</sup>
Im a newbie to python and i tried cloning the repo on my pi 4 but this doesnt really work.</div>

![image](https://user-images.githubusercontent.com/31692271/166146994-92cb0bce-6850-41ab-87d7-df556eb85c25.png)
whenever i try to run the run.py i get this error. and yes. i did install the requirements.txt. what should i do?

**Comment by Tkd-Alex** [comment]
`pip install -r requirements`

**Comment by laGameTV** [comment]
![image](https://user-images.githubusercontent.com/31692271/166151298-b71ac3a3-e173-4598-bf0c-5f465f905bab.png)

**Comment by Tkd-Alex** [comment]
You are using pip for python3.9 and execute the script with python3.7
Check if you have pip3.7, or execute the script with python3.9

**Comment by laGameTV** [comment]
i built a python 3.7 version on the pi using this guide https://gist.github.com/SeppPenner/6a5a30ebc8f79936fa136c524417761d
And for running the py i used `python3.7 run.py`

**Comment by ColinShark** [comment]
With whatever Python version you prefer, set up a virtual environment to encapsulate your dependencies:

```bash
# Navigating to home directory
cd ~

# cloning the repository into its own folder (no zip download)
git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2.git twitchminer
cd twitchminer

# Use the python version of your choice, commands after this don't need versioning
python3.7 -m venv venv

# create and activate a virtual environment, update pip and install requirements
source ./venv/bin/activate
python -m pip install -U pip wheel
pip install -Ur requirements.txt
```

**Comment by laGameTV** [comment]
Thanks. I now got it to work using pip3.7
