### ISSUE TITLE
I seem to be only getting points on 2 sometimes 3 channels

### ISSUE THREAD

**Issue by Olamio** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#5]
It does import the right amount of people that I follow and even recognice the ones that are online but after the whole "streamer xxx is online" thingy is over it only shows +10 or +50 on two or three channels
![Problem](https://user-images.githubusercontent.com/77693637/105109771-7dc03780-5abd-11eb-8622-612fe31861ce.PNG)

**Comment by Tkd-Alex** [comment]
Yes, It is correct / normal. This is a Twitch limit.
You can read a comment in the original repository (I've also included this comment in the code):
https://github.com/gottagofaster236/Twitch-Channel-Points-Miner/blob/master/watch_minute.py#L29

And if you are convinced just googling, I've founded something on Reddit:
https://www.reddit.com/r/Twitch/comments/htr6iy/watching_multiple_streams_viewer_count/

**Comment by Olamio** [comment]
Oh, okay I seem to have skipped that part. Is there a way to maybe change the priority of some streamers, because the "list" seems to be just a random order?

**Comment by Tkd-Alex** [comment]
If you write manually the streamers then the priority It's the same that you have write.
If you download the followers from Twitch the order It's the same of Twitch and I think It's based on `followed_at` field. The last that you have follow have higher priority.

**Comment by Olamio** [comment]
Oh, so "["streamer1", "streamer2"],  # Array of streamers" will prioritize them from left to right? If so, you should definitely put that in the documentation!

**Comment by scryptio** [comment]
Don't want to open a new issue for this. But is this only related to using programs? Or is this info outdated currently?

I have 6 tabs open where I actively collect time for streamelements giveaways (you gather points / 10min watching) and it works perfectly.

**Comment by Tkd-Alex** [comment]
streamelements are different from Twitch points
