### ISSUE TITLE
Set Priority

### ISSUE THREAD

**Issue by abdevv** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#505]
I want to prioritize streamers with which I have a high score. But I could not. Is there anyone who can help?

**Comment by ColinShark** [comment]
Use `POINTS_DESCENDING` in your priority. This should start with the streamer you have the most points for, then the next lowest and so on.

**Comment by abdevv** [comment]
I don't know exactly where to write. Thank you for your answer.

**Comment by ColinShark** [comment]
> I don't know exactly where to write.

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/master/example.py#L18-L22

```python
priority = [
    Priority.POINTS_DESCENDING
]
```
