### ISSUE TITLE
It's saying that the streamer doesn't exist!

### ISSUE THREAD

**Issue by TinyHero13** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#513]
**Describe the bug**
I have used the same code with my other accounts, but changing the username and the password and worked, but when I tried with the third account it's shows that the streamer does not exist.

**To Reproduce**
1. wrote the command "python3 MyThirdAccount.py"
2. After the message of "streamer does not exist" I exit the program with CTRL + C

**Desktop (please complete the following information):**
 - OS: POP OS
 - Python version: 3.10.4

**Log**
[Log FIle](https://drive.google.com/file/d/1OyGweKlC6HJ381e6JLBjZvghI104QODG/view?usp=sharing)

**Error Output**
16/05/22 18:04:36 - INFO - [run]: 💣  Start session: 'c5706428-f7aa-4d6c-b8f1-e039ab7c0f5b'
16/05/22 18:04:37 - INFO - [run]: 🤓  Loading data for 3 streamers. Please wait...
16/05/22 18:04:38 - INFO - [run]: 😢  Streamer hitsquadgodfather does not exist
16/05/22 18:04:39 - INFO - [run]: 😢  Streamer lenovolegion does not exist
16/05/22 18:04:40 - INFO - [run]: 😢  Streamer glodoom does not exist
16/05/22 18:04:41 - ERROR - [error]: error from callback <function WebSocketsPool.on_message at 0x7f7934968280>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'r8F2RtJEL0bRo0KMIfJGlXzpeGUW30'}
16/05/22 18:04:41 - ERROR - [on_error]: #0 - WebSocket error: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'r8F2RtJEL0bRo0KMIfJGlXzpeGUW30'}16/05/22 18:05:41 - ERROR - [on_error]: #0 - WebSocket error: Connection to remote host was lost.
16/05/22 18:05:41 - INFO - [on_close]: #0 - WebSocket closed
16/05/22 18:05:41 - INFO - [handle_reconnection]: #0 - Reconnecting to Twitch PubSub server in ~60 seconds
16/05/22 18:06:41 - ERROR - [error]: error from callback <function WebSocketsPool.on_message at 0x7f7934968280>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': '6dCRCemvNkYH1SzzNLfnJejeyDteN1'}
16/05/22 18:06:41 - ERROR - [on_error]: #0 - WebSocket error: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': '6dCRCemvNkYH1SzzNLfnJejeyDteN1'}
16/05/22 18:07:12 - ERROR - [on_error]: #0 - WebSocket error: Connection to remote host was lost.
16/05/22 18:07:12 - INFO - [on_close]: #0 - WebSocket closed
16/05/22 18:07:12 - INFO - [handle_reconnection]: #0 - Reconnecting to Twitch PubSub server in ~60 seconds
16/05/22 18:08:12 - ERROR - [error]: error from callback <function WebSocketsPool.on_message at 0x7f7934968280>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'xj9e7iurumPKM5eFrPmCw0OcNTYlUA'}
16/05/22 18:08:12. - ERROR - [on_error]: #0 - WebSocket error: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error':'ERR_BADAUTH', 'nonce': 'xj9e7iurumPKM5eFrPmCw0OcNTYlUA'}
^C16/05/22 18:08:15 - INFO - [end]: CTRL+C Detected! Please wait just a moment!
16/05/22 18:08:15 - INFO - [on_close]: #0 - WebSocket closed
16/05/22 18:08:21 - INFO - [__print_report]: 🛑  Ending session: 'c5706428-f7aa-4d6c-b8f1-e039ab7c0f5b'
16/05/22 18:08:21 - INFO - [__print_report]: ⌛  Duration 0:03:44.581794

**Comment by ColinShark** [comment]
Those errors you get `{'type': 'RESPONSE', 'error': 'ERR_BADAUTH', ..}` make me believe that your session/cookie might have been logged out. Could you try to delete your third accounts cookie file and log in interactively?
If there is no cookie file, the program should ask you for Password and 2FA interactively

```bash
rm ./cookies/MyThirdAccount.pkl
python3 MyThirdAccount.py
```

<details><summary>Offtopic: For the future, please wrap code and logs in triple backticks</summary>

    ```
    like so
    ```
</details>

**Comment by TinyHero13** [comment]
Oooh I see, deleting the cookies worked,  thanks for the help and the advice.
