### ISSUE TITLE
Syntax Error - "Username = str"

### ISSUE THREAD

**Issue by Hughesy** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#52]
Hi there,

I am probably doing something really stupid, but I keep getting a syntax error as shown in screenshot.

Any help would be great,

Thanks,
<img width="778" alt="Screenshot 2021-02-05 at 17 22 37" src="https://user-images.githubusercontent.com/2457878/107067356-13a2d480-67d7-11eb-9d61-78cf078f187f.png">

**Comment by Tkd-Alex** [comment]
`python --version` ?

**Comment by Hughesy** [comment]
2.7 I think

**Comment by Tkd-Alex** [comment]
Python 2.x is deprecated. Please upgrade to 3.6+

**Comment by Hughesy** [comment]
Ah okay, it's been working fine with other projects, so assumed it would work.

Thanks for your help

**Comment by Tkd-Alex** [comment]
Hey @Hughesy , It's solved? Can we close this issue?

**Comment by Hughesy** [comment]
Yes, thanks for your help!
