### ISSUE TITLE
Exception Raised for topic:community points

### ISSUE THREAD

**Issue by Warlord21** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#523]
**Describe the bug**
This error keeps on showing up after I start the program. I searched the issues earlier and found out that it can be fixed by deleting the analytics folder, I did that, sometimes this fixed the problem but the frequency of its occurence is quite high, today even after deleting the folder it did not fix the error. Occuring only on one device, I have got another realme phone with android 12 running the same script using termux and i dont get the issue.
![Screenshot_2022-06-03-23-36-21-230_com termux](https://user-images.githubusercontent.com/26519624/171925882-e3c1dc22-4e0c-4df0-a2eb-eee8966ef9ac.jpg)
![Screenshot_2022-06-03-23-36-41-826_com termux](https://user-images.githubusercontent.com/26519624/171925898-6abbdec5-199e-42e0-b192-e8755c08c9b8.jpg)

**To Reproduce**
start the script and it occurs automatically

**Expected behavior**
Normal mining should occur

**Desktop (please complete the following information):**
 - OS: Android 11 MIUI 12.5.6 stable
 - Python version 3.10.4
 - Latest termux update

**Comment by Warlord21** [comment]
any updates?

**Comment by D3SK3R** [comment]
I get this too, it seems to be the way it writes to the file, not fully compatible with json, but it still works, you just can't read what it's doing
![image](https://user-images.githubusercontent.com/39961645/172526243-8f0c743f-41d5-4c19-aa2b-f12aa84ccb6b.png)

**Comment by Warlord21** [comment]
> I get this too, it seems to be the way it writes to the file, not fully compatible with json, but it still works, you just can't read what it's doing ![image](https://user-images.githubusercontent.com/39961645/172526243-8f0c743f-41d5-4c19-aa2b-f12aa84ccb6b.png)

so u mean that it still mines points while its showing these errors? are you sure about this?

**Comment by D3SK3R** [comment]
> so u mean that it still mines points while its showing these errors? are you sure about this?

Yes, I've tested many many times, and it still gets you points, bets for you, gets drops, everything still works fine, this errors simply prevents the script to show you what it's doing.

**Comment by Warlord21** [comment]
> > so u mean that it still mines points while its showing these errors? are you sure about this?
> 
> Yes, I've tested many many times, and it still gets you points, bets for you, gets drops, everything still works fine, this errors simply prevents the script to show you what it's doing.

but i think we are getting different errors, mine is for community points...

**Comment by Tkd-Alex** [comment]
Try to remove the analytics folder

**Comment by Warlord21** [comment]
> Try to remove the analytics folder

I tried deleting the folder too and separately deleting the json files too
