### ISSUE TITLE
Strange error when leaving IRC chat

### ISSUE THREAD

**Issue by tildejustin** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#541]
**Describe the bug**
Every time after the script leaves IRC chat I get the error:
`
08/07/22 12:24:53 - ERROR - [start]: Exception raised: [Errno 9] Bad file descriptor. Thread is active: True
`

and then it prints
`
08/07/22 12:24:53 - ERROR - [start]: Exception raised: file descriptor cannot be a negative integer (-1). Thread is active: True
` a couple hundred times. This only happens on mac, not on windows.

**To Reproduce**
1. Run script
2. Wait for someone to go offline

**Expected behavior**
To not give an error.

**Desktop (please complete the following information):**
 - OS: [MacOS 11.6.5, Win 11 build 22000.739]
 - Python version [3.10.5 (both)]

**Additional context**
I'm not very good at working with macs so there might be something very obvious I'm overlooking. I run the script from terminal by `python3 run.py`.

**Comment by LuKresXD** [comment]
same

**Comment by JCharante** [comment]
same
