### ISSUE TITLE
Web Server

### ISSUE THREAD

**Issue by bgktmxg** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#556]
First of all thanks for the awesome app! Im running it on a windows VM as I dont have the knowledge to run scripts on Unraid just yet.

Ive got more of a question rather than a bug. Ive got the web server working locally via 127.0.0.1:5000, but cant access it from another PC via 192.168.1.119:5000 (the machines IP)

Ive tried disabling the firewall, but wanted to check to make sure there's no other setting I should be aware of before I start digging deeper into windows settings.

Cheers!

**Comment by TheToto** [comment]
Hello,

Did you miss this line in the README ?

```
If you want to connect from one to second machine that have that webpanel you have to use 0.0.0.0 instead of 127.0.0.1.
```

**Comment by bgktmxg** [comment]
Hi, I did read that line (many times actually) but it just didnt seem right. I have since set it to 192.168.1.119 and opened port 5000 in the firewall and its working nicely.

Thanks for the reply
