### ISSUE TITLE
Don't Start

### ISSUE THREAD

**Issue by FMB684** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#559]
when i start the python file the only output in the console is "24/07/22 19:01:28 - DEBUG - [_new_conn]: Starting new HTTPS connection (1): raw.githubusercontent.com:443".

 - OS: Linux
 - Python version 3.8

**Comment by AgileGhost** [comment]
I can take a long time to start up. If you leave it for a couple of hours and come back it should be fully started.

**Comment by ColinShark** [comment]
> I can take a long time to start up.

It shouldn't. My script with currently 15 streamers starts up within like 30 seconds.

---

@FMB684 You may want to add further logs and not just a single line. Your `run.py` might also be good information to see how your setup looks.

**Comment by FMB684** [comment]
i re-downloaded and re-configured the farmer, now it works
