### ISSUE TITLE
ModuleNotFoundError: No module named 'TwitchChannelPointsMiner'

### ISSUE THREAD

**Issue by taurynamonsterxdd** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#570]
![image](https://user-images.githubusercontent.com/108152893/184369424-79118007-05be-4adc-90b2-689d83de93a4.png)
![image](https://user-images.githubusercontent.com/108152893/184369456-cab9f9b0-99c8-43ec-bb9f-f5ab86eb44da.png)
13:59 ~ $ python run.py
Traceback (most recent call last):
  File "/home/vezdus/run.py", line 5, in <module>
    from TwitchChannelPointsMiner.TwitchChannelPointsMiner import TwitchChannelPointsMiner
ModuleNotFoundError: No module named 'TwitchChannelPointsMiner' 
help me pls

**Comment by Jackas0** [comment]
idk, but mb use "cd" in your bash console?

**Comment by MoMMde** [comment]
having the same issue, although i use docker

**Comment by taurynamonsterxdd** [comment]
pip install Twitch-Channel-Points-Miner-v2

**Comment by taurynamonsterxdd** [comment]
> having the same issue, although i use docker

pip install Twitch-Channel-Points-Miner-v2

**Comment by MoMMde** [comment]
> 
How should this help on Docker? The Dockerfile copies the `TwitchChannelPointsMiner` dir into the WORKDIR directory. So it uses the code from the latest contianer build and for some reason its missing
