### ISSUE TITLE
Start on windows startup

### ISSUE THREAD

**Issue by LukysGaming** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#575]
Hi, always when i add start.bat with path to the script to shell:startup
`@echo off
"C:\Users\Xdmoj\AppData\Local\Programs\Python\Python310/python.exe " "D:\twfarm\Twitch-Channel-Points-Miner-v2-master/run.py"
pause`
It always creates folders 
- analytics
- cookies
- logs
, that means when i start windows i always have to manually close them because they open.
any idea how to fix it?

**Comment by hubailmn** [comment]
try,

@echo off 
py D:\twfarm\Twitch-Channel-Points-Miner-v2-master\run.py
pause

**Comment by hubailmn** [comment]
put the bat file in "D:\twfarm\Twitch-Channel-Points-Miner-v2-master\run.py"
and create a shourtcut of the bat file 
and put the shortcut in the startup fille

**Comment by LukysGaming** [comment]
> put the bat file in "D:\twfarm\Twitch-Channel-Points-Miner-v2-master\run.py" and create a shourtcut of the bat file and put the **shortcut** file in the **startup** file
> 
> i know bad explanation :))
> 
> @echo off timeout/t 60 py D:\twfarm\Twitch-Channel-Points-Miner-v2-master\run.py pause

Got it, thank you so much.
