### ISSUE TITLE
Errno 2 - no such file or directory on UNRAID

### ISSUE THREAD

**Issue by Maxi531** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#585]
I tried installing the docker on unraid and the template installed correctly, the command run, but I can't get the container to start. It errors with "Errno 2 - No such file or directory"
 t**Describe the bug**

Maybe I am just too incompetent, I'm not that versed in Docker, but on Windows itself I got the docker to run.

![Docker Template Unraid](https://user-images.githubusercontent.com/82330572/188329881-659c1c3e-9d1a-4120-b085-c2ab53e46cbe.png)
![Directory Unraid](https://user-images.githubusercontent.com/82330572/188329996-96fbaf95-d798-46f1-9399-38786c711018.png)
![Command executed correctly](https://user-images.githubusercontent.com/82330572/188329885-30662ed8-894e-4bb0-8e1e-5d32688b020b.png)

![Error](https://user-images.githubusercontent.com/82330572/188329866-deb6c918-79d6-4203-b2c6-695687b99971.png)

**Comment by FlavioPrates** [comment]
Hey @Maxi531, Im having the same problem as you, how exactly did you fix this?
Thanks!

**Comment by Maxi531** [comment]
> Hey @Maxi531, Im having the same problem as you, how exactly did you fix this?
> 
> Thanks!

So the container Path has to be _/usr/src/app/x_ x being logs, run.py etc.

**Comment by FlavioPrates** [comment]
Yeah thats what I tought you meant, I tried that and didnt work for me...

**Comment by Maxi531** [comment]
Send a quick screenshot of the container path and directory configs
