### ISSUE TITLE
Program taking obscene amount of time to fetch streamers

### ISSUE THREAD

**Issue by chronoquairium** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#596]
This is a new issue that only started in the past day or two after almost a year of continuous usage.
![dafuq](https://user-images.githubusercontent.com/68948661/190518238-6967d117-45f2-43d6-8f4e-c025f246eae2.PNG)

Two things to note: There is also that same amount of time spent until the "unable to detect" line, during which the window has no text whatsoever for the three full minutes until it shows up. The second thing is that while it was not collecting any points at all while fetching the streamers, after it got the last one it _did_ start collecting as normal, including claims and raids. But _only_ after the last one.

Debug log included if necessary - everything before the current session was removed to make it fit in the post.

[debug.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/9579377/debug.log)

**Comment by rdavydov** [comment]
@chronoquairium If you closed this as completed that means you have a solution. It would be nice of you to share how the issue was fixed with the rest of the community.
