### ISSUE TITLE
Include acc name in logs + more log options

### ISSUE THREAD

**Issue by Guliveer** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#602]
**Is your feature request related to a problem? Please describe.**
Since there is a possibility to use multiple accounts at once, I thought it would be cool if you could differentiate which is which.
Also, I thought about adding more options to the log system (Events), like START, LOAD, and END.

**Describe the solution you'd like**
Just check the bottom of the issue.

**Describe alternatives you've considered**
At the moment I don't think there are any alternatives

**Additional context**
![Screenshot_215](https://user-images.githubusercontent.com/32310642/191108721-74c559c3-87c1-4e15-981e-61ccf6caa150.png)

e.g.
> **_TwitchChannelPointsMiner.py:_**
> f"`[{self.username}] `Start session: '{self.session_id}'", extra={"emoji": ":bomb:", `"event": Events.START`,}

Anything more that is to do is just edit _**Settings.py**_ file and you're good to go!

**Comment by rdavydov** [comment]
`TwitchChannelPointsMiner.py` doesn't produce all the log messages, for example `+50 --> ... REASON: CLAIM` is handled by another module. I decided to add the username to `logger.py`, so it will appear on EVERY message in the console.

It works and looks cool. Added an option to toggle it.

See PR #635 or my release https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/1.3.2
