### ISSUE TITLE
unable to find any streamers

### ISSUE THREAD

**Issue by anytarseir67** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#605]
**Describe the bug**
unable to find any streamers

**To Reproduce**
run the script

**Expected behavior**
finding streamers

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.8.7

**Additional context**
i recently changed my twitch account password, and although i have updated it in the script, given the timing i feel it *could* be related.
also, after it runs through the list of streamers, it throws an `ERR_BADAUTH` from `on_message` in `TwitchChannelPointsMiner\classes\WebSocketsPool.py`

**Comment by wizardtoast** [comment]
You may need to delete the cookie file for your account at `Twitch-Channel-Points-Miner-v2\cookies\<YourAccount>.pkl` and try again

**Comment by anytarseir67** [comment]
> You may need to delete the cookie file for your account at `Twitch-Channel-Points-Miner-v2\cookies\<YourAccount>.pkl` and try again

after removing the cookie

```
23/09/22 03:31:05 - INFO - [login_flow]: You'll have to login to Twitch!
Traceback (most recent call last):
  File "./mine.py", line 8, in <module>
23/09/22 03:31:05 - ERROR - [login_flow]: Unknown error: {'error': 'Oops! We encountered an unexpected error. Please try again.', 'error_code': 5027, 'error_description': 'client blocked from this operation'}
```

**Comment by anytarseir67** [comment]
seems the new problem is unrelated, #606
