### ISSUE TITLE
Console login unavailable (VDS)

### ISSUE THREAD

**Issue by EnchantedGoldenApple** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#608]
I have VDS on DigitalOcean. Droplet on Debian without GUI. When I start program I have a error: Console login unavailable (CAPTCHA). And choise what browser I use. But it is a cli linux. I don't have any browsers. What should I do?

**Comment by ColinShark** [comment]
The CAPTCHA needs js, which the CLI doesn't have. I just run it locally, then upload the cookie file to the server.
