### ISSUE TITLE
You'll have to login to Twitch!

### ISSUE THREAD

**Issue by niruvibes** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#620]
When trying to run the script, it just says "You'll have to log in to Twitch!" without any input or popup or anything, adding the password and username to the file also doesn't work.
![image](https://user-images.githubusercontent.com/67180137/195262705-5a594883-f795-4452-993d-9a655aff6333.png)

**Comment by niruvibes** [comment]
No clue how to add the need help label sorry

**Comment by BeastModeCoding** [comment]
If you look carefully, you'll notice that the error is "Unknown TwitchAPI error code:5027". This is happening due to recent changes in Twicth API. This topic has been discussed and solved here:
[https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/606#issuecomment-1256839239](url)

**Comment by niruvibes** [comment]
Ah i see, ill follow the steps and let you know if i have anything else.
Thanks!

**Comment by niruvibes** [comment]
Well there is nothing else that is important, but this just sits like this 
![image](https://user-images.githubusercontent.com/67180137/195779917-07aab86a-6e19-4e7a-8f7d-64598d7b259f.png)
