### ISSUE TITLE
Incorrect filter applied text

### ISSUE THREAD

**Issue by SiIason** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#63]
```
08/02 11:09:44 - Filter applied on this bet. Current total_users is 12, must be GT 10
```

Settings filter is DECISION_USERS not TOTAL_USERS

**Comment by Tkd-Alex** [comment]
It is correct.
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/82cd573d9158b4597dfb4d9fac8852d30e123171/TwitchChannelPointsMiner/classes/entities/Bet.py#L39-L45

I use the `OutcomeKeys` for reference key in the code. These values are the same but are distinct by the If in the `skip()` method

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/82cd573d9158b4597dfb4d9fac8852d30e123171/TwitchChannelPointsMiner/classes/entities/Bet.py#L183-L187

```python
if key in [OutcomeKeys.TOTAL_USERS, OutcomeKeys.TOTAL_POINTS]
    compared_value = sum values
else:
    compared_value = get this value based on decision
````

**Comment by SiIason** [comment]
I have to disagree, if I'm filtering on DECISION_USERS, thats what the log should tell me not total_users.
Because at that point in time TOTAL_USERS is a totally different value and is described as such in the docs.

I agree the filter is working, but its not clear in the INFO what filter is being applied.
