### ISSUE TITLE
Script/Twitch reporting wrong drop information

### ISSUE THREAD

**Issue by SiIason** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#65]
![image](https://user-images.githubusercontent.com/2955537/107247038-c9189680-6a28-11eb-9a6e-4d043821b2fb.png)

Script sees the value 75%, but the actually moving value is 18%

Which caused this behaviour  https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/35#issuecomment-775251794

Could be caused by the campaign changing? Maybe the previous drop was 75% collected when it because unavailable and the campaign updated? I'll check logs and update.

**Comment by SiIason** [comment]
Yip that looks like it.

```
08/02 14:56:42 - +10 --> brbteabreak (19.34k points) - Reason: WATCH.
08/02 14:58:43 - Drop event 75% for brbteabreak (19.34k points)!
<---CAMPAIGNS UPDATED, OLD DROP NOW UNAVAILABLE
<---NEW CAMPAIGN OPEN NEW DROP STARTED COLLECTING
08/02 15:00:41 - Drop event 75% for brbteabreak (19.34k points)!
08/02 15:01:41 - Drop event 75% for brbteabreak (19.34k points)!
```

**Comment by Tkd-Alex** [comment]
Sorry @SiIason but the Twitch Drops It's a really big feature and I need time to write better/again all the logs and how we manage the inventory and claim the drops. Currently, I don't have this time. I'll work asap.

For example in this specific case as you also you see the problem It's not related how we calculate the drops percentage but how Twitch talks with us, and as you can see on image's right corner the percentage It's currently at 75%. I should make a request every time for the inventory and see If we the correct status/percentage. And I don't really like. Moreover, the LOGS dedicated for percentage It was my idea for debug, If It's create too much problem for you, I can delete this row and make available again when It's fully working.
