### ISSUE TITLE
anyone got a clue whats my problems here? "TypeError: __init__() got an unexpected keyword argument 'console_username'"

### ISSUE THREAD

**Issue by Kazushi-0** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#651]
![image](https://user-images.githubusercontent.com/89697869/201664282-92752f70-47bb-47ee-b78e-7be54c8d7a06.png)

**Comment by rdavydov** [comment]
Seems like you're trying to use the runner file from [my fork](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2) which introduced a new option called `console_username` on the old version that don't have such option. Am I right?

What version of the miner are you using? What link did you download it from?

**Comment by Kazushi-0** [comment]
Im using a docker image to install it soo... bacisly the official one

**Comment by rdavydov** [comment]
No, I don't currently use Docker. But you always can build one yourself.

This is not the first time people asking for a pre-built Docker image, so I will add this to my TODO list.
