### ISSUE TITLE
Browser Unsupported 

### ISSUE THREAD

**Issue by B4kedBr3ad** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#659]
I started it with Termux and when I ran it, it questioned my browser.
So I selected 3. I got an error and could not log in. What should I do?

Log:
```
~/Twitch-Channel-Points-Miner-v2 $ python run.py           
19/11/22 11:58:32 - INFO - [run]: 💣  Start session: 'xxxxxxxxxxxxx'
19/11/22 11:58:32 - INFO - [login_flow]: You'll have to login to Twitch!
What browser do you use? Chrome (1), Firefox (2), Other (3): 3                                                        19/11/22 11:58:38 - INFO - [login_flow_backup]: Your browser is unsupported, sorry.                                   
19/11/22 11:58:38 - INFO - [run]: 🤓  Loading data for 1 streamers. Please wait...
19/11/22 11:58:39 - INFO - [run]: 😢  Streamer stylishnoob4 does not exist                                            
19/11/22 11:58:40 - WARNING - [warning]: websocket connected                                                          19/11/22 11:58:40 - ERROR - [error]: error from callback <function WebSocketsPool.on_message at 0x7afc683a60>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'nW9TvY8ZDUdnT5uf8hP3QW35V9al4z'}
19/11/22 11:58:40 - ERROR - [on_error]: #0 - WebSocket error: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'nW9TvY8ZDUdnT5uf8hP3QW35V9al4z'}                                             ^C19/11/22 11:58:45 - INFO - [end]: CTRL+C Detected! Please wait just a moment!                                       
19/11/22 11:58:45 - INFO - [on_close]: #0 - WebSocket closed                                                                                                                     
19/11/22 11:58:59 - INFO - [__print_report]: 🛑  Ending session: 'xxxxxxxxxxxxx'
19/11/22 11:58:59 - INFO - [__print_report]: 📄  Logs file: /data/data/com.termux/files/home/Twitch-Channel-Points-Miner-v2/logs/B4kedBr3ad.log                                  19/11/22 11:58:59 - INFO - [__print_report]: ⌛  Duration 0:00:26.225765
```

**Comment by Kazushi-0** [comment]
> I started it with Termux and when I ran it, it questioned my browser. So I selected 3. I got an error and could not log in. What should I do?
> 
> Log:
> 
> ```
> ~/Twitch-Channel-Points-Miner-v2 $ python run.py           
> 19/11/22 11:58:32 - INFO - [run]: 💣  Start session: 'xxxxxxxxxxxxx'
> 19/11/22 11:58:32 - INFO - [login_flow]: You'll have to login to Twitch!
> What browser do you use? Chrome (1), Firefox (2), Other (3): 3                                                        19/11/22 11:58:38 - INFO - [login_flow_backup]: Your browser is unsupported, sorry.                                   
> 19/11/22 11:58:38 - INFO - [run]: 🤓  Loading data for 1 streamers. Please wait...
> 19/11/22 11:58:39 - INFO - [run]: 😢  Streamer stylishnoob4 does not exist                                            
> 19/11/22 11:58:40 - WARNING - [warning]: websocket connected                                                          19/11/22 11:58:40 - ERROR - [error]: error from callback <function WebSocketsPool.on_message at 0x7afc683a60>: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'nW9TvY8ZDUdnT5uf8hP3QW35V9al4z'}
> 19/11/22 11:58:40 - ERROR - [on_error]: #0 - WebSocket error: Error while trying to listen for a topic: {'type': 'RESPONSE', 'error': 'ERR_BADAUTH', 'nonce': 'nW9TvY8ZDUdnT5uf8hP3QW35V9al4z'}                                             ^C19/11/22 11:58:45 - INFO - [end]: CTRL+C Detected! Please wait just a moment!                                       
> 19/11/22 11:58:45 - INFO - [on_close]: #0 - WebSocket closed                                                                                                                     
> 19/11/22 11:58:59 - INFO - [__print_report]: 🛑  Ending session: 'xxxxxxxxxxxxx'
> 19/11/22 11:58:59 - INFO - [__print_report]: 📄  Logs file: /data/data/com.termux/files/home/Twitch-Channel-Points-Miner-v2/logs/B4kedBr3ad.log                                  19/11/22 11:58:59 - INFO - [__print_report]: ⌛  Duration 0:00:26.225765
> ```

Try using this fork : https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/1.5.0
fix some miner issue

**Comment by B4kedBr3ad** [comment]
Thank you so much.
It's work!
