### ISSUE TITLE
One channel (and only one) gives a long error every time it should collect points

### ISSUE THREAD

**Issue by chronoquairium** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#666]
I don't have any idea why, but it's _just_ one channel doing it, and all 12 others work perfectly. I checked the run.py and it is formatted correctly. Yes, this happens every 5 minutes.

![errorr](https://user-images.githubusercontent.com/68948661/204362552-4c5798b7-6759-4f2b-91bd-f1480520309a.PNG)

**Comment by rdavydov** [comment]
`__save_json` is the key to understand what's wrong.

**Comment by rdavydov** [comment]
.json file is broken. That happens when you didn't end the program gracefully.

**Comment by rdavydov** [comment]
Easy solution: just delete analytics/streamername.json.

Or even disable Analytics if you don't need it. I will save you from future errors like this.

You can disable Analytics in my fork: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/

**Comment by chronoquairium** [comment]
1. How would you even end the program without just closing Git Bash?
2. I'm not sure what Analytics does in particular, but the only thing I want to see out of the program is this text.

![image](https://user-images.githubusercontent.com/68948661/204405548-9f3e405b-1035-4202-bdb0-b149135960b1.png)

**Comment by rdavydov** [comment]
1. Ctrl+C
2. Then disable Analytics (use [my fork](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/))

**Comment by chronoquairium** [comment]
Does not help answer the question. What does Analytics do specifically, so that I know whether I need to get the fork or not? I modified some files beyond just run.py so I'd rather not get a new version if I don't have to.

**Comment by rdavydov** [comment]
> how are you even meant to close the program in a graceful manner?

Already answered, CTRL+C.



> What does Analytics do specifically

Read the README.

**Comment by chronoquairium** [comment]
Alright, am sorry. Didn't connect the dots somehow on Ctrl-C because of it being its own hotkey for copying, and honestly forgot the README had most of that stuff lol. My bad, thank you though.
