### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ArtemBay** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#667]
**Cant login**

**To Reproduce**
1. idk, just check [code](https://hastebin.com/yihudatupi.properties)

**Desktop:**
 - OS: Ubuntu Linux 20.04
 - Python version: 3.8.10

While login i gets this error:
![image](https://user-images.githubusercontent.com/31122393/205906904-6243079a-5645-4769-90dd-3950a7522ed1.png)

**Comment by rdavydov** [comment]
That's because this repo is outdated.

Try my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/ as it has many fixes and improvements and is constantly evolving.

**Comment by ArtemBay** [comment]
Should i edit anything?

**Comment by ArtemBay** [comment]
I tested and i think no. Thanks
