### ISSUE TITLE
Execute outside the directory doesnt detect saved login

### ISSUE THREAD

**Issue by heyimrendy** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#67]
**Describe the bug**
When executing the program outside cloned directory it doesnt detect saved login.

**To Reproduce**
1. Go  to cloned directory, do normal login flow.
2. And then, CD to other directory. For example program cloned into `home/programming/miner`.
3. Run `/home/programming/miner/env/bin/python3 /home/programming/miner/run.py`.
4. Program asking to login again while existing config exist.

**Expected behavior**
Detect config path from `.py` path.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python version 3.8.6

**Comment by Tkd-Alex** [comment]
Why you need to execute the script from another directory?

**Comment by heyimrendy** [comment]
Im running script with multiple account from vps with systemd, I guess I could tweak my settings. Just to let others know if they run into similar error.

**Comment by Tkd-Alex** [comment]
It's normal because the entire code use: `Path.absolute()`
I had a similar issue in another project. If you have a cronjob and/or systemd you can try:
- `cd /home/folder/where/is/the/repo; env/bin/python run1.py`
- `cd /home/folder/where/is/the/repo; env/bin/python run2.py` 

Or use: **WorkingDirectory** for systemd

**Comment by heyimrendy** [comment]
Testing with `WorkingDirectory` resolve the path correctly now. Should I close this if in the future the path for this project will remain `Path.absolute()` and won't change?

**Comment by Tkd-Alex** [comment]
yes, close
