### ISSUE TITLE
I'm getting Twitch API Error code: 5023

### ISSUE THREAD

**Issue by ssoaora** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#673]
**Describe the bug**
Currently on Ubuntu 20.04 LTS, Python 3.8.10
I'm getting Twitch API Error code: 5023. Message shows 'Please update your app to continue' and 'client is not supported for this feature'

![image](https://user-images.githubusercontent.com/63569586/207243193-d30a6fd7-3fe8-4c4a-a6c9-73926c11c7b4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Python version: 3.8.10

**Additional context**
Does anyone have this same issue?

**Comment by rdavydov** [comment]
Same as https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/issues/85#issuecomment-1347896421

**Comment by J0J0HA** [comment]
[rdavydov/Twitch-Channel-Points-Miner-v2](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/pulls) has this fixed.
