### ISSUE TITLE
Uh-oh, Twitch has detected this miner as a "Bad Bot"

### ISSUE THREAD

**Issue by andreaconfa** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#679]
What does this mean? :  Uh-oh, Twitch has detected this miner as a "Bad Bot" when i start the bot

**Comment by andreaconfa** [comment]
any news?

**Comment by Kazushi-0** [comment]
> any news?

https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/discussions/34#discussion-4539294
