### ISSUE TITLE
Points not for every streamer

### ISSUE THREAD

**Issue by jurmarr** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#686]
Hi, I've got an issue:
I've followed about 50 people on twitch, right now 11 people are streaming, but in app, there are only 2 streamers shown. And I can't gain points on every streamer's channel. How can I fix it? 

I expected, that if 11 streamers are streaming at the moment, I will gain points on every streamer's channel, that is streaming rn.

Windows, Python 3.10.5

**Comment by zehelnehil** [comment]
it will only mine from the first two streamers you added in the code, twitch doesnt allow to collect in many streams at once ig
