### ISSUE TITLE
Exception raised with: button[data-a-target="consent-banner-accept"]

### ISSUE THREAD

**Issue by vadrozh** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#7]
20/01/21 15:15:22 - ERROR - [__click_when_exist]: Exception raised with: button[data-a-target="consent-banner-accept"]
Traceback (most recent call last):
  File "/home/vadrozh/Twitch/TwitchChannelPointsMiner/classes/TwitchBrowser.py", line 284, in __click_when_exist
    expected_conditions.element_to_be_clickable((by, selector))
  File "/home/vadrozh/.local/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Tkd-Alex** [comment]
Does it happen every time you open the script or randomly?
The problem seems to be on bootstrap process, please try with `BrowserSettings(show: True)` and see what's up

![image](https://user-images.githubusercontent.com/14061593/105174053-459f1000-5b22-11eb-8bc7-6aad06467529.png)

**Comment by vadrozh** [comment]
it runs on VPS, so it's impossible to check browser
it happens every run

**Comment by Tkd-Alex** [comment]
Ok, please try to edit the code as follow:

**Comment by Tkd-Alex** [comment]
Ok, please edit the file `TwitchChannelPointsMiner/classes/TwitchBrowser.py` and add `self.__debug(event, "click_on_cookies")` before line 128. So we can have a screen of the Window. Remember also `BrowserSettings(do_screenshot: True)`

Should became:
```python
        self.__debug(event, "click_on_cookies")
        self.__click_when_exist(cookiePolicyQuery, By.CSS_SELECTOR)
        time.sleep(1.5)
```

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/ddc8be3068a640676613a7ad6f06fcbcc490fdf6/TwitchChannelPointsMiner/classes/TwitchBrowser.py#L127-L129

**Comment by vadrozh** [comment]
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    followers=False  # Automatic download the list of your followers
  File "/home/vadrozh/Twitch/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 70, in mine
    self.run(streamers, followers)
  File "/home/vadrozh/Twitch/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 126, in run
    self.twitch_browser.init()
  File "/home/vadrozh/Twitch/TwitchChannelPointsMiner/classes/TwitchBrowser.py", line 105, in init
    self.__init_twitch()
  File "/home/vadrozh/Twitch/TwitchChannelPointsMiner/classes/TwitchBrowser.py", line 128, in __init_twitch
    self.__debug(event, "click_on_cookies")
NameError: name 'event' is not defined

**Comment by Tkd-Alex** [comment]
Oh sorry, you are right! Try this please :)

```python
self.browser.save_screenshot("click_on_cookies.png")
with open(""click_on_cookies.html", "w", encoding="utf-8") as writer:
    writer.write(self.browser.page_source)
self.__click_when_exist(cookiePolicyQuery, By.CSS_SELECTOR)
time.sleep(1.5)
```

**Comment by Element21** [comment]
I'm getting this issue also. I think it's because once you accept it the first time it saves that you've accepted it in a cookie or something, so you don't need to press it every time.

**Comment by Element21** [comment]
We just need a check to make sure the element exists

**Comment by Tkd-Alex** [comment]
It's strange because I don't have this error. I don't know If It's because you are running on VPS, I use a Raspberry pi 4 without any problem. Anyways It's just a error message the script should continue to work, but I'll do check before click on the "Accept cookies" button to prevent any issues

**Comment by Tkd-Alex** [comment]
Suppress the error in the last commit, so don't worry ;D

**Comment by Element21** [comment]
@Tkd-Alex Can we please close this issue?

**Comment by Tkd-Alex** [comment]
I'd like an answer from @vadrozh 
Anyway don't worry If the issues still open, I have configured a stale-bot for this 😁

**Comment by vadrozh** [comment]
No errors on #6e1f74c
