### ISSUE TITLE
Predictions: negative bet value 

### ISSUE THREAD

**Issue by testdev123456** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#70]
on small channels with no many people betting.. I've experienced :

```python
 10/02/21 13:28:15 - INFO - TwitchChannelPointsMiner.classes.Twitch - [make_predictions]: Place -3 channel points on: Yes (PINK), Points: 0, Users: 0 (0%), Odds: 0 (0%)
```

Stealth_mode=true

we should check the bet amount to be at least 10 points (the minimum).  and if Stealth_mode=true and the current amount of bets is  10 or ZERO .. to skip/avoid the prediction.   right?

**Comment by Tkd-Alex** [comment]
You can place bet also LTE 10 If you set a custom value from the website.
For the negative values It's really strange

Because I've already put an If condition: 

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/c0134edfd3b0abf332485836fc31e15c0af435ea/TwitchChannelPointsMiner/classes/Twitch.py#L235-L239

It's in the commit: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/175d6abe126dfba8b1942e4787f449c21d724f0e

**Comment by testdev123456** [comment]
I catched those errors on feb.10 ... I see the commit 175d6ab was pulled on feb.11.   didn't think it would address that issue.


 problem should be fixed..  thanks!!  <3

**Comment by testdev123456** [comment]
Sorry, i opened it again to ask....

shouldn't it be 

` if decision["amount"] > 10: `

because the minimum allowed bet amount is 10

**Comment by Tkd-Alex** [comment]
I expand the code-line :laughing: 
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/c0134edfd3b0abf332485836fc31e15c0af435ea/TwitchChannelPointsMiner/classes/Twitch.py#L235-L250

It's more clear now? As I already said If you want you can place a manual bet lower than 10.

**Comment by Tkd-Alex** [comment]
But ... OK! I'll fix to GTE 10

**Comment by testdev123456** [comment]
Sorry, I thought the minimum allowed was 10 points.
It's on the twitch terms https://www.twitch.tv/p/es-es/legal/predictions-terms-and-conditions/

thanksss!!!!!!

**Comment by testdev123456** [comment]
I just manually  tested  to bet 4 points and I was allowed !! 
i feel bad now.... the original code   `> 0:`    should be the one to keep!!   maybe someone wants o always bet 1 point just to 'participate' and now they can't.

sorry!  twitch terms are outdated I guess...

**Comment by Tkd-Alex** [comment]
Maybe the terms are update, but the developer have forget to set a value >10 :laughing: 
Don't worry. We will keep >= 10
