### ISSUE TITLE
help

### ISSUE THREAD

**Issue by CoolioTT** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#701]
![image](https://user-images.githubusercontent.com/110967917/219913822-24f77199-2ddb-48ed-9023-1cce2a9bd662.png)

how do i fix this?

**Comment by Dotyam** [comment]
Also trying to get through this issue since 2 days

**Comment by FMB684** [comment]
I have the same error

**Comment by rdavydov** [comment]
Fixed in my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2
