### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by r0dok** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#702]
I am having this problem whenever I am starting the script. 

> File "Twitch-Channel-Points-Miner-v2-master\run.py", line 74, in <module>
>     twitch_miner.mine(
>   File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 150, in mine
>     self.run(streamers=streamers, blacklist=blacklist, followers=followers)
>   File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 236, in run
>     self.twitch.load_channel_points_context(streamer)
>   File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 420, in load_channel_points_context
>     if response["data"]["community"] is None:
> KeyError: 'data'

I have not changed anything, just happened when I restarted the script after I had to reboot my computer

This is what I get when I debug the script in VS Code:

> Exception has occurred: KeyError
> 'data'
>   File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 420, in load_channel_points_context
>     if response["data"]["community"] is None:
>   File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 236, in run
>     self.twitch.load_channel_points_context(streamer)
>   File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 150, in mine
>     self.run(streamers=streamers, blacklist=blacklist, followers=followers)
>   File "Twitch-Channel-Points-Miner-v2-master\run.py", line 74, in <module>
>     twitch_miner.mine(
> KeyError: 'data'

This is what I get in the problems tab: 
![image](https://user-images.githubusercontent.com/93918376/219961154-89d4bab0-209b-40b3-8428-278fce23d3c1.png)
![image](https://user-images.githubusercontent.com/93918376/219961163-2d377ea8-3c03-45fe-b789-fbb60166526b.png)
![image](https://user-images.githubusercontent.com/93918376/219961180-b44fe9b3-7364-405b-b81f-fd5985f63771.png)

**Comment by Kazushi-0** [comment]
> I am having this problem whenever I am starting the script.
> 
> > File "Twitch-Channel-Points-Miner-v2-master\run.py", line 74, in 
> > twitch_miner.mine(
> > File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 150, in mine
> > self.run(streamers=streamers, blacklist=blacklist, followers=followers)
> > File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 236, in run
> > self.twitch.load_channel_points_context(streamer)
> > File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 420, in load_channel_points_context
> > if response["data"]["community"] is None:
> > KeyError: 'data'
> 
> I have not changed anything, just happened when I restarted the script after I had to reboot my computer
> 
> This is what I get when I debug the script in VS Code:
> 
> > Exception has occurred: KeyError
> > 'data'
> > File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 420, in load_channel_points_context
> > if response["data"]["community"] is None:
> > File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 236, in run
> > self.twitch.load_channel_points_context(streamer)
> > File "Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 150, in mine
> > self.run(streamers=streamers, blacklist=blacklist, followers=followers)
> > File "Twitch-Channel-Points-Miner-v2-master\run.py", line 74, in 
> > twitch_miner.mine(
> > KeyError: 'data'
> 
> This is what I get in the problems tab: ![image](https://user-images.githubusercontent.com/93918376/219961154-89d4bab0-209b-40b3-8428-278fce23d3c1.png) ![image](https://user-images.githubusercontent.com/93918376/219961163-2d377ea8-3c03-45fe-b789-fbb60166526b.png) ![image](https://user-images.githubusercontent.com/93918376/219961180-b44fe9b3-7364-405b-b81f-fd5985f63771.png)

try take a look at https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2 Forked

**Comment by r0dok** [comment]
![image](https://user-images.githubusercontent.com/93918376/219969233-cae3ce6c-c82b-4a1f-bfb6-703198076b5a.png)

Still having the same issue, although bit different now with the forked version

**Comment by JPDL8901** [comment]
Getting the same issue since the past few days, nothing on my end changed.

**Comment by YodaGaming** [comment]
I'm also getting this issue

**Comment by rdavydov** [comment]
Fixed in my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2
