### ISSUE TITLE
 Websocket connected

### ISSUE THREAD

**Issue by zenko2** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#707]
![Скриншот 25-02-2023 083959](https://user-images.githubusercontent.com/68221131/221340674-2b6e83b1-1ccf-4342-86a2-2b7bbbb3c8cb.jpg)

when I start, I get a screen that does not even show the number of followers, I launch it not for the first time before everything worked, but yesterday it stopped

**Comment by abdulelah2737** [comment]
same issue

**Comment by Ozakinn** [comment]
Same issue. Dont know how to fix it.

**Comment by zenko2** [comment]
I updated everything that I could and it didn't help, but today everything worked by itself and now it writes how many points I have accumulated from the streamer, maybe I didn't notice it before

**Comment by rdavydov** [comment]
Fixed in my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2
