### ISSUE TITLE
not loading follower/  Load 0 followers from your profile!

### ISSUE THREAD

**Issue by abdulelah2737** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#708]
![Screenshot_20230225_094449](https://user-images.githubusercontent.com/108159777/221376672-a0c516c2-27cc-433b-a09c-f7eac7ee10ed.png)
![image](https://user-images.githubusercontent.com/108159777/221376957-5cdedec7-b735-4e3e-98b4-c30e4aa93cb2.png)

**Comment by m7-killer** [comment]
I  have the some problem

**Comment by HypaCNH** [comment]
You fixed it somehow? Had the same bug
