### ISSUE TITLE
How to speed up the search cycle of streamers online? 

### ISSUE THREAD

**Issue by Nokenter** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#711]
How to speed up the search cycle of streamers online?

**Comment by comrademedic** [comment]
Hey! This repo is no longer maintained by its creator as confirmed by https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/bbe5aba323e941b8f189e295509db3f3a45c8a36. If you did not already you can submit this to the updated one instead! That being: [rdavydov/Twitch-Channel-Points-Miner-v2](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2 )
