### ISSUE TITLE
Notify on user mention

### ISSUE THREAD

**Issue by Telain** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#717]
Useful for streams that may have giveaways for people in chat.

When in IRC, support sending a notification with a link to the channel if your username is mentioned.

**Comment by comrademedic** [comment]
Hey! This repo is no longer maintained by its creator as confirmed by https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/bbe5aba323e941b8f189e295509db3f3a45c8a36. If you did not already you can submit this to the updated one instead! That being: [rdavydov/Twitch-Channel-Points-Miner-v2](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2 )
