### ISSUE TITLE
HTTPS logs can be seen on Ubuntu

### ISSUE THREAD

**Issue by TMShader** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#72]
**Describe the bug**
The app works perfectly but when using Ubuntu, HTTPS connection logs can be seen:
![image](https://user-images.githubusercontent.com/43723765/107855744-68bc9700-6e24-11eb-8572-a34c2452af7a.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the app
2. See weird HTTPS logs

**Expected behaviour**
On windows, these logs do not appear.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.8.7

**Additional context**
I ran the same config on Windows and Ubuntu. Weird HTTPS Logs are only present on Ubuntu.

**Comment by Tkd-Alex** [comment]
With `logging.INFO`?

**Comment by TMShader** [comment]
Yes

**Comment by Tkd-Alex** [comment]
Strange. I've these logs message on ArchLinux but only with `logging.DEBUG` :thinking:

**Comment by TMShader** [comment]
Yeah. I'll try something out and I'll tell you if it worked

**Comment by TMShader** [comment]
Ok it didn't :( I tried setting the file info thing to logging.INFO but that didn't fix it

**Comment by TMShader** [comment]
Do you know which library or file makes these outputs?

**Comment by Tkd-Alex** [comment]
Please try to edit the mail class file

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/4dbd85018415960d05dba9e53185959d8b17eda3/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py#L32-L37

Add the following: `logging.getLogger("urllib3").setLevel(logging.ERROR)`
Tell me if this will fix your problem.

**Comment by TMShader** [comment]
No sadly it didn't :(

**Comment by Tkd-Alex** [comment]
`logging.getLogger("requests").setLevel(logging.ERROR)`

Whit this? 😂😂

**Comment by TMShader** [comment]
Yay that worked! Thank you so much! If you add this to the official code, does it break it in any ways? Because if it didn't, you should add this.

**Comment by Tkd-Alex** [comment]
Yes I'll do

**Comment by Tkd-Alex** [comment]
I re-open the issue.
Will be closed with the commit
