### ISSUE TITLE
Don't run

### ISSUE THREAD

**Issue by MkasSASD** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#723]
1. Go to folder
2. Click on run.py

 - OS: Windows 11
 - Python version Python 3.9.10

![image](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/assets/43532096/360265d3-78e8-45f2-8e6f-8781cc690279)

**Comment by MkasSASD** [comment]
i'ts not outdated version Miner

**Comment by Verygafanhot** [comment]
Use [This Fork](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2)

**Comment by MkasSASD** [comment]
Thanks

**Comment by MkasSASD** [comment]
Thanks
