### ISSUE TITLE
Load streamers while running run.py

### ISSUE THREAD

**Issue by Yishaqel** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#73]
Isn't there an alternative way to check in a faster way if a twitch user is online?  If it were implemented it would improve the speed of loading this utility as I for example have 84 people in a row and I usually change the settings quite often.

**Comment by Tkd-Alex** [comment]
It's related to: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/62
If you think the bootstrap phase It's too slow try to remove the sleep for each streamer.

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/2771aa41c62b919ae18f608ad7c559f89e363295/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py#L174-L180
