### ISSUE TITLE
High amount of DNS Requests from Twitch Miner

### ISSUE THREAD

**Issue by r3df0chs** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#742]
**Describe the bug**
I use a DNS Filter and the Twitch Channel Miner Docker is the device in my network with the most requests.
All my other devices have only a small part of the requests. Its no big issue but i thought maybe someone can check this.
Is it possible that the miner is not caching DNS Entrys? The 2 most quested Domains are "www.twitch.tv" and "gql.twitch.tv"
Which are alright but i dont understand why its necessary all 2 Minutes.

**To Reproduce**
Only let the Miner run.

**Expected behavior**
That the client is caching the DNS Entrys and only requests after an TTL period

**Desktop (please complete the following information):**
Linux Distribution and Twitch Channel Point Miner runs in Docker, latest version.

**Comment by T0biii** [comment]
maybe https://pypi.org/project/requests-cache/ could mitigate this
for experation see: https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html

@Cebrain try maybe out the updatet Version of this project:
https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

**Comment by r3df0chs** [comment]
Thanks, will test the new repo and would reopen the ticket.
