### ISSUE TITLE
Tutorial for temux request

### ISSUE THREAD

**Issue by notshariq** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#76]
I would love a tutorial for termux please make it happen

**Comment by Jarsa132** [comment]
First you need to install Python on your Termux.
To do this, type this command:
`pkg install python`

(1 way):
Then you need to get GIT
`pkg install git`

(2 way):
Download sources from GitHub and put it into your Termux storage

Now you can enter directory with our miner, do this by typing this command:
`cd Twitch-Channel-Points-Miner-v2`

Configure your miner on your preferences by typing
`nano example.py`

When you have configured it now we can rename it (optional):
`mv example.py run.py`

We have to also install dependiences required to run miner:
`pip install -r requirements.txt`

Now when we did everything we can run miner:
`python run.py`

**Comment by Tkd-Alex** [comment]
@notshariq works? :smile_cat:
