### ISSUE TITLE
Cannot type in password

### ISSUE THREAD

**Issue by schizzio** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#77]
**Describe the bug**
When trying to type in my password in the run.py file it simply won't let me type anything

**To Reproduce**
1. Create .txt file
2. Save as .py file
3. Open run.py
4. Window asks for twitch password and I cannot type

**Expected behavior**
I should be able to just start typing my password

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.9.1

**Additional context**

**Comment by Tkd-Alex** [comment]
Have you a screen of the error?
The password input is hidden, have you already tired to type and then press enter?

**Comment by kelukelol** [comment]
It's typing already, just not showing it to you since it's hidden.

**Comment by Tkd-Alex** [comment]
@schizzio news? are you able to login and use the script or not?
