### ISSUE TITLE
Error data-test-selector="prediction-checkout-active-footer__input-type?-toggle"

### ISSUE THREAD

**Issue by FelixPanzer** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#8]
Seems to be a betting error. Happened multiple times in a row but after that didnt happen for a while.
![Bildschirmfoto 2021-01-20 um 14 15 07](https://user-images.githubusercontent.com/77693637/105181539-36bd5b00-5b2c-11eb-9ee6-ec40827ac9ba.png)

**Comment by Tkd-Alex** [comment]
Strange issue, I think I'ts only because the system It's currently in another bet.
The browser can handle only one prediction per time, If you read the log there are multiple prediction

**Comment by SiIason** [comment]
Just had this same issue, first time, no previous bet active I believe.

```
02/02/21 23:36:50 - ERROR - [__click_when_exist]: Exception raised with: //div[@data-test-selector="community-points-summary"]//button
Traceback (most recent call last):
  File "<removed>\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\TwitchBrowser.py", line 240, in __click_when_exist
    element = WebDriverWait(self.browser, timeout).until(
  File "<removed>\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

02/02/21 23:36:50 - WARNING - [__execute_script]: Failed to execute: document.querySelector("[data-test-selector='community-points-summary']").getElementsByTagName("button")[0].click();
02/02/21 23:36:50 - ERROR - [start_bet]: Attempt 3 failed!
```

**Comment by Tkd-Alex** [comment]
You should have the screen of the failed action named `f89ce06b-62e8-4ede-bba6-fdbf9d509929_*`
So we can see why It's failed.

**Comment by SiIason** [comment]
I don't have screenshots on, will change that now.
