### ISSUE TITLE
Error when trying to setup the bot on rasbian on a raspberry pi 3b

### ISSUE THREAD

**Issue by mrcsdl** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#86]
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ilz4libs -Ipy3c -I/usr/include/python2.7 -c lz4/_version.c -o build/temp.linux-armv7l-2.7/lz4/_version.o -O3 -Wall -Wundef
    In file included from lz4/_version.c:38:0:
    py3c/py3c.h:28:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-j4GmZx/lz4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-L0UeMy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-j4GmZx/lz4/

can you help me with that error?

**Comment by Tkd-Alex** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/0e743786-3345-4365-b184-1527a5112508-0c230afe-4f2b-4a6d-a61c-5e97da59f558-v1.png?transparent=1&palette=1&width=246)

This is insane :rofl: 
Are you able to run other Python project on this machine? You should try to upgrade to Python3.

**Comment by mrcsdl** [comment]
iam running python3 on my raspi. this comes when i try to use pip install -r requirements.txt

**Comment by Tkd-Alex** [comment]
You could try to set up a virtual env :thinking:

**Comment by mrcsdl** [comment]
so far so good i managed it to run the pip install now this error pops up 

:~/Twitch-Channel-Points-Miner-v2# python3 run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 104
    f"Start session: '{self.session_id}'", extra={"emoji": ":bomb:"}
                                        ^

**Comment by Tkd-Alex** [comment]
`python3 --version` ?

**Comment by mrcsdl** [comment]
Python 3.5.3

**Comment by RakSrinaNa** [comment]
`f"..."` were introduced in Python 3.6. So I guess you need to have at least that.

Apt repositories on raspberry takes quite some time to update Python versions.
Probably an idea to install it manually and not from apt. Latest version is Python 3.9.1. Python 3.5.3 is already 4 years old...

**Comment by mrcsdl** [comment]
I’ll update it. And try it again. Thanks for the help
