### ISSUE TITLE
Prioritize based on points amount.

### ISSUE THREAD

**Issue by KableK42** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#87]
Would be nice to have an option to prioritize streams that have the fewest points for WATCH and CLAIMs instead of using the order they are listed in.

EDIT: Might need to ignore streams with 0 points if it doesn't already, not sure how this script handles channels that don't have channel points enabled.

**Comment by Tkd-Alex** [comment]
I've missed something, why you have cited WATCH and CLAIM? We can easily sort by channel points, but for example if you have gained the points with bet or other system obv this will be part of total amount

**Comment by KableK42** [comment]
I only cited WATCH & CLAIM because bets/predictions don't really need prioritization, it seems to catch all of them anyway while watch and claim points benefit from prioritization because you can only get those points from 2 channels at a time.

**Comment by Tkd-Alex** [comment]
OK perfect, I just want to make sure that we are talking about the same things :rofl: 
It's an easy update, I'll do after merged some pull request
