### ISSUE TITLE
Cannot launch the script, syntax error.

### ISSUE THREAD

**Issue by shaakz** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#88]
When i do python run.py i get the following error:

Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/shaakz/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/shaakz/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 60
    username: str,
                   ^
SyntaxError: invalid syntax

Edit: it doesnt show the ^ in the correct place here, it points to the :

**Comment by Tkd-Alex** [comment]
Guys I don't understand why but there is a template for submit a bug, but nobody uses it :cry: 
I need at least OS and Python version. `python --version`
It's the same problem of #86

**Comment by shaakz** [comment]
My bad, that was kind of vague, and i solved the issue, but this was my info:
 - OS: Linux server 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Python version: 3.8.5
 
How i solved it: my linux was defaulting to python as running python2 for some reason, using python3 run.py worked like it should, running python --version showed 2.7.18, which showed me why it didnt work.
