### ISSUE TITLE
Strategy option to go with the most % voted.

### ISSUE THREAD

**Issue by StephanBruh** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#9]
**Describe the solution you'd like**
Strategy option to go with the most % voted.

**Additional context**
In most of the streams I watch/bet almost always the highest % wins and not where most people voted in.
![image](https://user-images.githubusercontent.com/19285400/105232005-0c898e80-5b68-11eb-8b0c-58677b874629.png)

**Comment by Tkd-Alex** [comment]
I've already done a commit for this, I need just to push on GitHub 😂

**Comment by StephanBruh** [comment]
> I've already done a commit for this, I need just to push on GitHub 😂

Oh 😂 will close it then asap when you pushed it
