### ISSUE TITLE
option to customize timezone in reports

### ISSUE THREAD

**Issue by testdev123456** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#90]
self-explanatory...
Would be nice to customize the timezone shown in terminal/reports.  It comes handy when running it from the cloud.

**Comment by Tkd-Alex** [comment]
You can't change the timezone on your machine? :rofl:

**Comment by testdev123456** [comment]
shared machine.. don't have privileges to change..

**Comment by RakSrinaNa** [comment]
You can probably do `TZ=Asia/Bangkok python3 main.py` to set the timezone.

**Comment by testdev123456** [comment]
thank you @RakSrinaNa . I'll try that !
