### ISSUE TITLE
Tool stops collecting after awhile

### ISSUE THREAD

**Issue by deion** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#91]
running multiple instances of the tool, each from its own folder/copy and each with its own account.

Collects fine for a few minutes then stops collecting all together across all instances

**Comment by Tkd-Alex** [comment]
Please attach the debug log file.

**Comment by deion** [comment]
for all instances?

**Comment by deion** [comment]
https://file.io/SR1MuKJ0fk0J

**Comment by deion** [comment]
update 1 is still collecting and the others are not

**Comment by Tkd-Alex** [comment]
> https://file.io/SR1MuKJ0fk0J

![image](https://user-images.githubusercontent.com/14061593/109044575-d8f3d400-76d2-11eb-92d1-43adc2189e94.png)

**Comment by deion** [comment]
try this one
https://filebin.net/4tyd4biwjjtq09sp

**Comment by Tkd-Alex** [comment]
After this line we are unable to send the minute watch request
`24/02/21 12:53:45 - DEBUG - urllib3.connectionpool - [_new_conn]: Starting new HTTPS connection (1): video-edge-858f41.pdx01.abs.hls.ttvnw.net:443`
Please edit the following, so we can try what is the problem:
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/189e60a4aad766ae3c0926288fd4ae51cfc82cf1/TwitchChannelPointsMiner/classes/Twitch.py#L326-L362

```python
response = requests.post(
    streamers[index].stream.spade_url,
    data=streamers[index].stream.encode_payload(),
    headers={"User-Agent": self.user_agent},
    timeout=25  # <-----
)

except Exception as e:
```

**Comment by deion** [comment]
do i add

```
response = requests.post(
    streamers[index].stream.spade_url,
    data=streamers[index].stream.encode_payload(),
    headers={"User-Agent": self.user_agent},
    timeout=25  # <-----
)

except Exception as e:
```

as a replacement to all of what you linked above or do i put it at the end

**Comment by Tkd-Alex** [comment]
Replace, you just add the string timeout on line 330 and replace `requests.exceptions.ConnectionError` with Exception

**Comment by deion** [comment]
seems to be okay right now, going to load a few more instances and i will update either when i notice an issue or in 2-3 hours

**Comment by deion** [comment]
Update: 
`24/02 14:28:26 - +10 --> ops1x (278.55k points) - Reason: WATCH.
24/02 14:30:17 - Error while trying to send minute watched: HTTPSConnectionPool(host='video-edge-858f41.pdx01.abs.hls.ttvnw.net', port=443): Read timed out. (read timeout=25)
24/02 14:31:11 - l2coop (75.82k points) is Online!`

**Comment by Tkd-Alex** [comment]
Uhm on **bab__y** there are errors? Or something else? :thinking:  Seems to be all OK.
____
> The default timeout is None, which means it'll wait (hang) until the connection is closed.

That's why on the current master branch you have this problem and the script stop to collect. I'll release a hot fix for this :smile_cat:

**Comment by deion** [comment]
ohhh, i see now. So its giving an error in the console but still collecting.
