### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by MelovZaebl** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#92]
Add termux version or documentation how to use it with termux.

Script can 24/7 work on ur phone.

**Comment by kelukelol** [comment]
Not sure if this will work, but try https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/76#issuecomment-780795995 and let me know if this will work. If it doesn't, I will try and help you asap.

**Comment by Tkd-Alex** [comment]
i will never understand why to run python scripts on mobile 🤷‍♂️

btw if the solution on #76 work I'll write on README

@MelovZaebl for the next time please check if there are other similar issues open before open a new one.

**Comment by MelovZaebl** [comment]
> Not sure if this will work, but try [#76 (comment)](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/76#issuecomment-780795995) and let me know if this will work. If it doesn't, I will try and help you asap.

Error when trying to download required modules

**Comment by Tkd-Alex** [comment]
I think you should share your error or a screenshot :)

**Comment by MelovZaebl** [comment]
> i will never understand why to run python scripts on mobile 🤷‍♂️
> 
> btw if the solution on #76 work I'll write on README
> 
> @MelovZaebl for the next time please check if there are other similar issues open before open a new one.
Sorry, I'm new to github + I don't know English well

**Comment by MelovZaebl** [comment]
> I think you should share your error or a screenshot :)

When write "pip install -r requirements.txt"
![1](https://user-images.githubusercontent.com/73187010/109174666-dd89bc80-77a6-11eb-8a3c-84311f768878.jpg)
![2](https://user-images.githubusercontent.com/73187010/109174671-debae980-77a6-11eb-97e1-8aba0d60299c.jpg)
![3](https://user-images.githubusercontent.com/73187010/109174672-df538000-77a6-11eb-87bb-800815adbdb4.jpg)
![4](https://user-images.githubusercontent.com/73187010/109174673-df538000-77a6-11eb-838c-05220d6c9f14.jpg)
![5](https://user-images.githubusercontent.com/73187010/109174675-dfec1680-77a6-11eb-86b6-d87e1b3faf82.jpg)
![6](https://user-images.githubusercontent.com/73187010/109174678-dfec1680-77a6-11eb-87b6-71c9d42740cf.jpg)
![7](https://user-images.githubusercontent.com/73187010/109174680-e084ad00-77a6-11eb-9ce4-d596c08bd1cb.jpg)

When write "python example.py" after that
`Traceback (most recent call last):
File "example.py", line 4, in <module>
from TwitchChannelPointsMiner import TwitchChannelPointsMiner
File "/storage/emulated/0/Download/Twitch/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
File "/storage/emulated/0/Download/Twitch/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 21, in <module>
from TwitchChannelPointsMiner.classes.Twitch import Twitch
File "/storage/emulated/0/Download/Twitch/TwitchChannelPointsMiner/classes/Twitch.py", line 25, in <module>
from TwitchChannelPointsMiner.classes.TwitchLogin import TwitchLogin
File "/storage/emulated/0/Download/Twitch/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 10, in <module>
import browser_cookie3
ModuleNotFoundError: No module named 'browser_cookie3'`

**Comment by Tkd-Alex** [comment]
You could try the following: https://github.com/python-pillow/Pillow/issues/1957#issuecomment-304086698
`$ pkg install python libjpeg-turbo libcrypt ndk-sysroot clang zlib`
`$ LDFLAGS="-L${PREFIX}/lib/" CFLAGS="-I${PREFIX}/include/" pip install --upgrade wheel pillow`

And then `pip install -r requirements.txt`

**Comment by MelovZaebl** [comment]
Now error only with cryptography (last 2 screenshots)

**Comment by Tkd-Alex** [comment]
- `pkg install libcrypt-dev`
- `pkg install libffi-dev`

Reference in: https://github.com/termux/termux-packages/issues/2430

**Comment by MelovZaebl** [comment]
![Screenshot_2021-02-26-00-48-36-950_com.termux.png](https://user-images.githubusercontent.com/73187010/109208413-15572b00-77cc-11eb-9646-a0c93539bc4f.png)
This 2 strings output this

**Comment by Tkd-Alex** [comment]
Sorry, but I don't have a fix for you.
I'm just googling in search of solution, I think you can do the same :)

**Comment by Tkd-Alex** [comment]
However, If you read the screenshot termux suggest installing `libffi` instead of `libffi-dev`
So you can try the following:
- `pkg install libffi`
- `pip install -r requirements.txt`

**Comment by Kayo99** [comment]
Same issue here , I already tried your suggestions and google search solutions , none worked 
![Screenshot_20210226-035035933](https://user-images.githubusercontent.com/7613901/109248628-6ecc5380-77e6-11eb-83fe-0028e644209e.jpg)

**Comment by Kayo99** [comment]
I bring good news , it's seems I found a fix that's was really under my nose and literally in error logs , the fix is to install rust then you just run the requirements command.

Ps: I did install rust while on miner directory but I'm not sure if it's relevant or not.

> pkg install rust

> pip install -r requirements.txt

Here a few screenshot

![Screenshot_20210227-185810559](https://user-images.githubusercontent.com/7613901/109395897-240a2300-792f-11eb-86ac-33562d8ad67c.jpg)
![Screenshot_20210227-190249102](https://user-images.githubusercontent.com/7613901/109395900-28364080-792f-11eb-9c72-f673fcf175b4.jpg)
![Screenshot_20210227-190843531](https://user-images.githubusercontent.com/7613901/109395909-397f4d00-792f-11eb-8aa9-39fba0399633.jpg)

**Comment by Tkd-Alex** [comment]
:partying_face: Awesome, so the steps should be the following:

Install the requirements
`pkg install python git rust libjpeg-turbo libcrypt ndk-sysroot clang zlib`
`LDFLAGS="-L${PREFIX}/lib/" CFLAGS="-I${PREFIX}/include/" pip install --upgrade wheel pillow`

Clone this repository
`git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2`

(2 way):
Download sources from GitHub and put it into your Termux storage

Now you can enter the directory with our miner, do this by typing this command:
`cd Twitch-Channel-Points-Miner-v2`

Configure your miner on your preferences by typing
`nano example.py`

When you have configured it now we can rename it (optional):
`mv example.py run.py`

We have to also install dependences required to run miner:
`pip install -r requirements.txt`

Now when we did everything we can run miner:
`python run.py`

**Comment by spix18** [comment]
So i had to reinstall this on my android phone termux and ran into some issues specifically Cryptography issue , if anyone is still having issue building wheel for cryptography try this :

`pip install cryptography  --no-binary cryptography`

its should correctly finish the process and build wheel for cryptography if everything has ran like i described above then all you have to do is to run the requirement command again just to make sure all requirements are satisfied:

`pip install -r requirements.txt`

now you can go configure your `run.py` and `python run.py`

**Comment by 13Quavo** [comment]
I'm stuck on pip install pandas when installing `requirements.txt`  
Stuck on Getting requirements to build wheel. 

I'm on the latest version of Python.

**Comment by 13Quavo** [comment]
When I try to install numpy it said `failed building wheel for numpy`

**Comment by 13Quavo** [comment]
On the last requirement.txt installation. I'm stuck on building wheel for pandas (pyproject.toml) 
Any solution?

**Comment by 13Quavo** [comment]
> So i had to reinstall this on my android phone termux and ran into some issues specifically Cryptography issue , if anyone is still having issue building wheel for cryptography try this :
> 
> `pip install cryptography --no-binary cryptography`
> 
> its should correctly finish the process and build wheel for cryptography if everything has ran like i described above then all you have to do is to run the requirement command again just to make sure all requirements are satisfied:
> 
> `pip install -r requirements.txt`
> 
> now you can go configure your `run.py` and `python run.py`


Any solutions?  Failed building wheel for cryptography.

**Comment by UItimate** [comment]
> Any solutions? Failed building wheel for cryptography.

Try `pip install --upgrade cryptography==3.4.6 --no-binary cryptography`

**Comment by uzi98f** [comment]
![error](https://user-images.githubusercontent.com/125817798/219960582-2606eac1-f803-4381-8c8b-bec0291f00a1.jpg)
Hi I have this problem Im in the step of pip install -r requirements.txt im in termux, I also have another session with another git I already use pkg install python git rust libjpeg-turbo libcrypt ndk-sysroot clang zlib
LDFLAGS="-L${PREFIX}/lib/" CFLAGS="-I${PREFIX}/include/" pip install --upgrade wheel pillow

**Comment by spix18** [comment]
try with 
`MATHLIB="m" pip install pandas`

**Comment by uzi98f** [comment]
Hi spix18 thank you for you help I write the MATHLIB="m" pip install pandas  but this already have like 2 hours, its ok? or its bugged? I still have memory in the phone
![raro](https://user-images.githubusercontent.com/125817798/220017892-673a9ffd-8e21-4df1-994d-8e4b5a7b8352.jpg)

**Comment by uzi98f** [comment]
hi the "MATHLIB="m" pip install pandas" help me but now I have this problem when I tried to run the twith miner "python run.py"
![11](https://user-images.githubusercontent.com/125817798/220036461-765cd9a5-a4cc-4f76-a494-69bd043b97d3.jpg)
![22](https://user-images.githubusercontent.com/125817798/220036476-782c80e3-1d70-47ce-be09-d220031e321a.jpg)
![3_1](https://user-images.githubusercontent.com/125817798/220036483-142f9cb7-e70e-442b-a2e0-d4c35d649739.jpg)

**Comment by uzi98f** [comment]
maybe because I have two session the first with another git

**Comment by spix18** [comment]
Don't forget to modify "run.py" according to your needs (your twitch username and password and channels...etc) because in your first screenshot , you are NOT doing this , you just copy and rename "example.py" to "run.py"  and attempt to run it by typing "python run.py"

also after running `MATHLIB="m" pip install pandas`
you should also run `pip install -r requirements.txt` to make sure every requirements has been met.

**Comment by uzi98f** [comment]
ohh I think I understand my fail let me check xd thankyou again

**Comment by spix18** [comment]
No problem

**Comment by uzi98f** [comment]
https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/ do I use this one? its more update than the other,

**Comment by uzi98f** [comment]
yes I think thats the problem Im using the version of https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2 I get twitchapi error code 5023 I will tried with the rdavydov version:)

**Comment by uzi98f** [comment]
I think thats the problem Im using the version of https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2 I get twitchapi error code 5023 I will tried with the rdavydov version:) I will tryed this one https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/ its update

**Comment by uzi98f** [comment]
@spix18 Hi again, I want to farm 7 channels of twitch, there is a way to put in priority two channels, 
In case those two channels are on and others on my list are still on? I saw that you can only farm points from two channels at the same time.Or you can only farm 1 channel at the time?

**Comment by uzi98f** [comment]
I follow all step again I update pandas and cryptography:) I already install the two packages pip install -r requirements.txt
pip install Twitch-Channel-Points-Miner-v2 But now I have this 
![image](https://user-images.githubusercontent.com/125817798/220614299-f4f0534d-9975-463a-8439-94006194cbd5.png)
![image](https://user-images.githubusercontent.com/125817798/220614318-70ad1b5f-caea-4ec0-848c-ed69b717bbf1.png)

**Comment by uzi98f** [comment]
I follow all step again I update pandas and cryptography:) I already install the two packages pip install -r requirements.txt
pip install Twitch-Channel-Points-Miner-v2 But now I have this
![error chale](https://user-ima
![error chale 2](https://user-images.githubusercontent.com/125817798/220614557-fbb51815-b5fc-4c8b-81e1-329a6a3ccd51.png)
ges.githubusercontent.com/125817798/220614543-2e4f2eb9-3904-4f68-b246-9d1ea604ebd9.png)

**Comment by uzi98f** [comment]
I follow all step again I update pandas and cryptography:) I already install the two packages pip install -r requirements.txt
pip install Twitch-Channel-Points-Miner-v2 But now I have this

![error chale 2](https://user-images.githubusercontent.com/125817798/220614804-2daddadb-e24d-43a0-8fe9-9af2b5b3bd2a.png)
![error chale](https://user-images.githubusercontent.com/125817798/220614814-e802060c-54c8-452a-b729-3fbe00c8a063.png)

**Comment by uzi98f** [comment]
@spix18 hi bro how I can make my list of streamer but with priority? that follow my list of streamer? :) can you shared me how I need to write please:)

**Comment by spix18** [comment]
> @spix18 hi bro how I can make my list of streamer but with priority? that follow my list of streamer? :) can you shared me how I need to write please:)

no idea sorry
